// swift-tools-version: 5.9
import PackageDescription

// Generated by apps/tech/scripts/ios-sync.mjs — do not edit by hand.
let package = Package(
    name: "CapApp-SPM",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "CapApp-SPM",
            targets: ["CapApp-SPM"])
    ],
    dependencies: [
        .package(url: "https://github.com/ionic-team/capacitor-swift-pm.git", exact: "8.5.2"),
        .package(name: "AparajitaCapacitorBiometricAuth", path: "../Plugins/AparajitaCapacitorBiometricAuth"),
        .package(name: "AparajitaCapacitorSecureStorage", path: "../Plugins/AparajitaCapacitorSecureStorage"),
        .package(name: "CapacitorApp", path: "../Plugins/CapacitorApp"),
        .package(name: "CapacitorCamera", path: "../Plugins/CapacitorCamera"),
        .package(name: "CapacitorGeolocation", path: "../Plugins/CapacitorGeolocation"),
        .package(name: "CapacitorHaptics", path: "../Plugins/CapacitorHaptics"),
        .package(name: "CapacitorPushNotifications", path: "../Plugins/CapacitorPushNotifications")
    ],
    targets: [
        .target(
            name: "CapApp-SPM",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm"),
                .product(name: "AparajitaCapacitorBiometricAuth", package: "AparajitaCapacitorBiometricAuth"),
                .product(name: "AparajitaCapacitorSecureStorage", package: "AparajitaCapacitorSecureStorage"),
                .product(name: "CapacitorApp", package: "CapacitorApp"),
                .product(name: "CapacitorCamera", package: "CapacitorCamera"),
                .product(name: "CapacitorGeolocation", package: "CapacitorGeolocation"),
                .product(name: "CapacitorHaptics", package: "CapacitorHaptics"),
                .product(name: "CapacitorPushNotifications", package: "CapacitorPushNotifications")
            ]
        )
    ]
)
