# -*- coding: utf-8 -*-
# English translation overlay for TalqeenData (keys = ids in the Arabic source)
BOOK = {
    "title": "Talqīn al-Ṣibyān — Teaching Children What Every Person Needs",
    "author": "Nur al-Din Abdullah bin Humaid al-Salimi",
    "about": "A short, easy treatise on the first duties of a person when they become accountable, and on some of what they are commanded to do. The author arranged it as an introduction, two main parts and a conclusion, “in clear words that both the clever and the weak can understand.”",
    "structure": [
        "Introduction: what a child’s guardian is commanded to do in caring for and raising the child until maturity.",
        "Part One: the first beliefs a person must hold in the heart.",
        "Part Two: the first acts a person must perform with the limbs.",
        "Conclusion: what a person must avoid, whether bodily deeds or traits of the soul.",
    ],
}

CHAPTERS = {
    "intro": ("Introduction", "Caring for the Child", "What the guardian does until the child grows up"),
    "aqeedah": ("Part One", "Belief (ʿAqīdah)", "What a person must believe in the heart"),
    "salah": ("Part Two", "Prayer (Ṣalāh)", "The first duty after learning the belief"),
    "taharah": ("Part Two", "Purification & Conditions of Prayer", "Wudu, ghusl, tayammum and the eight conditions of prayer"),
    "janaiz": ("Part Two", "Funerals", "The funeral prayer and the rights of a deceased Muslim"),
    "sawm": ("Part Two", "Fasting", "Fasting the blessed month of Ramadan"),
    "huquq": ("Part Two", "Rights", "Parents, relatives, neighbours, companions and guests"),
    "zakah": ("Part Two", "Zakah", "A purely financial act of worship"),
    "hajj": ("Part Two", "Hajj & Umrah", "A journey to the Sacred House of Allah"),
    "jihad": ("Part Two", "Jihad", "An act of worship with one’s self and wealth"),
    "khatimah": ("Conclusion", "What Must Be Avoided", "Bodily deeds and inner traits a person must leave"),
}

LESSONS = {
    "wudu": ("Wudu (Ablution)", "Learn wudu step by step", "Talqīn al-Ṣibyān, pp. 61–64"),
    "ghusl": ("Ghusl (Full Bath)", "How to perform the ritual bath", "Talqīn al-Ṣibyān, pp. 65–66"),
    "tayammum": ("Tayammum", "When there is no water", "Talqīn al-Ṣibyān, pp. 64–65"),
    "salah": ("Prayer (Ṣalāh)", "The Dhuhr prayer step by step", "Talqīn al-Ṣibyān, pp. 33–38"),
}

STEPS = {
    "wudu_01": ("Clean water", "We make wudu with clean, pure water.", "Wudu is a condition of prayer, and it is only done with pure water.", None),
    "wudu_02": ("Bismillah", "At the start of wudu we say: Bismillah.", "Say Allah’s name at the beginning of wudu, as reported: “There is no wudu for one who does not mention Allah’s name over it.”", None),
    "wudu_03": ("Siwak", "It is Sunnah to use the siwak before wudu.", "It is Sunnah to clean the teeth with a siwak before wudu.", None),
    "wudu_04": ("Washing the hands", "After waking up, we wash our hands three times before putting them in the water container.", None, None),
    "wudu_05": ("Rinsing the mouth", "We rinse the mouth three times, thoroughly.", "Put a finger of the right hand in the mouth and take water to just before the throat; a fasting person should not gargle deeply.", "O Allah, give me to drink from the sealed pure drink (of Paradise)."),
    "wudu_06": ("Rinsing the nose", "We bring water to the nose with the right hand, then blow it out.", None, "O Allah, do not deprive me of the scents of Your Paradise, by Your mercy, O Most Merciful."),
    "wudu_07": ("Washing the face", "We wash the face three times.", None, "O Allah, brighten my face with Your light on the day the faces of Your righteous servants are brightened, O Most Merciful."),
    "wudu_08": ("Right arm", "We wash the right arm, including the elbow, three times.", None, "O Allah, give me my book in my right hand and make my reckoning easy."),
    "wudu_09": ("Left arm", "Then we wash the left arm, including the elbow, three times.", None, "O Allah, I seek refuge in You from being given my book in my left hand or from behind my back."),
    "wudu_10": ("Wiping the head", "We wipe the head with water.", None, "O Allah, shade me in the shade of Your Throne on the day there is no shade but Yours."),
    "wudu_11": ("Wiping the ears", "We wipe the ears, inside and outside.", "Some scholars recommended wiping the neck after the ears.", "O Allah, make me of those who listen to speech and follow the best of it."),
    "wudu_12": ("Right foot", "We wash the right foot up to the ankles three times.", None, "O Allah, keep my feet firm on the truth and the religion, by Your mercy, O Most Merciful."),
    "wudu_13": ("Left foot", "Then we wash the left foot up to the ankles three times.", "With this, wudu is complete and you are ready to pray!", None),
    "ghusl_01": ("Washing the hands", "We begin by washing the hands.", "Ghusl after major impurity is required for males and females, and the same is required of a woman when her period ends.", None),
    "ghusl_02": ("Removing impurity", "We remove any impurity from where it is.", None, None),
    "ghusl_03": ("Mouth and nose", "We rinse the mouth and the nose; these are required in every case.", None, None),
    "ghusl_04": ("Wudu parts", "We wash the face and the other parts of wudu as for prayer.", "If one does not do this, there is no harm, but rinsing the mouth and nose is necessary.", None),
    "ghusl_05": ("Three handfuls", "We pour three handfuls of water over the head.", None, None),
    "ghusl_06": ("The head", "We wash the right side of the head, then the left.", None, None),
    "ghusl_07": ("The neck", "We wash the right side of the neck, then the left.", None, None),
    "ghusl_08": ("The body", "We wash the right side of the body, then the left.", None, None),
    "ghusl_09": ("The legs", "We wash the right leg, then the left.", None, None),
    "ghusl_10": ("The whole body", "We pass the hand over the body with water until it reaches everywhere.", "If the whole body is covered with water without order, it is valid; but the water must cover the whole body while passing the hand over it.", None),
    "tayammum_01": ("When is tayammum?", "When we find no water, or we find it but cannot use it for wudu.", None, None),
    "tayammum_02": ("Clean earth", "We do tayammum with clean earth that has dust.", "Tayammum is not done with ash, gypsum, lime plaster, salt flats, sand or wet mud.", None),
    "tayammum_03": ("Bismillah and intention", "We say Allah’s name and intend to lift the impurity and make prayer allowed.", None, None),
    "tayammum_04": ("First strike", "We strike the earth with our palms.", None, None),
    "tayammum_05": ("Wiping the face", "We wipe our face with our palms.", None, None),
    "tayammum_06": ("Second strike", "We strike the earth a second time.", None, None),
    "tayammum_07": ("Wiping the hands", "We wipe both hands, back and front, up to the wrists.", "With this, tayammum is complete.", None),
    "salah_01": ("Getting ready", "We are clean in body and clothes, with wudu, in a clean place.", "One stands upright after being pure in body and clothes, free of all impurity, in a clean place fit for prayer.", None),
    "salah_02": ("Qiblah and intention", "We face the Kaaba and intend the Dhuhr prayer in our hearts, sincerely for Allah.", "Intend that very obligatory prayer in the heart, mindful of its number of rak‘ahs, sincere in worship to one’s Lord.", None),
    "salah_03": ("Saying the intention", "We confirm the intention with our tongue.", None, "I pray for Allah, Blessed and Exalted, in this place of mine, the obligatory Dhuhr prayer, four rak‘ahs, facing the noble Kaaba, fulfilling the obligation, in obedience to Allah and His Messenger Muhammad ﷺ."),
    "salah_04": ("Iqamah", "Then the iqamah, which is for males rather than females.", None, None),
    "salah_05": ("Tawjih", "We say the opening words of our Prophet Muhammad ﷺ.", None, "Glory be to You, O Allah, and praise; blessed is Your name, exalted is Your majesty, great is Your praise, and there is no god but You."),
    "salah_06": ("Ibrahim’s words", "Then we say the words of our father Ibrahim, peace be upon him.", None, "I have turned my face to the One who created the heavens and the earth, inclining to truth, and I am not of those who associate others with Allah."),
    "salah_07": ("Confirming the intention", "We confirm the intention once more.", None, "I pray for Allah the obligatory Dhuhr prayer, four rak‘ahs, and the Kaaba is my qiblah."),
    "salah_08": ("Opening takbir", "We say the opening takbir, then pause briefly.", None, "Allah is the Greatest."),
    "salah_09": ("Seeking refuge", "We seek refuge quietly, with a present heart.", None, "I seek refuge in Allah from the accursed Satan."),
    "salah_10": ("Al-Fatihah", "We say Bismillah and recite Surah Al-Fatihah to the end, then pause briefly.", "In Dhuhr, only Al-Fatihah is recited, quietly.", None),
    "salah_11": ("Bowing (Rukū‘)", "We bow with a takbir: palms on the knees and the back level.", "Keep the forearms and upper arms straight until the back is level; do not raise or lower the head.", "Glory be to my Lord, the Most Great."),
    "salah_12": ("Rising from bowing", "We raise our head to standing.", "On rising say: “Allah hears whoever praises Him,” and when upright say: “Our Lord, and to You belongs all praise.”", "Allah hears whoever praises Him… Our Lord, and to You belongs all praise."),
    "salah_13": ("Prostration (Sujūd)", "We prostrate with a takbir: knees first, then hands, then nose and forehead.", "Prostrate on seven parts: the forehead, both hands, both knees and both feet, keeping the upper arms away from the sides.", "Glory be to my Lord, the Most High."),
    "salah_14": ("Sitting between prostrations", "We rise with a takbir and sit until every joint settles in its place.", None, None),
    "salah_15": ("Second prostration", "We prostrate again, just like the first.", None, "Glory be to my Lord, the Most High."),
    "salah_16": ("Second rak‘ah", "We stand with a takbir: forehead, then hands, then knees; we recite Al-Fatihah, then bow and prostrate.", None, None),
    "salah_17": ("First tashahhud", "After the second prostration we sit and recite the tahiyyat.", None, "The blessed greetings are for Allah, and the prayers and good things; peace be upon the Prophet and the mercy of Allah and His blessings; peace be upon us and upon the righteous servants of Allah. I bear witness that there is no god but Allah alone, without partner, and I bear witness that Muhammad is His servant and Messenger."),
    "salah_18": ("Third rak‘ah", "We stand with a takbir, recite only Al-Fatihah, then bow and prostrate.", None, None),
    "salah_19": ("Fourth rak‘ah", "We stand with a takbir, recite only Al-Fatihah, then bow and prostrate.", None, None),
    "salah_20": ("Final tashahhud", "We sit and recite the tahiyyat as before.", "After “His servant and Messenger” one may add: “ﷺ, He sent him with guidance and the religion of truth to make it prevail over all religion, even if the polytheists dislike it. Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.”", None),
    "salah_21": ("Taslim", "Then we give the salam, and the prayer is complete. Well done!", None, None),
}

MASAIL = {
    "intro-1": ("What the child’s guardian must do", "The guardian protects the child and chooses what is best.", [
        "To care for and raise the child, and protect them from anything harmful to their body, character or wealth.",
        "To choose what is best for the child in all matters, keeping them from what is improper and discouraging what is not good.",
        "Discipline is only as much as benefits the child; if the child obeys without being struck, striking is forbidden.",
        "To command the child to do the parts of Islam they are able to: avoiding impurities, cleaning them, and keeping clean from dirt.",
    ]),
    "intro-2": ("Teaching the child Islam before maturity", "We learn to pray from age seven, and to fast when we are able.", [
        "The guardian teaches the child to pray at seven years old, and teaches its conditions and duties.",
        "He does not strike them for leaving it until they reach ten, as reported: “Command them to pray at seven, and discipline them for it at ten.”",
        "He commands the child to fast Ramadan when able, so the child does not grow used to abandoning the rites of Islam.",
        "He teaches the child the Glorious Qur’an, good literature from Arab poetry and history, and wisdom suited to the child’s mind.",
        "He protects the child’s wealth and does what is best for it until the child reaches maturity.",
    ]),
    "aq-1": ("No obligations on a child", "Nothing is obligatory on a child until maturity.", [
        "As long as they are a child, no belief or act is obligatory upon them.",
        "They are commanded some things only as part of upbringing and training, not as an obligation.",
    ]),
    "aq-2": ("Signs of maturity", "When a sign of maturity appears, a person becomes accountable.", [
        "Signs of maturity include wet dreams, or hair growing in the usual places.",
        "Or reaching fifteen years of age according to the most correct view; it is also said seventeen.",
        "For a girl also: menstruation, pregnancy, or the development of the chest.",
        "When one of these signs appears, the rulings of an adult apply, and the person becomes responsible for worship and for avoiding what is forbidden.",
    ]),
    "aq-3": ("The first duty after maturity", "The first duty: to know that Allah is your Creator and the Creator of everything.", [
        "To know that one has a Maker who made them and a Creator who created them, bringing them from nothing into existence.",
        "That this Creator is the One who brought everything into being and created all that exists.",
        "That all creation needs Him, and He needs none of it.",
        "That He is described with perfection, unlike anything in essence, states or actions.",
        "That the name of the Creator who created them and all things is: Allah.",
    ]),
    "aq-4": ("What is impossible for Allah", "Allah is free of every imperfection.", [
        "Allah cannot be described with any attribute of imperfection.",
        "Ignorance, weakness, blindness, deafness, being contained in places and coming into being in time are impossible for Him.",
        "It is impossible for things to indwell in Him, just as it is impossible for Him to indwell in them.",
        "It is impossible for Him to be seen with eyes, or for His essence to be grasped by the eye, the heart or any other sense — all of that is imperfection, and our Lord is far above it.",
    ]),
    "aq-5": ("What Allah must be described with", "Allah is Eternal, Living, Knowing, Powerful, Hearing, Seeing and Everlasting.", [
        "He must be described with perfection: Eternal, Living, Knowing, Powerful, Willing, Hearing, Seeing, Everlasting, never ceasing.",
        "He is Knowing by His essence, Powerful by His essence, Willing by His essence, Seeing by His essence and Living by His essence.",
        "That is, His essence has these perfections without needing additional attributes, so that He never needs anything else.",
        "Glorified is He: self-sufficient and perfect in His essence.",
    ]),
    "aq-6": ("What is possible for Allah", "Out of His grace, Allah sent messengers and revealed books.", [
        "It is possible for Him to send messengers, reveal books, create creation, cause them to die, resurrect them, gather them, judge them, reward them and punish them.",
        "Allah has favoured us by sending messengers and revealing books, and gave us responsibility after the proof reached us, out of His grace.",
    ]),
    "aq-7": ("Prophets, messengers and books", "The first messenger was Adam and the last is Muhammad ﷺ.", [
        "The messengers number three hundred and thirteen.",
        "The first of them is Adam, peace be upon him, a messenger to his children.",
        "The last of them is Muhammad ﷺ, a messenger to all: Arabs and non-Arabs, humans and jinn.",
        "The prophets number one hundred and twenty-four thousand, among them the three hundred and thirteen messengers.",
        "The books number one hundred and four: fifty to Seth, thirty to Idris, ten to Ibrahim (his scrolls) and ten to Musa before the Torah.",
        "Then the Torah to Musa, the Injil to ‘Isa, the Zabur to Dawud and the Qur’an to Muhammad, peace and blessings be upon them all.",
    ]),
    "aq-8": ("Believing in the prophets and books", "We believe in all messengers and books, and specifically in Muhammad ﷺ and the Qur’an.", [
        "Believing in all the messengers and all the books in general is obligatory.",
        "General belief is enough, except for Muhammad ﷺ and the Glorious Qur’an.",
        "Every accountable person must believe specifically in Muhammad ﷺ and what was revealed to him.",
        "And must believe specifically in any messenger or book whose proof has reached them.",
    ]),
    "aq-9": ("Attributes of the messengers", "Messengers have necessary, impossible and possible attributes.", [
        "After the proof reaches them, the accountable person must know that messengers have attributes necessary for them.",
        "And attributes impossible for them.",
        "And attributes possible for them, like other people.",
    ]),
    "aq-10": ("Necessary attributes of messengers", "Truthfulness, trustworthiness, conveying the message and intelligence.", [
        "Truthfulness in what they tell.",
        "Trustworthiness.",
        "Conveying from their Lord what He commanded them to convey.",
        "Preserving precisely what they were commanded to preserve.",
        "Intelligence and alertness in their speech and conduct.",
    ]),
    "aq-11": ("Impossible attributes of messengers", "Messengers do not lie and do not betray.", [
        "Lying and betrayal.",
        "Carelessness about their Lord’s commands.",
        "Inability to express themselves, and dullness.",
        "None of this is possible for them.",
    ]),
    "aq-12": ("Possible attributes of messengers", "Messengers are human: they eat, drink and walk in the markets.", [
        "Eating and drinking.",
        "Mixing with people and walking in the markets.",
        "Having wives, companions and children, and so on.",
    ]),
    "aq-13": ("The angels", "The angels never disobey what Allah commands them.", [
        "One must know that Allah has angels, a kind of creation different from humans and jinn.",
        "They do not disobey Allah in what He commands them, and they do what they are commanded.",
        "They do not eat or drink, and are described as neither male nor female.",
        "They are a creation Allah made to worship Him and to carry out His commands.",
    ]),
    "aq-14": ("Death and what follows", "Death is true, and everything perishes except Allah.", [
        "One must know that death is true: it is the soul leaving the body.",
        "And that everything will perish except Allah, the Exalted.",
    ]),
    "aq-15": ("Resurrection, reckoning and reward", "People will be raised on the Day of Resurrection, then comes Paradise or the Fire.", [
        "One must know that every human will be raised on the Day of Resurrection; this raising is the coming of the Hour.",
        "That they will be gathered before their Lord and judged as our Lord wills.",
        "That Allah has a reward named Paradise, prepared for those who obey Him; nothing is like it, and whoever enters it never leaves, dies or falls ill.",
        "That Allah has a punishment named the Fire, prepared for the sinners of major sins; may Allah protect us from it and from what brings one near it.",
    ]),
    "aq-16": ("Fear and hope", "We hope for Allah’s reward and fear His punishment.", [
        "The accountable person must hope for Allah’s reward and fear His punishment.",
        "It is said one must keep fear and hope equal: too much fear risks despair, and too much hope risks feeling safe from Allah’s plan.",
        "The apparent view is that equality is not required; as long as one does not reach forbidden despair or forbidden false security, there is no harm.",
    ]),
    "aq-17": ("Divine decree", "Nothing moves or stays still except by Allah’s will.", [
        "One must know that nothing moves and nothing rests in all existence except by Allah’s will and decree.",
    ]),
    "aq-18": ("Blessings and the declaration", "The greatest blessing upon us is Islam.", [
        "One must know Allah’s blessings upon them: existing after not existing, health after illness, and the greatest of them, Islam.",
        "All of this falls under the “Jumlah” (declaration): “There is no god but Allah, Muhammad is the Messenger of Allah, and what Muhammad brought from his Lord is the truth.”",
        "When the accountable person bears witness to this declaration, they become a believing Muslim before Allah and people, unless they break it by denying, not knowing or doubting any part of it.",
    ]),
    "aq-19": ("Loyalty, disassociation and suspension", "We love the allies of Allah and disassociate from His enemies.", [
        "One must be loyal to all the allies of Allah from first to last, and disassociate from all the enemies of Allah; this is general loyalty and general disassociation.",
        "Then be loyal to those known to be allies among the leaders of the Muslims and their righteous, and disassociate from those known to be enemies among the unjust leaders.",
        "And suspend judgement about anyone whose state is unknown until something is known that requires loyalty or disassociation.",
    ]),
    "sl-0": ("Types of practical worship", "Worship is bodily, financial, or both.", [
        "Acting with the limbs is of two kinds: bodily worship and financial worship.",
        "Financial worship: zakah, and giving rights to those they belong to, like debts, the guest’s right and the neighbour’s right.",
        "Purely bodily worship: prayer and its duties, fasting, keeping ties with relatives and with neighbours.",
        "Bodily and financial worship: what needs spending money, such as Hajj and jihad.",
    ]),
    "sl-1": ("Prayer", "Five prayers every day and night.", [
        "Prayer is purely bodily worship, obligatory on the accountable person five times every day and night.",
        "It is the first of the duties after learning the belief.",
    ]),
    "sl-2": ("The Dhuhr prayer", "Four rak‘ahs with Al-Fatihah recited quietly.", [
        "At Dhuhr time four rak‘ahs are obligatory, reciting Al-Fatihah quietly in each rak‘ah and adding nothing else from the Qur’an.",
        "Then one is encouraged to pray two rak‘ahs after them, reciting Al-Fatihah and a surah in each.",
        "Then two more voluntary rak‘ahs are recommended, with Al-Fatihah and a surah.",
        "All of this recitation is quiet.",
    ]),
    "sl-3": ("The Asr prayer", "Four rak‘ahs with only Al-Fatihah, quietly.", [
        "At Asr time four rak‘ahs are obligatory: the “Asr obligatory prayer”.",
        "In each rak‘ah only Al-Fatihah is recited, and the recitation is quiet.",
    ]),
    "sl-4": ("The Maghrib prayer", "Three rak‘ahs, then two Sunnah rak‘ahs.", [
        "At Maghrib time three rak‘ahs are obligatory: Al-Fatihah and a surah in the first two, and only Al-Fatihah in the third.",
        "The imam recites aloud in the first two and quietly in the third; the follower and the one praying alone recite quietly in all three.",
        "The follower behind the imam recites only Al-Fatihah, quietly.",
        "Two rak‘ahs after Maghrib are a confirmed Sunnah, and two more voluntary rak‘ahs are recommended after them.",
    ]),
    "sl-5": ("The Isha prayer", "Four rak‘ahs, then two rak‘ahs after it.", [
        "At the time of the later Isha, four rak‘ahs are obligatory.",
        "In the first two, Al-Fatihah and a surah: aloud for an imam, quietly for one praying alone.",
        "In the last two, only Al-Fatihah, quietly.",
        "One is encouraged to pray two rak‘ahs after this obligatory prayer, with Al-Fatihah and a surah.",
    ]),
    "sl-6": ("The Witr prayer", "Three rak‘ahs between Isha and Fajr.", [
        "Between the later Isha and Fajr there are three rak‘ahs, the “Witr”, with Al-Fatihah and a surah in all of them.",
        "The author counted it as obligatory; Abu Ishaq Atfayyish commented that the correct view is that it is a confirmed Sunnah, like the Sunnahs of Maghrib and Fajr.",
    ]),
    "sl-7": ("The Fajr prayer", "Two Sunnah rak‘ahs, then two obligatory rak‘ahs.", [
        "When dawn breaks, two rak‘ahs are Sunnah, the “Sunnah of Fajr”, with Al-Fatihah and a surah.",
        "Then two rak‘ahs are obligatory, the “Fajr obligatory prayer”, with Al-Fatihah and a surah in each.",
        "Aloud for an imam, quietly for one praying alone; the follower recites only Al-Fatihah quietly.",
    ]),
    "sl-8": ("Prayer times", "Each prayer has a start and an end time.", [
        "Dhuhr: starts when the sun passes its zenith, and ends when every object’s shadow equals its length beyond the zenith shadow.",
        "Asr: starts when the shadow grows a little beyond the end of Dhuhr, and ends when part of the sun has set; it is also said when the sun turns yellow.",
        "Maghrib: starts when the whole sun has set, and ends when the red twilight disappears; it is also said the white.",
        "Isha: starts when the twilight has fully gone, and ends at a third of the night; it is also said half the night.",
        "Fajr: starts at the true dawn, and ends when part of the sun has risen.",
    ]),
    "sl-9": ("Times when prayer is not allowed", "Prayer is forbidden at three times.", [
        "When part of the sun has risen: prayer is delayed until it has fully risen.",
        "When part of the sun has set: prayer is not allowed until it has fully set.",
        "When the sun stands at its highest point in intense heat: one does not pray until it passes the zenith.",
        "Voluntary prayer is forbidden after Fajr prayer until sunrise and after Asr until sunset, and disliked after dawn except the two rak‘ahs of Fajr.",
    ]),
    "sl-10": ("How to pray", "Purity, then the qiblah, then a sincere intention for Allah.", [
        "Stand upright after being pure in body and clothes, free of all impurity, in a clean place.",
        "Face the Kaaba and intend that very obligatory prayer in the heart, mindful of its rak‘ahs, sincere to one’s Lord.",
        "It is good to confirm the intention with the tongue, saying for example: “I pray for Allah, Blessed and Exalted, in this place of mine, the obligatory Dhuhr prayer, four rak‘ahs, facing the noble Kaaba, fulfilling the obligation, in obedience to Allah and His Messenger Muhammad ﷺ.”",
    ]),
    "sl-11": ("The adhan and what follows", "The iqamah, then the opening words, then confirming the intention.", [
        "Then the iqamah for males, not females; likewise the adhan is for males.",
        "Then say the opening of our Prophet ﷺ: “Glory be to You, O Allah, and praise; blessed is Your name, exalted is Your majesty, great is Your praise, and there is no god but You.”",
        "Then add the opening of our father Ibrahim: “I have turned my face to the One who created the heavens and the earth, inclining to truth, and I am not of the polytheists.” [Al-An‘am: 79]",
        "Then confirm the intention: “I pray for Allah the obligatory Dhuhr prayer, four rak‘ahs, and the Kaaba is my qiblah.”",
    ]),
    "sl-12": ("The opening takbir and the first rak‘ah", "Allahu Akbar… then Al-Fatihah, bowing and prostrating.", [
        "Say the opening takbir: “Allahu Akbar”, then pause briefly.",
        "Seek refuge quietly: “I seek refuge in Allah from the accursed Satan”, then say Bismillah and recite Al-Fatihah.",
        "Bow with a takbir, palms on the knees until the back is level, and say “Glory be to my Lord, the Most Great” three times.",
        "Rise saying “Allah hears whoever praises Him”, and when upright say “Our Lord, and to You belongs all praise.”",
        "Prostrate with a takbir, putting down the knees, then the hands, then the nose and forehead, on seven parts: forehead, hands, knees and feet, saying “Glory be to my Lord, the Most High” three times.",
        "Rise with a takbir and sit until every joint settles, then prostrate again like the first.",
    ]),
    "sl-13": ("The second rak‘ah", "We stand with a takbir and recite Al-Fatihah.", [
        "Stand for the second rak‘ah with a takbir finished before standing fully, lifting the forehead first, then the hands, then the knees.",
        "Say Bismillah and recite Al-Fatihah, then pause briefly.",
        "Then bow and prostrate as in the first rak‘ah.",
    ]),
    "sl-14": ("The first tashahhud", "We sit after the second rak‘ah for the tahiyyat.", [
        "Rise from the second prostration to sit for the tahiyyat, the “first tashahhud”, and say:",
        "“The blessed greetings are for Allah, and the prayers and good things; peace be upon the Prophet and the mercy of Allah and His blessings; peace be upon us and upon the righteous servants of Allah. I bear witness that there is no god but Allah alone, without partner, and I bear witness that Muhammad is His servant and Messenger.”",
    ]),
    "sl-15": ("The third rak‘ah", "Only Al-Fatihah, then bowing and prostrating.", [
        "Stand for the third rak‘ah with a takbir finished before standing straight.",
        "Recite only Al-Fatihah while standing.",
        "Then bow, rise and prostrate as before.",
    ]),
    "sl-16": ("The fourth rak‘ah", "Only Al-Fatihah, then bowing and prostrating.", [
        "Stand for the fourth rak‘ah with a takbir and recite only Al-Fatihah.",
        "Then bow and prostrate as before.",
    ]),
    "sl-17": ("The final tashahhud and taslim", "We recite the tashahhud and give salam; the prayer is complete.", [
        "Sit for the tahiyyat, the “final tashahhud”, and recite it as before.",
        "On reaching “and I bear witness that Muhammad is His servant and Messenger”, one may give salam, and the prayer is complete.",
        "Or one may add: “ﷺ, He sent him with guidance and the religion of truth to make it prevail over all religion, even if the polytheists dislike it. Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire,” then give salam.",
    ]),
    "sl-18": ("How to pray Maghrib", "Two rak‘ahs then tashahhud, then the third with Al-Fatihah only.", [
        "Pray the first two rak‘ahs with Al-Fatihah and a surah, then sit and recite the tashahhud up to “His servant and Messenger”.",
        "Then stand for the third, recite only Al-Fatihah, bow and prostrate, recite the final tashahhud and give salam.",
    ]),
    "sl-19": ("Praying behind an imam", "We never go ahead of the imam.", [
        "The follower only recites Al-Fatihah in every rak‘ah of every prayer.",
        "Behind the imam one does not say “Allah hears whoever praises Him”, but says “Our Lord, and to You belongs all praise” after the imam says it.",
        "One must not go ahead of the imam in anything — takbir, recitation, bowing or rising; whoever goes ahead of him, their prayer is invalid.",
        "Likewise if one falls far behind the imam the prayer is invalid; one should follow slightly after him.",
    ]),
    "sl-20": ("Joining the prayer late", "What you missed with the imam, you make up after his salam.", [
        "If the follower arrives after the imam has started, they join him, pray what they catch, then stand after the imam’s salam to make up what they missed.",
        "If only Al-Fatihah was missed, they stand, recite it, sit and give salam, without takbir.",
        "If a whole rak‘ah was missed, they stand without takbir, seek refuge and recite, bow and prostrate, stand with a takbir, then sit and give salam.",
        "The rule: make up exactly what was missed, without adding or reducing.",
    ]),
    "sl-21": ("Prayer while travelling", "The traveller shortens four-rak‘ah prayers to two.", [
        "When travelling, you must shorten Dhuhr, Asr and the later Isha to two rak‘ahs each.",
        "If you pray each in its own time, say: “I pray for Allah the obligatory Dhuhr, two rak‘ahs, shortened, a traveller’s prayer.”",
        "It is recommended to pray the Sunnahs and voluntary prayers you pray at home; there is no harm in leaving them, except the Sunnah of Maghrib.",
    ]),
    "sl-22": ("Combining two prayers", "When travelling we combine Dhuhr with Asr, and Maghrib with Isha.", [
        "You may combine Dhuhr and Asr at one time, and Maghrib and Isha at one time, earlier or later.",
        "Say: “I pray for Allah the obligatory Dhuhr, two rak‘ahs, and the obligatory Asr, two rak‘ahs, combining them, traveller’s prayers.”",
        "After the salam of the first, stand for the second with iqamah, opening words and the opening takbir.",
        "You may combine the Witr with the two evening prayers; Sunnahs and voluntary prayers need no iqamah.",
    ]),
    "sl-23": ("What cannot be shortened; the prayer of fear", "Maghrib and Fajr are not shortened except for fear or illness.", [
        "Nothing of Maghrib or Fajr may be shortened except for fear or an illness that prevents completing them.",
        "The prayer of facing the enemy: the army divides into two groups; each group prays one rak‘ah with the imam, then all give salam with him.",
        "The prayer of close combat: if one cannot pray by actions or gestures, one says five takbirs for each obligatory prayer.",
        "The prayer of general fear: they pray however they can, on foot or riding.",
    ]),
    "sl-24": ("The prayer of the sick", "The sick person prays according to their ability.", [
        "The sick person may reduce from the prayer and its duties what they cannot do.",
        "If unable to purify with water, they do tayammum; if unable to stand, they pray sitting.",
        "If unable to sit, they pray lying on the right side facing the qiblah, nodding the head for bowing and prostrating.",
        "If unable, they say five takbirs for the obligatory prayer; if unable even to do that, they are excused, for Allah burdens no soul beyond its capacity.",
    ]),
    "sl-25": ("The Friday prayer", "Two rak‘ahs in congregation with adhan, sermon and iqamah.", [
        "On Friday Dhuhr is shortened and prayed as two rak‘ahs with the imam: the “Friday prayer”.",
        "It is only prayed in congregation, with an adhan, a sermon and an iqamah.",
        "The muezzin calls the adhan after noon, then the imam gives the sermon: he praises Allah, sends blessings on the Prophet and advises the people without making it long.",
        "Then the muezzin gives the iqamah and the imam leads two rak‘ahs, reciting aloud.",
        "No one speaks while the imam gives the sermon; they listen to it.",
    ]),
    "sl-26": ("Sunnahs of Friday", "Bathing, the best clothes and perfume.", [
        "It is Sunnah to take a bath on Friday for whoever will attend, as one bathes after major impurity.",
        "It is Sunnah to wear one’s best clothes and the best perfume one has.",
        "It is disliked to step over people’s necks; one sits wherever there is space.",
    ]),
    "sl-27": ("The two Eid prayers", "Two rak‘ahs with thirteen takbirs.", [
        "The prayer of Eid al-Fitr and Eid al-Adha is a communal obligation: two rak‘ahs in congregation, with the imam reciting aloud.",
        "One says: “I pray for Allah the Sunnah of Eid al-Fitr (or al-Adha), two rak‘ahs with thirteen takbirs, facing the noble Kaaba.”",
        "After the opening takbir, five takbirs, then the recitation, then bowing and prostrating.",
        "In the second: the recitation, then five takbirs, then bowing, then three takbirs after rising, then prostrating, tashahhud and salam.",
        "It is prayed in the open prayer ground, unlike Friday which is prayed in the central mosque.",
    ]),
    "sl-28": ("The Eid sermon", "The imam begins it with takbir.", [
        "After the prayer the imam gives a sermon, beginning with takbir, while the people listen.",
        "He advises them to fear Allah, tells them what is required of them on that day, and gives them good advice.",
    ]),
    "th-1": ("Conditions of prayer", "Prayer has eight conditions without which it is not complete.", [
        "First: not praying while needing to relieve oneself.",
        "Second: cleaning oneself after the toilet and washing impurities from the body.",
        "Third: wudu with pure water.",
        "Fourth: ghusl after major impurity.",
        "Fifth: the natural hygiene practices commanded by our father Ibrahim.",
        "Sixth: a clean place. Seventh: clean clothing that covers. Eighth: facing the qiblah.",
    ]),
    "th-2": ("Toilet manners", "We cover ourselves, enter with the left foot and leave with the right.", [
        "Do not pray while needing the toilet; go and relieve yourself first.",
        "Go far away and cover yourself from people, and do not face or turn your back to the qiblah when relieving yourself.",
        "Do not relieve yourself where people sit, in their shade, under fruit trees or in water.",
        "Enter with the left foot and say: “I seek refuge in Allah from the filthy, impure, accursed Satan.”",
        "Leave with the right foot and say: “Praise be to Allah who removed the harm from me.”",
        "The toilet is the opposite of the mosque: the mosque is entered with the right foot and left with the left; the home is entered and left with the right.",
    ]),
    "th-3": ("Istinja (washing after the toilet)", "Cleaning with water until the impurity is gone.", [
        "One must wash impurities from the body wherever they are, including washing with water after the toilet when able.",
        "If one does not wash with water when able, neither wudu nor prayer is complete.",
        "There is no fixed number; the aim is cleanliness and removing the impurity, not counting rubs.",
    ]),
    "th-4": ("Types of impurity", "We wash impurities from the body and clothes.", [
        "Impurities include: urine, stool, flowing blood and vomit.",
        "The dung and urine of predators, and the urine of all animals.",
        "Dead animals, pigs and dogs.",
        "One must avoid these things and wash what touches the body and clothes.",
    ]),
    "th-5": ("Wudu and how to do it", "Mouth, nose, face, arms, head, ears, feet.", [
        "Make wudu with pure water and say Allah’s name at the start.",
        "Rinse the mouth three times thoroughly, unless fasting.",
        "Then rinse the nose and blow out, then wash the face three times.",
        "Then wash the right arm with the elbow three times, then the left likewise.",
        "Then wipe the head, then wipe the ears inside and out.",
        "Then wash the right foot to the ankles three times, then the left likewise.",
    ]),
    "th-6": ("Some Sunnahs and supplications of wudu", "The siwak, and beautiful supplications for each part.", [
        "It is Sunnah to use the siwak before wudu, and after waking to wash the hands three times before putting them in the container.",
        "When rinsing the mouth: “O Allah, give me to drink from the sealed pure drink.”",
        "When washing the face: “O Allah, brighten my face with Your light on the day the faces of Your righteous servants are brightened.”",
        "When washing the right arm: “O Allah, give me my book in my right hand and make my reckoning easy.”",
        "When wiping the head: “O Allah, shade me in the shade of Your Throne on the day there is no shade but Yours.”",
        "When washing the feet: “O Allah, keep my feet firm on the truth and the religion, by Your mercy, O Most Merciful.”",
    ]),
    "th-7": ("Tayammum", "If we find no water, we do tayammum with clean earth.", [
        "If one finds no water, or finds it but cannot use it for wudu, one does tayammum with clean earth.",
        "Strike the earth with both palms, then wipe the face with them.",
        "Then strike a second time and wipe both hands, back and front, to the wrists.",
        "Say Allah’s name, intending to lift the impurity and make prayer allowed.",
    ]),
    "th-8": ("What tayammum may and may not be done with", "Tayammum is done with earth that has dust.", [
        "Tayammum is not done with ash, gypsum, lime plaster, salt flats, sand or wet mud.",
        "It is only done with earth that has dust.",
        "If that cannot be found, one uses what most resembles earth.",
    ]),
    "th-9": ("Ghusl after major impurity", "Ghusl is required for one in major impurity, and for a woman when her period ends.", [
        "Ghusl is required for one in a state of major impurity, male or female.",
        "The same ghusl is required of a woman when her menstruation ends.",
        "Prayer is not complete without it when water is available; if there is none, one does tayammum as for prayer.",
    ]),
    "th-10": ("How to do ghusl", "We start with the right, and water must cover the whole body.", [
        "Wash the hands, remove impurity from its places, then rinse the mouth and nose.",
        "Then wash the face and the other wudu parts; if one does not, there is no harm, but rinsing mouth and nose is necessary.",
        "Pour three handfuls on the head, then wash the right of the head then the left, the right of the neck then the left.",
        "Then the right of the body then the left, then the right leg then the left, passing the hand over the body with the water.",
        "If water covers the whole body without order it is valid, but it must cover the whole body with the hand passing over it.",
    ]),
    "th-11": ("Some Sunnahs of our father Ibrahim", "Natural hygiene and cleanliness.", [
        "One is commanded to shave the pubic hair when it grows long; it is said monthly, or every forty days.",
        "And to pluck the armpits, trim the moustache, clip the nails and part the hair if it is long.",
        "These are among the practices our father Ibrahim, peace be upon him, was commanded with.",
    ]),
    "th-12": ("Places where prayer is allowed", "We choose a clean place for our prayer.", [
        "Choose a clean place for prayer.",
        "Do not pray in the middle of the road or where camels rest.",
        "Prayer is not allowed on stolen land, or on material burned by fire such as gypsum, lime or ash.",
        "Nor on top of the Kaaba, because one praying there does not face the qiblah.",
    ]),
    "th-13": ("Clothing for prayer", "Clean clothing that covers the ‘awrah.", [
        "Clean clothing that covers is a condition.",
        "If one finds nothing to cover the ‘awrah, one prays sitting, using gestures.",
        "One does not pray in an impure garment if a clean one is available.",
        "One does not pray in silk unless nothing else is available.",
    ]),
    "th-14": ("Facing the qiblah", "The qiblah is the honoured Kaaba.", [
        "The qiblah is the honoured Kaaba; prayer is not complete without facing it.",
        "The worshipper should know the signs pointing to it, like sunrise and sunset, moonrise and moonset, and the directions.",
        "One may trust someone whose truthfulness about the qiblah direction reassures the heart.",
        "If confused and no one can tell, one does one’s best to find its direction and prays towards it.",
    ]),
    "jn-1": ("The funeral prayer", "A prayer without bowing or prostrating, with four takbirs.", [
        "The funeral prayer is a communal obligation, with no bowing or prostration.",
        "One says: “I pray for Allah over this deceased the Sunnah commanded by the Messenger of Allah ﷺ, with four takbirs, in obedience to Allah and His Messenger.”",
        "Say the first takbir, seek refuge and recite Al-Fatihah, then the second takbir and recite Al-Fatihah.",
        "Then the third takbir: praise Allah, send blessings on His Messenger ﷺ, ask forgiveness for one’s sins and the believers, and supplicate.",
        "Then the fourth takbir, then a light salam.",
    ]),
    "jn-2": ("The supplication in the funeral prayer", "We pray for mercy for the deceased.", [
        "If the deceased is known to be righteous: “O Allah, so-and-so is Your servant, son of Your servant, son of Your maidservant; You took him and kept us after him. O Allah, give him a home better than his home and a family better than his family…”",
        "One who cannot tell says: “Praise be to Allah who causes the living to die, gives life to the dead and raises those in the graves… Our Lord, You encompass all things in mercy and knowledge, so forgive those who repent and follow Your way, and protect them from the punishment of Hellfire.”",
        "Then send blessings on the Prophet ﷺ, his family and companions, then say takbir and salam.",
    ]),
    "jn-3": ("How the deceased is washed", "The deceased is washed gently, starting with the right.", [
        "Wudu is done for the deceased as for prayer; it is Sunnah in washing the deceased according to the correct view.",
        "Then the deceased is washed with water and lote leaves or similar if available; if not, there is no harm.",
        "Begin with the right side of the head, then the left, then the neck, the arms, the right side then the left, then the legs.",
        "Then cover the whole body with water, washing as gently as possible.",
    ]),
    "jn-4": ("Tayammum for the deceased", "If washing is impossible, tayammum is done with clean earth.", [
        "If there is no water, or the body cannot be washed, tayammum is done with clean earth instead.",
        "Put the hands on the earth and wipe the face of the deceased, then again and wipe the hands.",
        "Intend in the heart to fulfil the duty, and say Allah’s name over the act.",
    ]),
    "jn-5": ("Sunnah of washing the deceased", "We cover the deceased and protect their dignity.", [
        "A cloth must cover the deceased while being washed, held over them by someone other than the washer.",
        "It is not allowed to look at any of their ‘awrah.",
    ]),
    "jn-6": ("Shrouding and perfuming", "The deceased is shrouded in clean cloth and perfumed.", [
        "The deceased is shrouded in one or more garments in which prayer is valid.",
        "The body is dried of water and wrapped in the shrouds.",
        "Perfume is applied, such as camphor and saffron.",
        "Then the deceased is placed on the bier, covered, perfumed and scented with incense.",
    ]),
    "jn-7": ("Carrying the deceased", "We walk gently with the funeral.", [
        "When placed on the bier, they walk with it gently.",
        "They carry the head forward whether going to the place of prayer or to the grave.",
    ]),
    "jn-8": ("How the deceased is buried", "Laid on the right side, facing the qiblah.", [
        "The deceased is laid in the grave on the right side, facing the qiblah.",
        "Then bricks are placed over the niche and the grave is filled with earth.",
        "Following the funeral is commanded and has great reward.",
        "One should remember Allah much behind it; it is recommended to say: “There is no god but Allah, the Living who never dies.”",
    ]),
    "sw-1": ("Fasting and how to do it", "We abstain from dawn until sunset.", [
        "Fasting is purely bodily worship; what is obligatory is fasting the blessed month of Ramadan every year.",
        "It is to abstain from eating and drinking from dawn until sunset.",
        "And to keep away from indecent speech, backbiting and tale-bearing, and avoid all sins, for sins spoil the fast.",
        "About eating or drinking forgetfully there are two views: it is said the fast is spoiled and must be made up, and it is said nothing is due because forgetting is forgiven.",
    ]),
    "sw-2": ("The condition for a valid fast", "Making the intention at night.", [
        "To intend at night to fast the obligation of Ramadan the next day, in obedience to Allah and His Messenger Muhammad ﷺ.",
        "Whoever does not intend the fast at night has no fast.",
        "One should not start the day in major impurity; one in that state should bathe before dawn.",
        "Whoever has a wet dream during the day should bathe promptly, and nothing is due from them.",
    ]),
    "sw-3": ("Night prayer in Ramadan", "We pray at night in Ramadan as much as Allah wills.", [
        "One is encouraged to pray at night in Ramadan, between Isha and Fajr, as much as Allah wills.",
        "It is good to pray twenty rak‘ahs every night; twelve rak‘ahs are sufficient.",
        "The Witr prayer is also necessary in the nights of Ramadan.",
    ]),
    "sw-4": ("Forbidden and disliked fasting", "We do not fast on the day of Eid.", [
        "Fasting on the two Eids is forbidden.",
        "Fasting the days of Tashriq is disliked.",
        "Fasting the day of doubt is disliked; it is also said to be forbidden.",
    ]),
    "sw-5": ("Recommended fasting", "The white days, Ashura and six days of Shawwal.", [
        "It is recommended to fast the white days: the 13th, 14th and 15th of every month.",
        "And the first nine days of Dhul-Hijjah before Eid, Ashura in Muharram, and six days of Shawwal.",
        "And one day of Dhul-Qa‘dah (the 25th), one day of Rajab (the 27th) and one day of Sha‘ban (the 15th).",
    ]),
    "hq-1": ("Rights of parents", "Pleasing one’s parents is a door to Paradise.", [
        "The greatest tie of kinship is the right of parents, as he ﷺ said: “Whoever begins the day with their parents pleased with them has a door to Paradise opened for them.”",
        "Do not shout at them, hurt them with words or speak harshly to them; be humble and gentle with them.",
        "Do not walk in front of them unless to remove harm from their way, and do not call them by name — say “O my father”.",
        "Whatever acts of obedience or permissible things they command, one must obey if able.",
        "Do not disobey them unless they command disobedience to Allah, for “there is no obedience to a creature in disobedience to the Creator.”",
    ]),
    "hq-2": ("Rights of children", "A child has the right to good upbringing and teaching.", [
        "Parents owe their child rights just as the child owes them.",
        "To raise and discipline them well, and teach them the Qur’an, arithmetic, prayer, the obligations and all they need.",
        "To spend on them and clothe them until they grow up and can earn a living.",
        "To choose the best names for them: names of prophets and of the righteous.",
    ]),
    "hq-3": ("Rights of relatives", "Keeping ties with relatives is obligatory; the best way is with gifts.", [
        "Relatives are those who share a common ancestor with you, and keeping ties with them is obligatory.",
        "Keeping ties is on whoever is able, with wealth and self.",
        "Whoever is unable to reach them because of work is excused as long as they intend to reach them.",
        "The best tie is giving gifts, and the least is sending greetings.",
    ]),
    "hq-4": ("Rights of neighbours", "We do not harm our neighbour, and we share their joys and sorrows.", [
        "Keeping good relations with neighbours is a firm right, whether near or far.",
        "He ﷺ said: “Jibril kept advising me about the neighbour until I thought he would make him an heir.”",
        "The neighbour’s right includes keeping harm away from them; it is not allowed to harm one’s neighbour.",
        "Visit them at their time of joy and at their time of calamity.",
        "Share with them things they do not have when you know of it.",
    ]),
    "hq-5": ("Rights of a travel companion", "A travel companion has the right to kindness and help.", [
        "The “companion at your side” is the travel companion, and they have a right.",
        "Accompany them kindly and with good conduct, keep harm away, and share food and drink without keeping anything to yourself.",
        "Do not whisper with others to exclude them in their presence.",
        "If they fall ill, look after them; if they have a need, wait for them until they finish.",
    ]),
    "hq-6": ("Rights of a companion in seeking knowledge", "We help and advise each other in seeking knowledge.", [
        "To advise them in matters of this world and the Hereafter.",
        "To explain what they do not understand of manners and knowledge.",
        "If you see them slip, stop them and cover it for them; remind them when they forget and encourage them to work hard.",
        "Do not do what hurts their heart, like whispering without them.",
    ]),
    "hq-7": ("Rights of the guest", "Whoever believes in Allah and the Last Day, let them honour their guest.", [
        "Honouring the guest is a firm right, as he ﷺ said: “Whoever believes in Allah and the Last Day, let them honour their guest.”",
        "Hospitality is three days; beyond that is charity, and a guest should not stay until the host tires of them.",
        "The family should offer the best of what is in their home, serve food quickly and keep the prayer times for the guest.",
        "Do not serve food without water.",
    ]),
    "hq-8": ("What is disliked towards guests", "We do not leave the guest feeling lonely.", [
        "Do not give to some guests and not others, or whisper with some of them and not others.",
        "Do not keep silent much with your guests, making them uneasy.",
        "Do not make the guest serve; that is not good manners.",
        "Do not get angry with anyone in front of your guests, making them uncomfortable.",
    ]),
    "zk-1": ("Zakah", "A due from wealth given to specific groups.", [
        "Zakah is purely financial worship.",
        "Allah made obligatory on every Muslim a due from their wealth, given to specific groups when the wealth reaches a set amount.",
    ]),
    "zk-2": ("What zakah is due on", "Gold, silver, grain, livestock and trade.", [
        "Zakah is due on gold and silver.",
        "Dates, raisins and staple grains such as wheat, barley and sorghum.",
        "Camels, cattle, sheep and goats.",
        "And trade goods.",
    ]),
    "zk-3": ("What zakah is not due on", "No zakah on donkeys, horses or copper unless for trade.", [
        "No zakah on donkeys, horses, copper, or metals other than gold and silver.",
        "Unless they are kept for trade; then the zakah of trade is due.",
    ]),
    "zk-4": ("Zakah on gold", "The minimum is twenty dinars, and half a dinar is due.", [
        "Zakah is due on gold when it reaches twenty dinars or more and a year passes.",
        "Half a dinar is given from it.",
        "For every extra four dinars, a tenth of a dinar is given, and so on.",
        "If gold is below the minimum, it is combined with any silver one owns.",
    ]),
    "zk-5": ("Zakah on silver", "The minimum is two hundred dirhams, and five dirhams are due.", [
        "Zakah is due on silver when it reaches two hundred dirhams and a year passes.",
        "Five dirhams are given from it.",
        "For every extra forty dirhams, one dirham is given, and so on.",
        "Gold and silver are combined and given one zakah together.",
    ]),
    "zk-6": ("Zakah on grain and fruit", "A tenth or a twentieth at harvest.", [
        "It is due on dates, raisins and all grains when they reach three hundred sa‘.",
        "No year needs to pass; it is given when harvested.",
        "A tenth is due if watered by rain, rivers or springs or needing no watering.",
        "A twentieth is due if watered by drawing or carrying water.",
    ]),
    "zk-7": ("Zakah on camels", "The minimum is five camels.", [
        "Zakah is due on camels when one owns five grazing camels and a year passes.",
        "For five, one sheep; ten, two; fifteen, three; twenty, four.",
        "At twenty-five, a one-year-old she-camel; at thirty-six, a two-year-old; at forty-six, a three-year-old; at sixty-one, a four-year-old.",
        "Then for every forty a two-year-old she-camel, and for every fifty a three-year-old.",
    ]),
    "zk-8": ("Zakah on cattle", "Its ruling is like that of camels.", [
        "The zakah ruling for cattle is like that for camels; they differ only in names.",
        "The minimum and the amount given are the same.",
    ]),
    "zk-9": ("Zakah on sheep and goats", "The minimum is forty sheep.", [
        "It is due when they reach forty and a year passes.",
        "For forty up to one hundred and twenty, one sheep; one more, and two sheep up to two hundred.",
        "One more, and three sheep up to three hundred and ninety-nine.",
        "At four hundred, one sheep for every hundred.",
    ]),
    "zk-10": ("Zakah on trade", "A quarter of a tenth of the value of trade goods.", [
        "Zakah is due on trade goods when their value reaches the minimum of gold or silver and a year passes.",
        "A quarter of a tenth (2.5%) of their value is given, like the zakah of gold and silver.",
    ]),
    "zk-11": ("Zakat al-Fitr and its time", "One sa‘ of food for each person before the Eid prayer.", [
        "Zakat al-Fitr is due on well-off Muslims.",
        "It is one sa‘ of wheat, sorghum, dates or raisins for each person.",
        "One gives it for oneself, one’s child and everyone one supports; for the wife there are two views.",
        "Its time is from dawn on the day of Eid al-Fitr until going out to the prayer; it is given to the poor and needy.",
    ]),
    "zk-12": ("The eight categories", "Who is entitled to zakah?", [
        "The poor, who do not own a year’s provision; and the needy, who are in a worse state.",
        "Those who work to collect zakah, and those whose hearts are to be reconciled.",
        "Freeing those in bondage, and those in debt not due to sin or waste.",
        "In the way of Allah, and the stranded traveller cut off from their family without money.",
    ]),
    "hj-1": ("Hajj and when it is obligatory", "Once in a lifetime for whoever is able.", [
        "Hajj is worship required of the believing adult with their self and wealth.",
        "It is obligatory if one is healthy, has provision for the journey and return, and leaves enough for their family.",
        "And the road is safe, and one has transport or can walk without hardship.",
        "It is obligatory once in a lifetime; more than that is voluntary.",
    ]),
    "hj-2": ("Preparing for Hajj", "We pay debts and keep family ties before travelling.", [
        "Pay your debts, make expiation for your oaths and fulfil your vows.",
        "Keep ties with relatives and make peace with any neighbour who is upset with you.",
        "Take plenty of provision so you can be generous.",
        "Pray two rak‘ahs at home, make your intention sincere, then bid your family farewell.",
    ]),
    "hj-3": ("Setting out for Hajj", "The travel supplication when mounting.", [
        "When you mount, say takbir three times and say: “Glory be to the One who has placed this at our service, and we could not have done it, and to our Lord we will surely return.”",
        "“O Allah, You are the Companion on the journey and the Guardian of the family and wealth.”",
        "When going up a height say takbir, and when going down say subhan Allah.",
    ]),
    "hj-4": ("The miqat and the time of Hajj", "We do not pass the miqat except in ihram.", [
        "When the pilgrim reaches the miqat, they must not pass it except in ihram.",
        "The months of Hajj are Shawwal, Dhul-Qa‘dah and the first ten days of Dhul-Hijjah.",
        "Whoever enters ihram for Hajj before its months, it counts as Umrah, not Hajj.",
    ]),
    "hj-5": ("Umrah", "Ihram, then tawaf, then sa‘i.", [
        "Umrah is to enter ihram as for Hajj, then go to the House and perform tawaf and sa‘i.",
        "It may be done in any month.",
        "One must intend it as Umrah when entering ihram.",
    ]),
    "hj-6": ("How to enter ihram", "A bath, then two garments, then two rak‘ahs.", [
        "Take a bath at the start of ihram; it is said wudu is sufficient.",
        "Wear two garments, preferably new or freshly washed.",
        "Pray two rak‘ahs for ihram.",
    ]),
    "hj-7": ("The talbiyah", "Labbayka Allahumma labbayk.", [
        "After making the intention say: “Here I am, O Allah, here I am. Here I am, You have no partner, here I am. All praise, blessing and dominion are Yours; You have no partner, here I am.”",
        "It is recommended to say it whenever one travels on, climbs a height or descends into a valley.",
        "It is recommended to raise the voice with it; the more, the better.",
    ]),
    "hj-8": ("What is not allowed in ihram", "No perfume, no hunting, no cutting hair or nails.", [
        "One in ihram may not wear sewn clothes, nor cover the head or face except out of necessity.",
        "A woman covers her head, uncovers her face and may wear sewn clothes.",
        "One in ihram may not use perfume or hunt.",
        "And may not cut any hair or nails while in ihram.",
    ]),
    "hj-9": ("Entering Makkah", "We enter reciting the talbiyah.", [
        "When arriving in Makkah, enter it reciting the talbiyah, and continue until standing at the door of the mosque.",
        "On seeing the Kaaba say: “Allah is the Greatest (three times). O Allah, You are my Lord and I am Your servant; the House is Your House; I have come seeking Your pleasure.”",
        "On entering say: “O Allah, You are Peace and from You is peace; greet us, our Lord, with peace and admit us into the Abode of Peace.”",
    ]),
    "hj-10": ("Tawaf", "Seven circuits around the Kaaba.", [
        "Begin at the Black Stone, keeping the House on your left.",
        "During tawaf say often: “Glory be to Allah, praise be to Allah, there is no god but Allah, Allah is the Greatest, and there is no power or might except with Allah.”",
        "At the Yemeni corner say: “Our Lord, give us good in this world and good in the Hereafter and protect us from the punishment of the Fire,” without harming anyone.",
        "Complete seven circuits, then pray two rak‘ahs behind the Station of Ibrahim or wherever possible.",
    ]),
    "hj-11": ("Zamzam", "We drink Zamzam water and supplicate.", [
        "Go to Zamzam, drink its water and pour some on your head.",
        "Say: “O Allah, I ask You for complete faith, firm certainty, upright religion, righteous deeds, knowledge, wide lawful provision and healing from every illness.”",
    ]),
    "hj-12": ("Sa‘i between Safa and Marwah", "Seven laps, starting at Safa and ending at Marwah.", [
        "Climb Safa until you face the House, then say takbir, tahlil and supplicate.",
        "Go down towards Marwah, hurrying between the two markers and saying: “My Lord, forgive and have mercy, and overlook what You know.”",
        "At Marwah climb until you face the House and supplicate as on Safa.",
        "Complete seven laps, starting at Safa and ending at Marwah.",
    ]),
    "hj-13": ("Leaving the state of Umrah", "Shaving after the sa‘i.", [
        "After finishing the sa‘i, come down from Marwah and shave the head; you have left the state of Umrah.",
        "Everything becomes allowed except hunting in the Haram, which is forbidden for all.",
        "This is for one doing tamattu‘; one doing qiran does not leave ihram until Hajj is complete.",
    ]),
    "hj-14": ("Ihram for Hajj and going to Mina", "The day of Tarwiyah: the 8th of Dhul-Hijjah.", [
        "Enter ihram for Hajj on the evening of Tarwiyah, the 8th of Dhul-Hijjah.",
        "Say the talbiyah: “Here I am for Hajj; its completion and fulfilment are upon You, O Allah.”",
        "Then go to Mina, pray five prayers there, spend the night with the people and remember Allah much.",
    ]),
    "hj-15": ("Arafat", "Standing at Arafah is a pillar of Hajj.", [
        "Go to Arafat after sunrise reciting the talbiyah.",
        "Pray Dhuhr with the people and supplicate earnestly until sunset.",
        "Say often: “There is no god but Allah alone, without partner; His is the dominion and His is the praise; He gives life and death, and He is Living and never dies; in His hand is all good, and He is capable of all things.”",
    ]),
    "hj-16": ("Leaving Arafat and al-Mash‘ar al-Haram", "The night at Muzdalifah and collecting pebbles.", [
        "Then move on from Arafat to al-Mash‘ar al-Haram (Jam‘).",
        "Pray Maghrib and Isha together and spend the night with the people.",
        "Prepare seventy small pebbles from there and wash them.",
        "At dawn pray, stand at al-Mash‘ar al-Haram supplicating, then move on before sunrise.",
    ]),
    "hj-17": ("Stoning the pillars", "Seven pebbles, with a takbir for each.", [
        "On reaching Jamrat al-‘Aqabah, stop the talbiyah.",
        "Throw seven pebbles at it, saying takbir with each and “and to Allah belongs praise” after each takbir.",
        "On the days of Tashriq, stone the three pillars after noon: the first, then the middle, then Jamrat al-‘Aqabah.",
    ]),
    "hj-18": ("Sacrifice, shaving and the pillars of Hajj", "The pillars of Hajj: ihram, standing at Arafah and visiting the House.", [
        "Then sacrifice and shave, saying: “O Allah, bless me in removing my hair and forgive my sins.”",
        "After shaving everything becomes allowed except women and hunting until the House is visited.",
        "The agreed pillars of Hajj are: ihram, standing at Arafah and visiting the House.",
    ]),
    "hj-19": ("Visiting the House", "Tawaf and sa‘i as in Umrah.", [
        "During the visit do as you did in Umrah: tawaf, sa‘i and supplication.",
        "Then return to Mina without spending the night in Makkah, and stay there for the days of Tashriq.",
    ]),
    "hj-20": ("The farewell tawaf", "The last time with the House.", [
        "When leaving Makkah go to the House, perform seven circuits, then pray two rak‘ahs.",
        "Then go to Zamzam and drink, then supplicate with whatever Allah opens for you.",
        "Among the supplications: “O Allah, do not make this my last time at Your Sacred House.”",
        "Then leave, and do not buy or sell after the farewell.",
    ]),
    "jh-1": ("The meaning and virtue of jihad", "Striving with self and wealth in the way of Allah.", [
        "Jihad is worship prescribed with one’s self and wealth.",
        "Allah said: “The believers are only those who believe in Allah and His Messenger, then do not doubt, and strive with their wealth and their lives in the way of Allah. Those are the truthful.” [Al-Hujurat: 15]",
        "Allah praised the righteous of earlier nations for their steadfastness, patience and striving.",
    ]),
    "jh-2": ("Kinds of jihad", "It includes striving against one’s self and desires.", [
        "An individual duty: such as repelling an enemy attacking the land and the community.",
        "A communal duty: such as guarding the borders and protecting the call of Islam.",
        "Jihad also means striving with oneself to learn and practise the religion and spread knowledge, and striving against Satan and desires. (From Abu Ishaq’s commentary)",
    ]),
    "jh-3": ("The wisdom of jihad", "Repelling injustice and protecting the call of truth.", [
        "Jihad was prescribed to make Islam prevail and protect it, suppress aggression and remove falsehood.",
        "It was prescribed to repel injustice and corruption on earth and to protect the call of truth; it does not contradict the mercy Islam brought or the justice Allah commanded.",
        "Rebels are people of tawhid who unjustly left obedience to the imam; the imam fights them after the proof is established until they return to obedience, and their wealth is not taken as spoils.",
    ]),
    "kh-1": ("Disbelief in Allah (shirk)", "The greatest thing to be avoided.", [
        "The first thing to be avoided is disbelief in Allah, which is associating partners with Allah.",
        "Such as denying any of Allah’s books or any of His prophets.",
        "Or doubting Allah’s existence, or being ignorant of Allah and of His Messenger Muhammad ﷺ.",
        "Or denying death, resurrection, the reckoning, Paradise or the Fire, or denying a clearly stated ruling of Allah.",
    ]),
    "kh-2": ("Ingratitude for blessings", "Committing major sins.", [
        "Ingratitude for blessings (kufr al-ni‘mah) is committing any of the major sins, outward or inward.",
        "The inward sins are: vanity, arrogance, envy, showing off, and the bad traits that come from them.",
    ]),
    "kh-3": ("Vanity and its cure", "Every blessing is from Allah’s grace.", [
        "Vanity is to think highly of the blessing one has while forgetting the One who gave it, seeing oneself as deserving it.",
        "Its cause: some perfection in looks, qualities or wealth, such as beauty, knowledge, courage or generosity.",
        "Its cure: to know that Allah alone bestowed what one has, and one’s self has no share in it.",
    ]),
    "kh-4": ("Arrogance and its cure", "We look down on no one, and we accept the truth.", [
        "Arrogance is to look down on people and reject the truth.",
        "Its cause: seeing oneself as great and special.",
        "Its cure: to look at the origin one was created from and the end one will return to.",
    ]),
    "kh-5": ("Showing off and its cure", "We act for Allah alone.", [
        "Showing off is acting for the sake of people; whoever intends anything other than Allah is showing off.",
        "One must leave people aside and seek only one’s Lord’s pleasure.",
        "Its cure: to know that people have no power to benefit or harm; the One who does all that is Allah, the One, the Unique.",
    ]),
    "kh-6": ("Envy and admiration", "We wish the same good for ourselves without wishing it away from others.", [
        "Envy is wishing that Allah’s blessing be taken away from someone else; it is a major sin.",
        "One must abandon it and know that it is Allah’s grace, which He gives to whom He wills.",
        "Its cure: to know that envy does not remove the other’s blessing, but only brings harm to oneself in this world and the next.",
        "It is allowed to wish for a blessing like someone else’s; this is called “ghibtah” (admiration).",
    ]),
    "kh-7": ("Outward major sins", "We stay away from all that Allah has forbidden.", [
        "Among the outward major sins: usury, eating carrion, blood and pork, and killing a soul that is sacred.",
        "Highway robbery, wronging people, theft, harming and frightening Muslims, and spreading corruption on earth.",
        "Supporting falsehood, resisting the truth, and drinking wine and all intoxicants.",
        "And other acts forbidden by the text of the Qur’an, the Sunnah and the consensus of the Ummah.",
    ]),
}

QUIZ = {
    "intro": [
        ("When does the guardian teach the child to pray?", ["At three years old", "At seven years old", "At fifteen years old"], "The guardian is commanded to teach the child to pray at seven years old."),
        ("What else does the guardian teach the child?", ["The Glorious Qur’an and good literature", "Nothing before maturity", "Only fasting"], "He teaches the Qur’an, literature and the wisdom the child can understand."),
    ],
    "aqeedah": [
        ("How many messengers are there according to the book?", ["One hundred and four", "Three hundred and thirteen", "Twenty-five"], "The messengers sent by Allah number three hundred and thirteen."),
        ("Who is the first messenger?", ["Nuh, peace be upon him", "Ibrahim, peace be upon him", "Adam, peace be upon him"], "The first is Adam, peace be upon him, a messenger to his children."),
        ("To whom was the Zabur revealed?", ["Dawud, peace be upon him", "Musa, peace be upon him", "‘Isa, peace be upon him"], "The Zabur to Dawud, the Torah to Musa and the Injil to ‘Isa."),
        ("What is the greatest blessing Allah gave us?", ["Health", "The blessing of Islam", "Wealth"], "Among Allah’s blessings: existence, health, and the greatest, Islam."),
    ],
    "salah": [
        ("How many rak‘ahs are in the Maghrib prayer?", ["Two", "Three", "Four"], "Maghrib has three obligatory rak‘ahs."),
        ("What do we say in rukū‘ (bowing)?", ["Glory be to my Lord, the Most High", "Glory be to my Lord, the Most Great", "Our Lord, and to You belongs all praise"], "In bowing one says “Glory be to my Lord, the Most Great” three times."),
        ("On how many parts of the body is sujūd done?", ["Five", "Seven", "Three"], "Prostration is on seven parts: the forehead, hands, knees and feet."),
        ("What does a traveller do with Dhuhr?", ["Prays it as four", "Shortens it to two", "Leaves it"], "The traveller shortens Dhuhr, Asr and Isha to two rak‘ahs each."),
        ("How many takbirs are in the Eid prayer besides the prayer’s own takbirs?", ["Seven", "Thirteen", "Four"], "Thirteen takbirs besides the takbirs of the prayer."),
    ],
    "taharah": [
        ("How many times do we wash the face in wudu?", ["Once", "Three times", "Five times"], "The face is washed three times."),
        ("With which foot do we enter the toilet?", ["The right", "The left", "It doesn’t matter"], "Enter with the left foot and leave with the right."),
        ("If we find no water, what do we do?", ["Skip the prayer", "Do tayammum with clean earth", "Delay the prayer to tomorrow"], "If there is no water, one does tayammum with clean earth."),
        ("What is the qiblah we face in prayer?", ["Al-Aqsa Mosque", "The honoured Kaaba", "Any direction"], "The qiblah is the honoured Kaaba; prayer is not complete without facing it."),
    ],
    "janaiz": [
        ("How many takbirs are in the funeral prayer?", ["Three", "Four", "Five"], "The funeral prayer has four takbirs."),
        ("On which side is the deceased laid in the grave?", ["The right, facing the qiblah", "The left", "On the back"], "The deceased is laid on the right side facing the qiblah."),
    ],
    "sawm": [
        ("When is the intention for Ramadan fasting made?", ["At night", "After noon", "No intention is needed"], "One intends at night; whoever does not has no fast."),
        ("What is the ruling on fasting on the day of Eid?", ["Recommended", "Forbidden", "Obligatory"], "Fasting on the two Eids is forbidden."),
        ("What are the white days?", ["The 1st, 2nd and 3rd", "The 13th, 14th and 15th", "The last three days"], "The white days are the 13th, 14th and 15th of the month."),
    ],
    "huquq": [
        ("How do we call our father?", ["By his name", "We say: O my father", "We don’t call him"], "Calling one’s father by name is disrespectful; one says “O my father”."),
        ("How many days is hospitality?", ["One day", "Three days", "A week"], "Hospitality is three days; beyond that is charity."),
        ("What is the best way to keep ties with relatives?", ["Giving gifts", "Sending greetings", "Nothing"], "The best tie is giving gifts, and the least is sending greetings."),
    ],
    "zakah": [
        ("What is the minimum amount (nisab) of silver?", ["One hundred dirhams", "Two hundred dirhams", "Forty dirhams"], "Zakah is due on silver when it reaches two hundred dirhams."),
        ("When is Zakat al-Fitr given?", ["Before Ramadan", "On Eid day before going to the prayer", "A month after Eid"], "Its time is from dawn on Eid day until going out to the prayer."),
        ("How many categories are entitled to zakah?", ["Four", "Eight", "Ten"], "The categories entitled to zakah are eight."),
    ],
    "hajj": [
        ("How many times in a lifetime is Hajj obligatory?", ["Every year", "Once", "Twice"], "Hajj is obligatory once in a lifetime; more is voluntary."),
        ("How many circuits are in tawaf?", ["Five", "Seven", "Three"], "Tawaf is seven circuits."),
        ("Where does the sa‘i begin?", ["At Marwah", "At Safa", "At Zamzam"], "It begins at Safa and ends at Marwah."),
    ],
    "jihad": [
        ("With what was jihad prescribed?", ["With one’s self and wealth", "With wealth only", "With words only"], "Jihad is worship prescribed with one’s self and wealth."),
    ],
    "khatimah": [
        ("What is arrogance?", ["Looking down on people and rejecting the truth", "Loving good for people", "Acting for Allah"], "Arrogance is to look down on people and reject the truth."),
        ("What is the difference between envy and admiration (ghibtah)?", ["No difference", "Admiration is wishing for the same blessing without it leaving the other", "Admiration is forbidden and envy allowed"], "Wishing for a blessing like another’s is allowed and is called ghibtah."),
        ("What is the cure for showing off?", ["Knowing that people cannot bring benefit or harm", "Doing more in front of people", "Stopping good deeds"], "Its cure is knowing that people cannot benefit or harm; that is Allah alone."),
    ],
}
