# -*- coding: utf-8 -*-
# Turkish (Türkçe) translation overlay
BOOK = {
    "title": "Telkînü’s-Sıbyân — Her İnsanın Bilmesi Gerekenler",
    "author": "Nûreddin Abdullah b. Humeyd es-Sâlimî",
    "about": "İnsanın mükellef olduğu ilk anda üzerine düşen ilk görevler ve kendisine emredilen bazı şeyler hakkında kısa ve kolay bir risale. Yazar onu bir giriş, iki bölüm ve bir sonuç olarak düzenlemiştir; “zeki olanın da zayıf olanın da anlayabileceği açık bir ifadeyle.”",
    "structure": [
        "Giriş: Çocuğun velisinin, çocuğu ergenliğe kadar gözetip yetiştirmesi hakkında emrolunduğu şeyler.",
        "Birinci bölüm: İnsanın kalbiyle inanması gereken ilk şeyler.",
        "İkinci bölüm: İnsanın organlarıyla yapması gereken ilk ameller.",
        "Sonuç: İnsanın sakınması gereken bedenî işler ve nefsânî huylar.",
    ],
}

CHAPTERS = {
    "intro": ("Giriş", "Çocuğa Özen", "Velinin, çocuk büyüyene kadar yaptıkları"),
    "aqeedah": ("Birinci Bölüm", "İnanç (Akîde)", "İnsanın kalbiyle inanması gerekenler"),
    "salah": ("İkinci Bölüm", "Namaz", "İnancı öğrendikten sonraki ilk görev"),
    "taharah": ("İkinci Bölüm", "Temizlik ve Namazın Şartları", "Abdest, gusül, teyemmüm ve namazın sekiz şartı"),
    "janaiz": ("İkinci Bölüm", "Cenazeler", "Cenaze namazı ve vefat eden Müslümanın hakkı"),
    "sawm": ("İkinci Bölüm", "Oruç", "Mübarek Ramazan ayının orucu"),
    "huquq": ("İkinci Bölüm", "Haklar", "Anne baba, akrabalar, komşu, arkadaş ve misafir"),
    "zakah": ("İkinci Bölüm", "Zekât", "Tamamen malî bir ibadet"),
    "hajj": ("İkinci Bölüm", "Hac ve Umre", "Allah’ın Beyt-i Harâm’ına bir yolculuk"),
    "jihad": ("İkinci Bölüm", "Cihad", "Can ve malla yapılan bir ibadet"),
    "khatimah": ("Sonuç", "Terk Edilmesi Gerekenler", "Sakınılması gereken bedenî işler ve iç huylar"),
}

LESSONS = {
    "wudu": ("Abdest", "Abdesti adım adım öğren", "Telkînü’s-Sıbyân, s. 61–64"),
    "ghusl": ("Gusül (Boy Abdesti)", "Gusül nasıl alınır", "Telkînü’s-Sıbyân, s. 65–66"),
    "tayammum": ("Teyemmüm", "Su bulamadığımızda", "Telkînü’s-Sıbyân, s. 64–65"),
    "salah": ("Namaz", "Öğle namazı adım adım", "Telkînü’s-Sıbyân, s. 33–38"),
}

STEPS = {
    "wudu_01": ("Temiz su", "Abdesti temiz ve temizleyici su ile alırız.", "Abdest namazın şartıdır ve yalnızca temiz su ile alınır.", None),
    "wudu_02": ("Besmele", "Abdestin başında “Bismillah” deriz.", "Abdestin başında Allah’ın adı anılır; rivayet edildiğine göre: “Üzerine Allah’ın adını anmayanın abdesti yoktur.”", None),
    "wudu_03": ("Misvak", "Abdestten önce misvak kullanmak sünnettir.", "Abdestten önce dişleri misvakla temizlemek sünnettir.", None),
    "wudu_04": ("Elleri yıkamak", "Uykudan kalkınca ellerimizi kaba sokmadan önce üç kez yıkarız.", None, None),
    "wudu_05": ("Ağza su vermek", "Ağzımıza üç kez su verip iyice çalkalarız.", "Sağ elin parmağını ağza sokar, suyu boğazın hemen önüne kadar ulaştırır; oruçlu olan fazla gargara yapmaz.", "Allah’ım, bana cennetin mühürlü saf içeceğinden içir."),
    "wudu_06": ("Burna su vermek", "Sağ elimizle burnumuza su çeker, sonra dışarı atarız.", None, "Allah’ım, beni cennetinin kokularından mahrum etme, rahmetinle ey merhametlilerin en merhametlisi."),
    "wudu_07": ("Yüzü yıkamak", "Yüzümüzü üç kez yıkarız.", None, "Allah’ım, salih kullarının yüzlerinin ağaracağı gün yüzümü nurunla ağart, ey merhametlilerin en merhametlisi."),
    "wudu_08": ("Sağ kol", "Sağ kolu dirsekle birlikte üç kez yıkarız.", None, "Allah’ım, kitabımı sağ elimden ver ve hesabımı kolay eyle."),
    "wudu_09": ("Sol kol", "Sonra sol kolu dirsekle birlikte üç kez yıkarız.", None, "Allah’ım, kitabımın sol elimden veya arkamdan verilmesinden sana sığınırım."),
    "wudu_10": ("Başı meshetmek", "Başımızı ıslak elle meshederiz.", None, "Allah’ım, senin gölgenden başka gölgenin olmadığı gün beni arşının gölgesinde gölgelendir."),
    "wudu_11": ("Kulakları meshetmek", "Kulakları içinden ve dışından meshederiz.", "Bazı âlimler kulaklardan sonra enseyi meshetmeyi müstehap görmüştür.", "Allah’ım, beni sözü dinleyip en güzeline uyanlardan eyle."),
    "wudu_12": ("Sağ ayak", "Sağ ayağı topuklarla birlikte üç kez yıkarız.", None, "Allah’ım, ayaklarımı hak ve din üzere sabit kıl, rahmetinle ey merhametlilerin en merhametlisi."),
    "wudu_13": ("Sol ayak", "Sonra sol ayağı topuklarla birlikte üç kez yıkarız.", "Böylece abdest tamamlanır ve namaza hazırsın!", None),
    "ghusl_01": ("Elleri yıkamak", "Elleri yıkayarak başlarız.", "Cünüplükten gusül erkeğe ve kadına farzdır; aynı gusül hayızdan temizlenen kadına da farzdır.", None),
    "ghusl_02": ("Pisliği gidermek", "Pisliği bulunduğu yerden gideririz.", None, None),
    "ghusl_03": ("Ağız ve burun", "Ağza ve burna su veririz; bunlar her durumda gereklidir.", None, None),
    "ghusl_04": ("Abdest organları", "Yüzü ve diğer abdest organlarını namaz abdestindeki gibi yıkarız.", "Bunu yapmazsa sakıncası yoktur; ancak ağza ve burna su vermek gereklidir.", None),
    "ghusl_05": ("Üç avuç su", "Başımıza üç avuç su dökeriz.", None, None),
    "ghusl_06": ("Baş", "Başın sağ tarafını, sonra sol tarafını yıkarız.", None, None),
    "ghusl_07": ("Boyun", "Boynun sağ tarafını, sonra sol tarafını yıkarız.", None, None),
    "ghusl_08": ("Beden", "Bedenin sağ tarafını, sonra sol tarafını yıkarız.", None, None),
    "ghusl_09": ("Bacaklar", "Sağ bacağı, sonra sol bacağı yıkarız.", None, None),
    "ghusl_10": ("Bütün beden", "Suyla birlikte elimizi bedenimizde gezdiririz, su her yere ulaşsın.", "Sıra gözetmeden bütün bedene su ulaştırırsa yeterlidir; ancak su, el gezdirilerek bütün bedene ulaşmalıdır.", None),
    "tayammum_01": ("Ne zaman teyemmüm?", "Su bulamadığımızda ya da bulup da abdest için kullanamadığımızda.", None, None),
    "tayammum_02": ("Temiz toprak", "Tozlu, temiz toprakla teyemmüm ederiz.", "Kül, alçı, kireç harcı, kireç, çorak tuzlu toprak, kum ve ıslak çamurla teyemmüm olmaz.", None),
    "tayammum_03": ("Besmele ve niyet", "Allah’ın adını anar, hadesi kaldırmaya ve namazı mubah kılmaya niyet ederiz.", None, None),
    "tayammum_04": ("Birinci vuruş", "Avuçlarımızı toprağa vururuz.", None, None),
    "tayammum_05": ("Yüzü meshetmek", "Avuçlarımızla yüzümüzü meshederiz.", None, None),
    "tayammum_06": ("İkinci vuruş", "Toprağa ikinci kez vururuz.", None, None),
    "tayammum_07": ("Elleri meshetmek", "İki elin üstünü ve içini bileklere kadar meshederiz.", "Böylece teyemmüm tamamlanır.", None),
    "salah_01": ("Hazırlık", "Bedenimiz ve elbisemiz temiz, abdestliyiz ve temiz bir yerdeyiz.", "Bedeni ve elbisesi temiz, bütün hadeslerden arınmış olarak namaza elverişli temiz bir yerde dimdik durur.", None),
    "salah_02": ("Kıble ve niyet", "Kâbe’ye yönelir, kalbimizle öğle namazına ihlasla, Allah için niyet ederiz.", "Kalbiyle o farz namazın kendisine niyet eder, rekât sayısını gözetir ve ibadetini Rabbine halis kılar.", None),
    "salah_03": ("Niyeti dille söylemek", "Niyeti dilimizle de pekiştiririz.", None, "Tebârek ve Teâlâ olan Allah için, şu yerimde, öğle namazının farzını, dört rekât, Kâbe-i Şerife’ye yönelerek, farzı eda etmek üzere, Allah’a ve Resulü Muhammed ﷺ’e itaat olarak kılıyorum."),
    "salah_04": ("Kamet", "Sonra kamet getirilir; bu kadınlar için değil erkekler içindir.", None, None),
    "salah_05": ("Tevcih", "Peygamberimiz Muhammed ﷺ’in tevcihini okuruz.", None, "Allah’ım, seni hamdinle tesbih ederim; adın mübarek, şanın yüce, övgün büyüktür ve senden başka ilah yoktur."),
    "salah_06": ("İbrahim’in tevcihi", "Sonra atamız İbrahim aleyhisselamın tevcihini okuruz.", None, "Ben hanîf olarak yüzümü gökleri ve yeri yaratana çevirdim ve ben müşriklerden değilim."),
    "salah_07": ("Niyeti pekiştirmek", "Niyeti bir kez daha pekiştiririz.", None, "Allah Teâlâ için öğle namazının farzını dört rekât kılıyorum ve Kâbe kıblemdir."),
    "salah_08": ("İftitah tekbiri", "İftitah tekbirini alır, sonra kısa bir süre susarız.", None, "Allah en büyüktür."),
    "salah_09": ("İstiâze", "Kalp huzuruyla gizlice Allah’a sığınırız.", None, "Kovulmuş şeytandan Allah’a sığınırım."),
    "salah_10": ("Fâtiha", "Besmele çekip Fâtiha suresini sonuna kadar okur, sonra kısa bir süre susarız.", "Öğle namazında yalnızca Fâtiha gizlice okunur.", None),
    "salah_11": ("Rükû", "Tekbirle rükûa gideriz: avuçlar dizlerde, sırt dümdüz.", "Kollarını dik tutar, sırtı düzleşene kadar eğilir; başını ne kaldırır ne de sarkıtır.", "Yüce Rabbimi tüm noksanlıklardan tenzih ederim."),
    "salah_12": ("Rükûdan kalkış", "Başımızı kaldırıp doğruluruz.", "Kalkarken “Allah kendisine hamd edeni işitir” der; dikilince “Rabbimiz, hamd sanadır” der.", "Allah kendisine hamd edeni işitir… Rabbimiz, hamd sanadır."),
    "salah_13": ("Secde", "Tekbirle secdeye gideriz: önce dizler, sonra eller, sonra burun ve alın.", "Yedi uzuv üzerine secde eder: alın, iki el, iki diz ve iki ayak; kollarını yanlarından uzak tutar.", "En yüce Rabbimi tüm noksanlıklardan tenzih ederim."),
    "salah_14": ("İki secde arası oturuş", "Tekbirle başımızı kaldırır, her eklem yerine oturana kadar otururuz.", None, None),
    "salah_15": ("İkinci secde", "Birincisi gibi bir secde daha yaparız.", None, "En yüce Rabbimi tüm noksanlıklardan tenzih ederim."),
    "salah_16": ("İkinci rekât", "Tekbirle kalkarız: alın, sonra eller, sonra dizler; Fâtiha okur, sonra rükû ve secde ederiz.", None, None),
    "salah_17": ("İlk teşehhüd", "İkinci secdeden sonra oturup tahiyyatı okuruz.", None, "Mübarek selamlar Allah’a aittir, dualar ve güzel şeyler de; Peygamber’e selam, Allah’ın rahmeti ve bereketleri olsun; bize ve Allah’ın salih kullarına selam olsun. Şahitlik ederim ki Allah’tan başka ilah yoktur, O tektir, ortağı yoktur; ve şahitlik ederim ki Muhammed O’nun kulu ve Resulüdür."),
    "salah_18": ("Üçüncü rekât", "Tekbirle kalkar, yalnızca Fâtiha okur, sonra rükû ve secde ederiz.", None, None),
    "salah_19": ("Dördüncü rekât", "Tekbirle kalkar, yalnızca Fâtiha okur, sonra rükû ve secde ederiz.", None, None),
    "salah_20": ("Son teşehhüd", "Oturur ve tahiyyatı önceki gibi okuruz.", "“Kulu ve Resulüdür”den sonra şunu ekleyebilir: “ﷺ, onu hidayetle ve hak dinle, müşrikler hoşlanmasa da onu bütün dinlere üstün kılmak için gönderdi. Rabbimiz, bize dünyada da iyilik ver, ahirette de iyilik ver ve bizi ateş azabından koru.”", None),
    "salah_21": ("Selam", "Sonra selam veririz ve namaz tamamlanır. Aferin!", None, None),
}

MASAIL = {
    "intro-1": ("Çocuğun velisinin görevi", "Veli çocuğu korur ve onun için en iyisini seçer.", [
        "Çocuğa bakmak, onu yetiştirmek ve bedenine, ahlakına veya malına zarar verecek şeylerden korumak.",
        "Her işinde onun için en iyisini gözetmek; onu uygun olmayan şeylerden alıkoymak ve hoş olmayan işlerden men etmek.",
        "Terbiye, yalnızca çocuğu düzeltecek ölçüdedir; dövülmeden itaat ederse dövülmesi yasaktır.",
        "Ona, gücü yettiği İslam hasletlerini emretmek: pisliklerden kaçınmak, onlardan temizlenmek ve kirlerden temiz kalmak.",
    ]),
    "intro-2": ("Çocuğa ergenlikten önce İslam’ı öğretmek", "Yedi yaşında namazı öğrenir, gücümüz yetince oruç tutarız.", [
        "Veli, çocuğa yedi yaşında namazı ve onun şartlarını, görevlerini öğretir.",
        "On yaşına kadar namazı bırakması sebebiyle onu dövmez; rivayet edildiğine göre: “Onlara yedi yaşında namazı emredin, on yaşında onun için terbiye edin.”",
        "Gücü yetiyorsa Ramazan orucunu emreder ki İslam’ın şiarlarını terk etmeye alışmasın.",
        "Ona Kur’an-ı Kerim’i, Arap şiiri ve siyerinden edebi ve aklının alacağı hikmetleri öğretir.",
        "Çocuğun malını korur ve olgunluğa erişene kadar onun için en iyisini yapar.",
    ]),
    "aq-1": ("Çocuğun mükellef olmaması", "Ergenliğe kadar çocuğa hiçbir şey farz değildir.", [
        "Çocuk olduğu sürece ona ne bir inanç ne de bir amel farzdır.",
        "Bazı şeyler ona farz olduğu için değil, terbiye amacıyla emredilir.",
    ]),
    "aq-2": ("Ergenlik belirtileri", "Ergenlik belirtilerinden biri görülünce insan mükellef olur.", [
        "Ergenlik belirtilerinden: ihtilam olmak veya alışılmış yerlerde kıl bitmesi.",
        "Ya da en doğru görüşe göre on beş yaşına ulaşmak; on yedi yaş da denmiştir.",
        "Kız için ayrıca: hayız, gebelik veya göğüslerin belirginleşmesi.",
        "Bu belirtilerden biri görülünce ona ergenin hükümleri uygulanır; ibadetlerle ve haramları terk etmekle yükümlü olur.",
    ]),
    "aq-3": ("Ergenlikten sonraki ilk görev", "İlk görev: Allah’ın seni ve her şeyi yaratan olduğunu bilmek.", [
        "Onu yapan bir yapıcının ve yaratan bir yaratıcının olduğunu, onu yokluktan varlığa çıkardığını bilmek.",
        "Bu yaratıcının her şeyi var eden ve her varlığı yaratan olduğunu bilmek.",
        "Bütün yaratılmışların O’na muhtaç olduğunu, O’nun ise onlardan müstağni olduğunu bilmek.",
        "O’nun kemal sıfatlarıyla nitelendiğini; özünde, hallerinde ve fiillerinde her şeyden farklı olduğunu bilmek.",
        "Onu ve her şeyi yaratanın adının “Allah” olduğunu bilmek.",
    ]),
    "aq-4": ("Allah hakkında imkânsız olanlar", "Allah her türlü eksiklikten münezzehtir.", [
        "Allah hiçbir eksiklik sıfatıyla nitelenemez.",
        "Cehalet, acizlik, körlük, sağırlık, mekânlara yerleşmek ve zaman içinde sonradan olmak O’nun hakkında imkânsızdır.",
        "Şeylerin O’na yerleşmesi imkânsız olduğu gibi O’nun da onlara yerleşmesi imkânsızdır.",
        "O’nun gözle görülmesi, zatının göz, kalp veya diğer duyularla kavranması imkânsızdır; bunların hepsi eksikliktir ve Rabbimiz bundan çok yücedir.",
    ]),
    "aq-5": ("Allah’ın nitelenmesi gerekenler", "Allah ezelî, diri, bilen, güçlü, işiten, gören ve bakidir.", [
        "Kemal ile nitelenmesi gerekir: ezelî, diri, bilen, güç yetiren, dileyen, işiten, gören ve yok olmayan baki.",
        "O, zatıyla bilen, zatıyla güç yetiren, zatıyla dileyen, zatıyla gören ve zatıyla diridir.",
        "Yani zatı bu kemal sıfatlarıyla nitelenmiştir; başkasına muhtaç olmaması için ilave sıfatlara ihtiyacı yoktur.",
        "O münezzehtir: kendi kendine yeterli ve zatında kâmildir.",
    ]),
    "aq-6": ("Allah hakkında caiz olanlar", "Allah’ın lütfuyla peygamberler gönderildi ve kitaplar indirildi.", [
        "Peygamber göndermek, kitap indirmek, yaratmak, öldürmek, diriltmek, toplamak, hesaba çekmek, ödüllendirmek ve cezalandırmak O’nun hakkında caizdir.",
        "Allah peygamberler gönderip kitaplar indirerek bize lütufta bulundu ve hüccet ulaştıktan sonra lütfuyla bizi mükellef kıldı.",
    ]),
    "aq-7": ("Nebiler, resuller ve kitaplar", "İlk resul Âdem, son resul Muhammed ﷺ’dir.", [
        "Resullerin sayısı üç yüz on üçtür.",
        "İlki Âdem aleyhisselamdır; çocuklarına gönderilmiş bir resuldür.",
        "Sonuncusu Muhammed ﷺ’dir; Araplara ve Arap olmayanlara, insanlara ve cinlere, herkese gönderilmiştir.",
        "Nebilerin sayısı yüz yirmi dört bindir; üç yüz on üç resul de onlardandır.",
        "Kitapların sayısı yüz dörttür: elli Şît’e, otuz İdris’e, on İbrahim’e (sahifeleri) ve on da Tevrat’tan önce Musa’ya.",
        "Sonra Tevrat Musa’ya, İncil İsa’ya, Zebur Davud’a ve Kur’an Muhammed’e indirilmiştir; Allah’ın salat ve selamı hepsinin üzerine olsun.",
    ]),
    "aq-8": ("Peygamberlere ve kitaplara iman", "Bütün resullere ve kitaplara, özellikle de Muhammed ﷺ’e ve Kur’an’a iman ederiz.", [
        "Bütün resullere ve bütün kitaplara toptan iman etmek farzdır.",
        "Muhammed ﷺ ve Kur’an-ı Kerim dışında toptan iman yeterlidir.",
        "Her mükellefin Muhammed ﷺ’e ve ona indirilene özel olarak iman etmesi farzdır.",
        "Hücceti kendisine ulaşan her resule ve kitaba da özel olarak iman etmesi farzdır.",
    ]),
    "aq-9": ("Resullerin sıfatları", "Resullerin vacip, imkânsız ve caiz sıfatları vardır.", [
        "Hüccet ulaştıktan sonra mükellef, resullerin kendileri için vacip olan sıfatları olduğunu bilmelidir.",
        "Ve kendileri için imkânsız olan sıfatları.",
        "Ve diğer insanlar gibi kendileri için caiz olan sıfatları.",
    ]),
    "aq-10": ("Resuller için vacip sıfatlar", "Doğruluk, emanet, tebliğ ve zekâ.", [
        "Haber verdiklerinde doğruluk.",
        "Emanet (güvenilirlik).",
        "Rablerinin tebliğ etmelerini emrettiğini tebliğ etmek.",
        "Korumakla emrolundukları şeyi tam olarak korumak.",
        "Konuşmalarında ve hallerinde zekâ ve uyanıklık.",
    ]),
    "aq-11": ("Resuller için imkânsız sıfatlar", "Resuller yalan söylemez ve ihanet etmez.", [
        "Yalan ve ihanet.",
        "Rablerinin emirlerini önemsememek.",
        "Konuşmada acizlik ve anlayış kıtlığı.",
        "Bunların hiçbiri onlar hakkında caiz değildir.",
    ]),
    "aq-12": ("Resuller için caiz sıfatlar", "Resuller insandır: yer, içer ve çarşılarda yürürler.", [
        "Yemek ve içmek.",
        "İnsanlarla kaynaşmak ve çarşılarda yürümek.",
        "Eş ve arkadaş edinmek, çocuk sahibi olmak ve benzerleri.",
    ]),
    "aq-13": ("Melekler", "Melekler Allah’ın emrine karşı gelmez.", [
        "Allah’ın melekleri olduğunu ve onların insanlardan ve cinlerden ayrı bir tür olduğunu bilmelidir.",
        "Allah’ın kendilerine emrettiğine karşı gelmezler ve emrolunduklarını yaparlar.",
        "Yemez ve içmezler; erkeklik veya dişilikle nitelenmezler.",
        "Onlar, Allah’ın kendisine ibadet etmeleri ve emirlerini yerine getirmeleri için yarattığı varlıklardır.",
    ]),
    "aq-14": ("Ölüm ve sonrası", "Ölüm haktır ve Allah’tan başka her şey yok olacaktır.", [
        "Ölümün hak olduğunu ve ruhun bedenden ayrılması olduğunu bilmelidir.",
        "Ve Allah Teâlâ’dan başka her şeyin yok olacağını bilmelidir.",
    ]),
    "aq-15": ("Diriliş, hesap ve karşılık", "İnsanlar kıyamet günü diriltilir, sonra cennet ya da cehennem.", [
        "Her insanın kıyamet günü diriltileceğini ve bunun kıyametin kopması olduğunu bilmelidir.",
        "Rablerinin huzurunda toplanacaklarını ve Rabbimiz nasıl dilerse öyle hesaba çekileceklerini bilmelidir.",
        "Allah’ın, kendisine itaat edenler için hazırladığı cennet adında bir ödülü olduğunu; onun benzeri bir ödül olmadığını, oraya girenin çıkmayacağını, ölmeyeceğini ve hastalanmayacağını bilmelidir.",
        "Allah’ın, büyük günah işleyenler için hazırladığı cehennem adında bir cezası olduğunu bilmelidir; Allah bizi ondan ve ona yaklaştıran şeylerden korusun.",
    ]),
    "aq-16": ("Korku ve ümit", "Allah’ın mükâfatını umar, azabından korkarız.", [
        "Mükellef, Allah’ın sevabını ummalı ve azabından korkmalıdır.",
        "Korku ile ümidin eşit tutulması gerektiği söylenmiştir; korku artarsa ümitsizlikten, ümit artarsa kendini güvende görmekten endişe edilir.",
        "Açık olan görüş eşitliğin şart olmadığıdır; haram olan ümitsizliğe veya yasak olan emniyete varmadıkça sakıncası yoktur.",
    ]),
    "aq-17": ("Kaza ve kader", "Hiçbir şey Allah’ın dilemesi olmadan hareket etmez ve durmaz.", [
        "Bütün varlıklarda hiçbir hareket edenin hareket etmediğini ve hiçbir durağanın durmadığını, ancak Allah’ın dilemesi ve takdiriyle olduğunu bilmelidir.",
    ]),
    "aq-18": ("Nimetler ve “Cümle”", "Üzerimizdeki en büyük nimet İslam nimetidir.", [
        "Allah’ın kendisine verdiği nimetleri bilmelidir: yokluktan sonra var olmak, hastalıktan sonra sağlık ve en büyüğü İslam nimeti.",
        "Bunların hepsi “Cümle”nin altına girer: “Allah’tan başka ilah yoktur, Muhammed Allah’ın Resulüdür ve Muhammed’in Rabbinden getirdiği haktır.”",
        "Mükellef bu cümleye şahitlik edince, onun bir kısmını inkâr etmek, bilmemek veya ondan şüphe etmekle bozmadıkça Allah katında ve insanlar nezdinde mümin ve Müslüman olur.",
    ]),
    "aq-19": ("Velayet, beraet ve vakıf", "Allah’ın dostlarını sever, düşmanlarından uzak dururuz.", [
        "İlkinden sonuncusuna kadar Allah’ın bütün dostlarını dost edinmeli ve Allah’ın bütün düşmanlarından uzak durmalıdır; bu “genel velayet ve genel beraet”tir.",
        "Sonra Müslümanların önderlerinden ve seçkinlerinden dostluğunu bildiklerini dost edinir; zalim önderlerden düşmanlığını bildiklerinden uzak durur.",
        "Durumunu bilmediği kimse hakkında, dostluğu veya uzak durmayı gerektiren bir şey bilinceye kadar hüküm vermez (vakıf).",
    ]),
    "sl-0": ("Amelî ibadet çeşitleri", "İbadet bedenî, malî ya da her ikisidir.", [
        "Organlarla yapılan amel iki çeşittir: bedenî ibadet ve malî ibadet.",
        "Malî ibadet: zekât ve hakları sahiplerine vermek; borçlar, misafir hakkı ve komşu hakkı gibi.",
        "Salt bedenî ibadet: namaz ve görevleri, oruç, akrabayı ziyaret ve komşuyla ilişkiyi sürdürmek.",
        "Hem bedenî hem malî ibadet: mal harcamayı gerektirenler, hac ve cihad gibi.",
    ]),
    "sl-1": ("Namaz", "Bir gün ve gecede beş namaz.", [
        "Namaz, mükellefe bir gün ve gecede beş kez farz olan salt bedenî bir ibadettir.",
        "İnancı öğrendikten sonraki farzların ilkidir.",
    ]),
    "sl-2": ("Öğle namazı", "Gizlice Fâtiha okunan dört rekât.", [
        "Öğle vaktinde dört rekât farzdır; her rekâtta Fâtiha gizlice okunur ve Kur’an’dan başka bir şey eklenmez.",
        "Sonra ardından Fâtiha ve bir sure ile iki rekât kılması tavsiye edilir.",
        "Sonra Fâtiha ve bir sure ile iki rekât nafile kılması müstehaptır.",
        "Bunların hepsinde okuma gizlidir.",
    ]),
    "sl-3": ("İkindi namazı", "Yalnızca Fâtiha okunan dört rekât, gizlice.", [
        "İkindi vaktinde dört rekât farzdır: “ikindinin farzı”.",
        "Her rekâtta yalnızca Fâtiha okunur ve okuma gizlidir.",
    ]),
    "sl-4": ("Akşam namazı", "Üç rekât, sonra iki rekât sünnet.", [
        "Akşam vaktinde üç rekât farzdır: ilk ikisinde Fâtiha ve bir sure, üçüncüsünde yalnızca Fâtiha.",
        "İmam ilk ikisinde açıktan, üçüncüde gizli okur; cemaat ve yalnız kılan üçünde de gizli okur.",
        "İmamın arkasındaki cemaat yalnızca Fâtiha’yı gizlice okur.",
        "Akşamın farzından sonra iki rekât müekked sünnettir; ardından iki rekât nafile müstehaptır.",
    ]),
    "sl-5": ("Yatsı namazı", "Dört rekât, sonra iki rekât.", [
        "Yatsı vaktinde dört rekât farzdır.",
        "İlk ikisinde Fâtiha ve bir sure: imam için açıktan, yalnız kılan için gizli.",
        "Son ikisinde yalnızca Fâtiha, gizlice.",
        "Bu farzdan sonra Fâtiha ve bir sure ile iki rekât kılması tavsiye edilir.",
    ]),
    "sl-6": ("Vitir namazı", "Yatsı ile sabah arasında üç rekât.", [
        "Yatsı ile fecir arasında üç rekât vardır, bunlara “vitir” denir; hepsinde Fâtiha ve bir sure okunur.",
        "Yazar onu vacip saymıştır; Ebû İshak Atfeyyiş ise doğru görüşün, akşam ve sabah sünnetleri gibi müekked sünnet olduğu şeklinde açıklama yapmıştır.",
    ]),
    "sl-7": ("Sabah namazı", "İki rekât sünnet, sonra iki rekât farz.", [
        "Fecir doğunca iki rekât sünnettir: “sabahın sünneti”, Fâtiha ve bir sure ile.",
        "Sonra iki rekât farzdır: “sabahın farzı”, her rekâtta Fâtiha ve bir sure ile.",
        "İmam için açıktan, yalnız kılan için gizli; cemaat yalnızca Fâtiha’yı gizlice okur.",
    ]),
    "sl-8": ("Namaz vakitleri", "Her namazın bir başlangıç ve bir bitiş vakti vardır.", [
        "Öğle: başlangıcı güneşin zevalidir; sonu, zeval gölgesinden sonra her şeyin gölgesinin kendisi kadar olmasıdır.",
        "İkindi: başlangıcı gölgenin öğlenin sonundan biraz fazla olması; sonu güneşin bir kısmının batmasıdır; güneşin sararması da denmiştir.",
        "Akşam: başlangıcı güneşin tamamen batması, sonu kızıl şafağın kaybolmasıdır; beyaz şafak da denmiştir.",
        "Yatsı: başlangıcı şafağın tamamen kaybolması, sonu gecenin üçte biridir; gecenin yarısı da denmiştir.",
        "Sabah: başlangıcı ikinci fecrin doğması, sonu güneşin bir kısmının doğmasıdır.",
    ]),
    "sl-9": ("Namazın caiz olmadığı vakitler", "Üç vakitte namaz yasaklanmıştır.", [
        "Güneşin bir kısmı doğduğunda: namaz güneş tamamen doğana kadar ertelenir.",
        "Güneşin bir kısmı battığında: güneş tamamen batana kadar namaz caiz değildir.",
        "Şiddetli sıcakta güneş göğün ortasında durduğunda: zeval olana kadar namaz kılınmaz.",
        "Sabah namazından sonra güneş doğana kadar ve ikindiden sonra güneş batana kadar nafile yasaktır; fecirden sonra sabahın iki rekâtı dışında nafile mekruhtur.",
    ]),
    "sl-10": ("Namazın kılınışı", "Temizlik, sonra kıble, sonra Allah için halis niyet.", [
        "Bedeni ve elbisesi temiz, bütün hadeslerden arınmış olarak temiz bir yerde dimdik durur.",
        "Yüzüyle Kâbe’ye yönelir, kalbiyle o farzın kendisine niyet eder, rekâtlarını gözetir ve Rabbine ihlaslı olur.",
        "Niyeti dille pekiştirmesi uygundur; örneğin şöyle der: “Tebârek ve Teâlâ olan Allah için, şu yerimde, öğle namazının farzını, dört rekât, Kâbe-i Şerife’ye yönelerek, farzı eda etmek üzere, Allah’a ve Resulü Muhammed ﷺ’e itaat olarak kılıyorum.”",
    ]),
    "sl-11": ("Ezan ve sonrası", "Kamet, sonra tevcih, sonra niyeti pekiştirmek.", [
        "Sonra kadınlar için değil erkekler için kamet; ezan da erkekler içindir.",
        "Sonra Peygamberimiz ﷺ’in tevcihini okur: “Allah’ım, seni hamdinle tesbih ederim; adın mübarek, şanın yüce, övgün büyüktür ve senden başka ilah yoktur.”",
        "Sonra atamız İbrahim’in tevcihini ekler: “Ben hanîf olarak yüzümü gökleri ve yeri yaratana çevirdim ve ben müşriklerden değilim.” [En‘âm: 79]",
        "Sonra niyeti pekiştirir: “Allah Teâlâ için öğle namazının farzını dört rekât kılıyorum ve Kâbe kıblemdir.”",
    ]),
    "sl-12": ("İftitah tekbiri ve birinci rekât", "Allahu ekber… sonra Fâtiha, rükû ve secde.", [
        "İftitah tekbirini alır: “Allahu ekber”, sonra kısa bir süre susar.",
        "Gizlice istiâze eder: “Kovulmuş şeytandan Allah’a sığınırım”, sonra besmele çekip Fâtiha’yı okur.",
        "Tekbirle rükûa gider, avuçları dizlerde sırtı düzleşir ve üç kez “Yüce Rabbimi tenzih ederim” der.",
        "“Allah kendisine hamd edeni işitir” diyerek kalkar; dikilince “Rabbimiz, hamd sanadır” der.",
        "Tekbirle secdeye gider; önce dizlerini, sonra ellerini, sonra burnunu ve alnını koyar, yedi uzuv üzerine: alın, eller, dizler ve ayaklar; üç kez “En yüce Rabbimi tenzih ederim” der.",
        "Tekbirle başını kaldırır, her eklem yerine oturana kadar oturur, sonra birincisi gibi bir secde daha yapar.",
    ]),
    "sl-13": ("İkinci rekât", "Tekbirle kalkar ve Fâtiha okuruz.", [
        "Tam doğrulmadan önce bitirdiği bir tekbirle ikinci rekâta kalkar; önce alnını, sonra ellerini, sonra dizlerini kaldırır.",
        "Besmele çekip Fâtiha’yı okur, sonra kısa bir süre susar.",
        "Sonra birinci rekâttaki gibi rükû ve secde eder.",
    ]),
    "sl-14": ("İlk teşehhüd", "İkinci rekâttan sonra tahiyyat için otururuz.", [
        "İkinci secdeden kalkıp tahiyyat, yani “ilk teşehhüd” için oturur ve şöyle der:",
        "“Mübarek selamlar Allah’a aittir, dualar ve güzel şeyler de; Peygamber’e selam, Allah’ın rahmeti ve bereketleri olsun; bize ve Allah’ın salih kullarına selam olsun. Şahitlik ederim ki Allah’tan başka ilah yoktur, O tektir, ortağı yoktur; ve şahitlik ederim ki Muhammed O’nun kulu ve Resulüdür.”",
    ]),
    "sl-15": ("Üçüncü rekât", "Yalnızca Fâtiha, sonra rükû ve secde.", [
        "Dimdik durmadan önce bitirdiği bir tekbirle üçüncü rekâta kalkar.",
        "Ayakta yalnızca “Elhamdü” (Fâtiha) okur.",
        "Sonra önceki gibi rükû eder, kalkar ve secde eder.",
    ]),
    "sl-16": ("Dördüncü rekât", "Yalnızca Fâtiha, sonra rükû ve secde.", [
        "Tekbirle dördüncü rekâta kalkar ve yalnızca Fâtiha okur.",
        "Sonra önceki gibi rükû ve secde eder.",
    ]),
    "sl-17": ("Son teşehhüd ve selam", "Teşehhüd okur, selam veririz ve namaz tamamlanır.", [
        "Tahiyyat, yani “son teşehhüd” için oturur ve onu önceki gibi okur.",
        "“Ve şahitlik ederim ki Muhammed O’nun kulu ve Resulüdür”e gelince dilerse selam verir ve namazı tamamlanır.",
        "Dilerse şunu ekler: “ﷺ, onu hidayetle ve hak dinle, müşrikler hoşlanmasa da onu bütün dinlere üstün kılmak için gönderdi. Rabbimiz, bize dünyada da iyilik ver, ahirette de iyilik ver ve bizi ateş azabından koru”, sonra selam verir.",
    ]),
    "sl-18": ("Akşam namazının kılınışı", "İki rekât sonra teşehhüd, sonra yalnızca Fâtiha ile üçüncü rekât.", [
        "İlk iki rekâtı Fâtiha ve bir sure ile kılar, sonra oturup teşehhüdü “kulu ve Resulüdür”e kadar okur.",
        "Sonra üçüncüye kalkar, yalnızca Fâtiha okur, rükû ve secde eder, son teşehhüdü okur ve selam verir.",
    ]),
    "sl-19": ("İmamın arkasında namaz", "Hiçbir şeyde imamın önüne geçmeyiz.", [
        "Cemaatin, bütün namazlarda ve bütün rekâtlarda yalnızca Fâtiha okuması gerekir.",
        "İmamın arkasında “Allah kendisine hamd edeni işitir” demez; imam dedikten sonra “Rabbimiz, hamd sanadır” der.",
        "Hiçbir şeyde imamın önüne geçmemelidir: ne tekbirde, ne okumada, ne rükûda, ne kalkışta; önüne geçerse namazı bozulur.",
        "Aynı şekilde imamdan çok geride kalırsa namazı bozulur; ondan biraz sonra hareket etmelidir.",
    ]),
    "sl-20": ("Namaza geç yetişmek", "İmamla kaçırdığını, onun selamından sonra kaza edersin.", [
        "Cemaat, imam namaza başladıktan sonra gelirse ona katılır, yetiştiğini kılar, imamın selamından sonra kalkıp kaçırdığını kaza eder.",
        "Yalnızca Fâtiha’yı kaçırdıysa kalkar, onu okur, sonra tekbirsiz oturup selam verir.",
        "Bir rekâtın tamamını kaçırdıysa tekbirsiz kalkar, istiâze edip okur, rükû ve secde eder, tekbirle kalkar, sonra oturup selam verir.",
        "Kural: kaçırılan, eksiksiz ve fazlasız kaza edilir.",
    ]),
    "sl-21": ("Yolculuk namazı", "Yolcu dört rekâtlı namazları iki rekât kılar.", [
        "Yolcu olduğunda öğle, ikindi ve yatsıyı ikişer rekât kısaltarak kılman farzdır.",
        "Her birini kendi vaktinde kılarsan şöyle dersin: “Allah için öğlenin farzını iki rekât, kasr olarak, yolculuk namazı olarak kılıyorum.”",
        "Evde kıldığın sünnet ve nafileleri kılman müstehaptır; terk edersen sakıncası yoktur, akşamın sünneti hariç.",
    ]),
    "sl-22": ("İki namazı birleştirmek (cem)", "Yolculukta öğleyi ikindiyle, akşamı yatsıyla birleştiririz.", [
        "Öğle ile ikindiyi bir vakitte, akşam ile yatsıyı bir vakitte, öne alarak veya erteleyerek birleştirebilirsin.",
        "Şöyle dersin: “Allah Teâlâ için öğlenin farzını iki rekât ve ikindinin farzını iki rekât, cem ederek, yolculuk namazı olarak kılıyorum.”",
        "Birincinin selamından sonra kamet, tevcih ve iftitah tekbiriyle ikinciye kalkarsın.",
        "Vitri iki gece namazıyla birleştirebilirsin; sünnetler ve nafileler kamet gerektirmez.",
    ]),
    "sl-23": ("Kısaltılmayanlar ve korku namazı", "Akşam ve sabah ancak korku veya hastalık için kısaltılır.", [
        "Akşam ve sabah namazından hiçbir şey kısaltılmaz; ancak tamamlamaya engel olan korku veya hastalık hali müstesna.",
        "Düşmanla karşı karşıya kalma namazı: ordu iki gruba ayrılır, her grup imamla bir rekât kılar, sonra hepsi onunla selam verir.",
        "Göğüs göğse savaş namazı: fiil veya işaretle kılamıyorsa her farz için beş tekbir alır.",
        "Genel korku namazı: yaya veya binekli, nasıl mümkünse öyle kılarlar.",
    ]),
    "sl-24": ("Hastanın namazı", "Hasta gücü yettiği kadar namaz kılar.", [
        "Hasta, namazdan ve görevlerinden yapamadığını kısaltır.",
        "Su ile temizlenemiyorsa teyemmüm eder; ayakta duramıyorsa oturarak kılar.",
        "Oturamıyorsa sağ yanı üzerine kıbleye dönük yatarak kılar; rükû ve secde için başıyla işaret eder.",
        "Buna da gücü yetmezse farz için beş tekbir alır; onu da yapamazsa mazurdur, çünkü Allah hiç kimseyi gücünün üstünde yükümlü tutmaz.",
    ]),
    "sl-25": ("Cuma namazı ve kılınışı", "Ezan, hutbe ve kametle cemaatle iki rekât.", [
        "Cuma günü öğle namazı kısaltılır ve imamla iki rekât kılınır: “Cuma namazı”.",
        "Ancak cemaatle, ezan, hutbe ve kametle kılınır.",
        "Müezzin zevalden sonra ezan okur, sonra imam hutbe okur: Allah’a hamd eder, Peygamberine salavat getirir ve uzatmadan insanlara öğüt verir.",
        "Sonra müezzin kamet getirir ve imam açıktan okuyarak iki rekât kıldırır.",
        "İmam hutbe okurken kimse konuşmaz; herkes hutbeyi dinler.",
    ]),
    "sl-26": ("Cumanın sünnetleri", "Gusül, en güzel elbise ve güzel koku.", [
        "Cumaya katılmak isteyen için cuma günü cünüplükten yıkanır gibi gusletmek sünnettir.",
        "En güzel elbisesini giymek ve sahip olduğu en güzel kokuyu sürünmek sünnettir.",
        "İnsanların omuzlarının üzerinden atlamak mekruhtur; yer bulduğu yere oturur.",
    ]),
    "sl-27": ("Bayram namazları", "On üç tekbirle iki rekât.", [
        "Ramazan ve Kurban bayramı namazı farz-ı kifayedir: imamın açıktan okuduğu, cemaatle kılınan iki rekât.",
        "Namaz kılan şöyle der: “Allah Teâlâ için Ramazan (veya Kurban) bayramı sünnetini, on üç tekbirle iki rekât, Kâbe-i Şerife’ye yönelerek kılıyorum.”",
        "İftitah tekbirinden sonra beş tekbir, sonra kıraat, sonra rükû ve secde.",
        "İkincide: kıraat, sonra beş tekbir, sonra rükû, sonra rükûdan kalktıktan sonra üç tekbir, sonra secde, teşehhüd ve selam.",
        "Şehir dışındaki namazgâhta kılınır; cuma ise ulu camide kılınır.",
    ]),
    "sl-28": ("Bayram hutbesi", "İmam onu tekbirle başlatır.", [
        "İmam namazdan sonra tekbirle başlayan bir hutbe okur; insanlar dinler.",
        "Onlara Allah’tan korkmayı tavsiye eder, o gün kendilerine gerekenleri söyler ve güzel öğütlerle nasihat eder.",
    ]),
    "th-1": ("Namazın şartları", "Namazın, onlarsız tamam olmadığı sekiz şartı vardır.", [
        "Birinci: tuvalet ihtiyacını tutarak namaz kılmamak.",
        "İkinci: istincâ ve bedenden pislikleri yıkamak.",
        "Üçüncü: temiz su ile abdest.",
        "Dördüncü: cünüplükten gusül.",
        "Beşinci: atamız İbrahim’e emredilen fıtrat hasletleri.",
        "Altıncı: temiz yer. Yedinci: temiz ve örten elbise. Sekizinci: kıbleye yönelmek.",
    ]),
    "th-2": ("Tuvalet âdabı", "Örtünür, sol ayakla girer, sağ ayakla çıkarız.", [
        "Tuvalet ihtiyacı varken namaz kılmaz; önce gidip ihtiyacını giderir.",
        "Uzaklaşır ve insanlardan gizlenir; bevl ve gaitada kıbleye yönelmez ve arkasını da dönmez.",
        "İnsanların oturduğu yerlerde, gölgeliklerinde, meyve ağaçlarının altında ve suda ihtiyacını gidermez.",
        "Girerken sol ayağını öne atar ve der: “Pis, murdar, habis, kovulmuş şeytandan Allah’a sığınırım.”",
        "Çıkarken sağ ayağını öne atar ve der: “Benden eziyeti gideren Allah’a hamd olsun.”",
        "Tuvalet camiin tersidir: camiye sağ ayakla girilip sol ayakla çıkılır; eve ise giriş ve çıkış sağ ayakladır.",
    ]),
    "th-3": ("İstincâ", "Pislik gidene kadar su ile temizlik.", [
        "Bedendeki pislikleri nerede olursa olsun yıkamalıdır; buna gücü yetiyorsa su ile istincâ da dahildir.",
        "Gücü yettiği halde su ile istincâ yapmazsa ne abdesti ne de namazı tamam olur.",
        "Belirli bir sayı yoktur; amaç temizlik ve pisliği gidermektir, ovuşturma sayısı değil.",
    ]),
    "th-4": ("Pislik çeşitleri", "Pislikleri bedenden ve elbiseden yıkarız.", [
        "Pisliklerden: idrar, dışkı, akan kan ve kusmuk.",
        "Yırtıcı hayvanların dışkısı ve idrarı ile bütün hayvanların idrarı.",
        "Leş, domuz ve köpek.",
        "Bunlardan kaçınmak ve bedene ve elbiseye bulaşanı yıkamak gerekir.",
    ]),
    "th-5": ("Abdest ve alınışı", "Ağız, burun, yüz, kollar, baş, kulaklar, ayaklar.", [
        "Temiz su ile abdest alır ve başında Allah’ın adını anar.",
        "Oruçlu değilse ağzına üç kez su verip iyice çalkalar.",
        "Sonra burnuna su verip sümkürür, sonra yüzünü üç kez yıkar.",
        "Sonra sağ kolunu dirsekle birlikte üç kez, sonra sol kolunu aynı şekilde yıkar.",
        "Sonra başını meshedir, sonra kulaklarını içinden ve dışından meshedir.",
        "Sonra sağ ayağını topuklara kadar üç kez, sonra sol ayağını aynı şekilde yıkar.",
    ]),
    "th-6": ("Abdestin bazı sünnetleri ve duaları", "Misvak ve her organ için güzel dualar.", [
        "Abdestten önce misvak kullanmak sünnettir; uykudan kalkmışsa ellerini kaba sokmadan önce üç kez yıkar.",
        "Ağza su verirken: “Allah’ım, bana mühürlü saf içecekten içir.”",
        "Yüzü yıkarken: “Allah’ım, salih kullarının yüzlerinin ağaracağı gün yüzümü nurunla ağart.”",
        "Sağ kolu yıkarken: “Allah’ım, kitabımı sağ elimden ver ve hesabımı kolay eyle.”",
        "Başı meshederken: “Allah’ım, senin gölgenden başka gölgenin olmadığı gün beni arşının gölgesinde gölgelendir.”",
        "Ayakları yıkarken: “Allah’ım, ayaklarımı hak ve din üzere sabit kıl, rahmetinle ey merhametlilerin en merhametlisi.”",
    ]),
    "th-7": ("Teyemmüm", "Su bulamazsak temiz toprakla teyemmüm ederiz.", [
        "Su bulamazsa ya da bulup da abdest için kullanamazsa temiz toprakla teyemmüm eder.",
        "Avuçlarını yere vurur, sonra onlarla yüzünü meshedir.",
        "Sonra ikinci kez vurur ve iki elinin üstünü ve içini bileklere kadar meshedir.",
        "Allah’ın adını anar ve hadesi kaldırmaya ve namazı mubah kılmaya niyet eder.",
    ]),
    "th-8": ("Teyemmümün caiz olduğu ve olmadığı şeyler", "Teyemmüm tozlu toprakla olur.", [
        "Kül, alçı, kireç harcı, kireç, çorak tuzlu toprak, kum ve ıslak çamurla teyemmüm olmaz.",
        "Yalnızca tozu olan toprakla teyemmüm edilir.",
        "Onu bulamazsa toprağa en çok benzeyen şeyle teyemmüm eder.",
    ]),
    "th-9": ("Cünüplükten gusül", "Gusül cünübe ve hayızdan temizlenen kadına farzdır.", [
        "Cünüp olana, erkek veya kadın, gusül farzdır.",
        "Aynı gusül hayızdan temizlenen kadına da farzdır.",
        "Su varsa namaz onsuz tamam olmaz; yoksa namaz için teyemmüm eder gibi toprakla teyemmüm eder.",
    ]),
    "th-10": ("Guslün alınışı", "Sağdan başlarız ve suyu bütün bedene ulaştırırız.", [
        "Ellerini yıkar, pisliği yerinden giderir, sonra ağzına ve burnuna su verir.",
        "Sonra yüzünü ve diğer abdest organlarını yıkar; yapmazsa sakıncası yoktur, ama ağza ve burna su vermek gereklidir.",
        "Başına üç avuç su döker, sonra başın sağını sonra solunu, boynun sağını sonra solunu yıkar.",
        "Sonra bedenin sağını sonra solunu, sonra sağ bacağı sonra solu yıkar ve suyla birlikte elini bedeninde gezdirir.",
        "Sıra gözetmeden suyu bütün bedene ulaştırırsa yeterlidir; ancak su, el gezdirilerek bütün bedene ulaşmalıdır.",
    ]),
    "th-11": ("Atamız İbrahim’in bazı sünnetleri", "Fıtrat hasletleri ve temizlik.", [
        "Kasık kılları uzayınca onları tıraş etmesi emredilir; ayda bir ya da kırk günde bir denmiştir.",
        "Koltuk altı kıllarını yolması, bıyığını kısaltması, tırnaklarını kesmesi ve uzunsa saçını ayırması emredilir.",
        "Bu hasletler, atamız İbrahim aleyhisselamın emrolunduğu şeylerdendir.",
    ]),
    "th-12": ("Namaz kılınabilen yerler", "Namazımız için temiz bir yer seçeriz.", [
        "Namazı için temiz bir yer seçer.",
        "Yolun ortasında ve develerin yattığı yerde namaz kılmaz.",
        "Gasbedilmiş arazide ve alçı, kireç, kül gibi ateşin yaktığı şeyler üzerinde namaz caiz değildir.",
        "Kâbe’nin damında da caiz değildir; çünkü orada namaz kılan kıbleye yönelmiş olmaz.",
    ]),
    "th-13": ("Namaz elbisesi", "Avreti örten temiz elbise.", [
        "Temiz ve örten elbise şarttır.",
        "Avretini örtecek bir şey bulamazsa oturarak ve işaretle kılar.",
        "Temiz elbise varken necis elbiseyle namaz kılmaz.",
        "Başka bir şey bulamadıkça ipek elbiseyle namaz kılmaz.",
    ]),
    "th-14": ("Kıbleye yönelmek", "Kıble, yüce Kâbe’dir.", [
        "Kıble yüce Kâbe’dir; namaz ancak ona yönelmekle tamam olur.",
        "Namaz kılan, güneşin ve ayın doğup batması ve yönleri bilmek gibi kıbleyi gösteren işaretleri bilmelidir.",
        "Doğruluğuna gönlü kanan birinin kıble yönü hakkındaki sözüne güvenebilir.",
        "Şaşırır ve haber verecek kimse bulamazsa yönünü araştırır ve o yöne doğru kılar.",
    ]),
    "jn-1": ("Cenaze namazı", "Rükûsuz ve secdesiz, dört tekbirli bir namaz.", [
        "Cenaze namazı farz-ı kifayedir; rükû ve secdesi yoktur.",
        "Namaz kılan der ki: “Allah Teâlâ için bu ölü üzerine, Resulullah ﷺ’in emrettiği sünneti dört tekbirle, Allah’a ve Resulüne itaat olarak kılıyorum.”",
        "Birinci tekbiri alır, istiâze eder ve Fâtiha okur; sonra ikinci tekbiri alır ve Fâtiha okur.",
        "Sonra üçüncü tekbir: Allah’a hamd eder, Resulüne ﷺ salavat getirir, kendi günahı ve müminler için bağışlanma diler ve dua eder.",
        "Sonra dördüncü tekbir, ardından hafif bir selam.",
    ]),
    "jn-2": ("Cenaze namazında dua", "Ölü için rahmet dileriz.", [
        "Ölü salih biriyse şöyle der: “Allah’ım, falan senin kulun, kulunun oğlu, cariyenin oğludur; onu vefat ettirdin, bizi ondan sonra bıraktın. Allah’ım, ona evinden daha hayırlı bir ev, ailesinden daha hayırlı bir aile ver…”",
        "Ayırt edemeyen şöyle der: “Dirileri öldüren, ölüleri dirilten ve kabirdekileri dirilten Allah’a hamd olsun… Rabbimiz, rahmetin ve ilmin her şeyi kuşatmıştır; tövbe edip yoluna uyanları bağışla ve onları cehennem azabından koru.”",
        "Sonra Peygamber ﷺ’e, âline ve ashabına salavat getirir, tekbir alır ve selam verir.",
    ]),
    "jn-3": ("Ölünün yıkanması", "Ölü nazikçe yıkanır, sağdan başlanır.", [
        "Ölüye namaz abdesti gibi abdest aldırılır; doğru görüşe göre bu, ölüyü yıkamada sünnettir.",
        "Sonra varsa su ve sidr (çiriş) veya benzeriyle yıkanır; yoksa sakıncası yoktur.",
        "Başın sağından başlanır, sonra solu, sonra boyun, kollar, sağ yan sonra sol yan, sonra bacaklar.",
        "Sonra suyla bütün bedeni yıkanır ve olabildiğince nazik davranılır.",
    ]),
    "jn-4": ("Ölüye teyemmüm", "Yıkamak mümkün değilse temiz toprakla teyemmüm ettirilir.", [
        "Su yoksa veya ölünün bedeni yıkanamayacak durumdaysa, yıkamanın yerine temiz toprakla teyemmüm ettirilir.",
        "Ellerini toprağa koyar ve ölünün yüzünü meshedir, sonra tekrar koyar ve ellerini meshedir.",
        "Kalbiyle vazifeyi yerine getirmeye niyet eder ve yaptığı işe Allah’ın adını anar.",
    ]),
    "jn-5": ("Ölüyü yıkamanın sünneti", "Ölüyü örter ve saygınlığını koruruz.", [
        "Yıkanırken ölüyü örten bir örtü gerekir; bunu yıkayandan başkası tutar.",
        "Avretinden hiçbir yere bakmak caiz değildir.",
    ]),
    "jn-6": ("Kefenleme ve hanût", "Ölü temiz bezle kefenlenir ve güzel kokulanır.", [
        "Ölü, namazın caiz olduğu elbiselerden bir veya daha fazlasıyla kefenlenir.",
        "Bedeni sudan kurulanır ve kefenlerine sarılır.",
        "Hanût sürülür; yani kâfur ve zaferan gibi güzel koku konur.",
        "Sonra teneşire/tabuta konur, örtülür, kokulanır ve buhurlanır.",
    ]),
    "jn-7": ("Ölünün taşınması", "Cenazeyle ağır ağır yürürüz.", [
        "Onu tabutuna koyunca onunla yumuşak bir yürüyüşle yürürler.",
        "Namaz yerine veya kabre götürürken başını öne alırlar.",
    ]),
    "jn-8": ("Ölünün defnedilmesi", "Sağ yanı üzerine, kıbleye dönük konur.", [
        "Ölü lahdine sağ yanı üzerine, kıbleye dönük olarak yatırılır.",
        "Sonra üzerine kerpiç konur, sonra toprakla gömülür.",
        "Cenazeyi uğurlamak emredilmiştir ve büyük fazileti vardır.",
        "Arkasından çokça Allah’ı anmak uygundur; “Allah’tan başka ilah yoktur, ölmeyen diridir” demek müstehaptır da denmiştir.",
    ]),
    "sw-1": ("Oruç ve tutuluşu", "Fecirden gün batımına kadar kendimizi tutarız.", [
        "Oruç salt bedenî bir ibadettir; farz olanı her yıl mübarek Ramazan ayını oruçla geçirmektir.",
        "Fecrin doğuşundan gün batımına kadar yemekten ve içmekten uzak durmaktır.",
        "Çirkin sözden, gıybetten ve söz taşımaktan sakınmak ve bütün günahlardan kaçınmaktır; çünkü günahlar orucu bozar.",
        "Unutarak yiyen veya içen hakkında iki görüş vardır: orucu bozulur ve kazası gerekir denmiştir; unutmak affedildiği için bir şey gerekmez de denmiştir.",
    ]),
    "sw-2": ("Orucun sıhhat şartı", "Geceden niyet etmek.", [
        "Geceden, sabaha Ramazan farzı oruçlu olarak, Allah’a ve Resulü Muhammed ﷺ’e itaat için gireceğine niyet etmek.",
        "Geceden oruca niyet etmeyenin orucu yoktur.",
        "Cünüp olarak sabaha girmemelidir; cünüp olan fecirden önce gusletmelidir.",
        "Gündüz ihtilam olan hemen gusleder ve ona bir şey gerekmez.",
    ]),
    "sw-3": ("Ramazan gecelerini ihya", "Ramazan gecelerinde Allah’ın dilediği kadar namaz kılarız.", [
        "Ramazan gecesinde yatsı ile fecir arasında Allah’ın dilediği kadar namaz kılması tavsiye edilir.",
        "Her gece yirmi rekât kılması uygundur; on iki rekâtla yetinirse yeterlidir.",
        "Ramazan gecelerinde vitir namazı da gereklidir.",
    ]),
    "sw-4": ("Haram ve mekruh oruçlar", "Bayram günü oruç tutmayız.", [
        "İki bayram günü oruç tutmak haramdır.",
        "Teşrik günlerinde oruç tutmak mekruhtur.",
        "Şek gününde oruç tutmak mekruhtur; haram olduğu da söylenmiştir.",
    ]),
    "sw-5": ("Müstehap oruçlar", "Eyyâm-ı bîd, Âşûrâ ve Şevval’in altı günü.", [
        "Her ayın on üç, on dört ve on beşinci günleri olan eyyâm-ı bîd orucu müstehaptır.",
        "Bayramdan önceki Zilhiccenin dokuz günü, Muharrem’deki Âşûrâ ve Şevval’den altı gün müstehaptır.",
        "Zilkade’den bir gün (yirmi beşinci), Recep’ten bir gün (yirmi yedinci) ve Şaban’dan bir gün (on beşinci) de müstehaptır.",
    ]),
    "hq-1": ("Anne babanın hakları", "Anne babanın rızası cennete açılan bir kapıdır.", [
        "Akrabalık bağının en büyüğü anne babanın hakkıdır; Peygamber ﷺ buyurdu: “Kim anne babası kendisinden razı olarak sabahlarsa, ona cennetten bir kapı açılmış olur.”",
        "Onları azarlamaz, sözle incitmez, sert konuşmaz; aksine sözünde onlara karşı alçak gönüllü ve yumuşak olur.",
        "Yollarından eziyeti kaldırmak dışında önlerinde yürümez ve onlara adlarıyla seslenmez, “babacığım” der.",
        "Anne babanın emrettiği her itaat veya mubah şeyi, gücü yetiyorsa yerine getirmesi gerekir.",
        "Allah’a isyanı emretmedikçe onlara karşı gelmez; çünkü “Yaradana isyanda yaratılmışa itaat olmaz.”",
    ]),
    "hq-2": ("Çocukların hakları", "Çocuğun anne babası üzerinde güzel terbiye ve öğretim hakkı vardır.", [
        "Anne babanın üzerindeki haklar, çocuğun onlara karşı olan hakları gibidir.",
        "Onu güzelce terbiye etmek ve ona Kur’an’ı, hesabı, namazı, farzları ve ihtiyaç duyduğu her şeyi öğretmek.",
        "Büyüyüp geçimini kazanabilir hale gelene kadar nafakasını vermek ve onu giydirmek.",
        "Ona isimlerin en güzelini seçmek: peygamberlerin ve salihlerin isimleri.",
    ]),
    "hq-3": ("Akrabaların hakları", "Sıla-i rahim farzdır; en güzeli hediyeyle olanıdır.", [
        "Akrabalar, seninle ortak bir dedede birleşenlerdir; onlarla bağı sürdürmek farzdır.",
        "Sıla, malıyla ve bedeniyle gücü yetene düşer.",
        "Meşguliyeti sebebiyle onlara ulaşamayan, ziyaret niyetini sürdürdüğü sürece mazurdur.",
        "Sılanın en güzeli hediye göndermek, en zayıfı selam göndermektir.",
    ]),
    "hq-4": ("Komşunun hakları", "Komşumuza eziyet etmez, sevincini ve üzüntüsünü paylaşırız.", [
        "Komşuyla iyi ilişki sabit bir haktır; yakın da olsa uzak da olsa.",
        "Peygamber ﷺ buyurdu: “Cebrail bana komşu hakkında o kadar tavsiyede bulundu ki onu mirasçı kılacağını sandım.”",
        "Komşunun hakkından biri ondan eziyeti uzak tutmaktır; komşuya eziyet etmek caiz değildir.",
        "Sevinçli anında ve musibet anında onu ziyaret eder.",
        "Onda olmayıp kendisinde olan şeyleri bildiği zaman onunla paylaşır.",
    ]),
    "hq-5": ("Yol arkadaşının hakları", "Yol arkadaşının yardım ve paylaşma hakkı vardır.", [
        "“Yanındaki arkadaş” yol arkadaşıdır ve onun bir hakkı vardır.",
        "Ona iyilikle ve güzel ahlakla arkadaşlık eder, eziyeti uzak tutar, yiyecek ve içecekte onu kendine ortak eder, hiçbir şeyi yalnız kendine ayırmaz.",
        "Onun yanında başkasıyla fısıldaşmaz.",
        "Hastalanırsa ona bakar; bir işi varsa bitirene kadar onu bekler.",
    ]),
    "hq-6": ("İlim yolundaki arkadaşın hakları", "İlim tahsilinde yardımlaşır ve birbirimize öğüt veririz.", [
        "Dünya ve ahiret işlerinde ona öğüt verir.",
        "Edep ve ilimden anlamadığı şeyleri ona anlatır.",
        "Bir hatasını görürse onu uyarır ve örter; unuttuğunda hatırlatır ve çalışmaya teşvik eder.",
        "Onu dışarıda bırakarak fısıldaşmak gibi kalbini kıracak şeyler yapmaz.",
    ]),
    "hq-7": ("Misafirin hakları", "Allah’a ve ahiret gününe iman eden misafirine ikram etsin.", [
        "Misafire ikram sabit bir haktır; Peygamber ﷺ buyurdu: “Allah’a ve ahiret gününe iman eden misafirine ikram etsin.”",
        "Misafirlik üç gündür; ötesi sadakadır; misafir ev sahibini bıktıracak kadar kalmamalıdır.",
        "Evlerindeki en iyi şeyi ona ikram etmeleri, yemeğini çabuk hazırlamaları ve namaz vakitlerini gözetmeleri gerekir.",
        "Yanında su olmadan yemek ikram etme.",
    ]),
    "hq-8": ("Misafire karşı hoş olmayanlar", "Misafiri yalnız ve rahatsız bırakmayız.", [
        "Misafirlerinin bazısına verip bazısına verme, bazısıyla fısıldaşıp diğerlerini dışlama.",
        "Misafirlerinin yanında çok susma ki onları sıkıntıya sokmayasın.",
        "Misafire iş yaptırma; bu mertliğe yakışmaz.",
        "Misafirlerinin yanında kimseye kızma ki senden rahatsız olmasınlar.",
    ]),
    "zk-1": ("Zekât", "Maldan belirli kişilere verilen bir hak.", [
        "Zekât tamamen malî bir ibadettir.",
        "Allah her Müslümanın malında, mal belirli bir miktara ulaşınca belirli sınıflara verilmek üzere bir hak farz kılmıştır.",
    ]),
    "zk-2": ("Zekâtın farz olduğu mallar", "Altın, gümüş, tahıl, hayvanlar ve ticaret.", [
        "Zekât altın ve gümüşte farzdır.",
        "Hurma, kuru üzüm ve buğday, arpa, darı gibi gıda olarak tüketilen tahıllarda.",
        "Deve, sığır ve koyunda.",
        "Ve ticaret mallarında.",
    ]),
    "zk-3": ("Zekâtın farz olmadığı mallar", "Eşek, at ve bakırda zekât yoktur; ticaret için olursa başka.", [
        "Eşekte, atta, bakırda ve altın ile gümüş dışındaki madenlerde zekât yoktur.",
        "Ancak ticaret için edinilmişse ticaret zekâtı gerekir.",
    ]),
    "zk-4": ("Altının zekâtı", "Nisabı yirmi dinardır, zekâtı yarım dinardır.", [
        "Altın yirmi dinar veya fazlasına ulaşır ve üzerinden bir yıl geçerse zekât farzdır.",
        "Ondan yarım dinar verilir.",
        "Her dört dinar fazlalık için dinarın onda biri verilir ve bu böyle devam eder.",
        "Altın nisaba ulaşmazsa sahip olduğu gümüşle birleştirilir.",
    ]),
    "zk-5": ("Gümüşün zekâtı", "Nisabı iki yüz dirhemdir, zekâtı beş dirhemdir.", [
        "Gümüş iki yüz dirheme ulaşır ve üzerinden bir yıl geçerse zekât farzdır.",
        "Ondan beş dirhem verilir.",
        "Her kırk dirhem fazlalık için bir dirhem verilir ve bu böyle devam eder.",
        "Altın ve gümüş birleştirilir ve tek bir zekât verilir.",
    ]),
    "zk-6": ("Tahıl ve meyvelerin zekâtı", "Hasatta onda bir veya yirmide bir.", [
        "Hurma, kuru üzüm ve bütün tahıllar üç yüz sâ‘a ulaşınca farzdır.",
        "Yıl şartı yoktur; hasat edilince zekâtı verilir.",
        "Yağmur, nehir veya pınarla sulanıyor ya da sulama gerektirmiyorsa onda bir verilir.",
        "Kuyudan çekilerek veya taşınarak sulanıyorsa yirmide bir verilir.",
    ]),
    "zk-7": ("Devenin zekâtı", "Nisabı beş devedir.", [
        "Beş otlak devesine sahip olup üzerinden bir yıl geçerse zekât farzdır.",
        "Beşte bir koyun, onda iki, on beşte üç, yirmide dört koyun.",
        "Yirmi beşte bir yaşında dişi deve; otuz altıda iki yaşında; kırk altıda üç yaşında; altmış birde dört yaşında dişi deve.",
        "Sonra her kırkta iki yaşında bir dişi deve, her ellide üç yaşında bir dişi deve.",
    ]),
    "zk-8": ("Sığırın zekâtı", "Hükmü devenin hükmü gibidir.", [
        "Sığırın zekât hükmü deve gibidir; yalnızca adlandırmada farklıdır.",
        "Nisap ve verilecek miktar aynıdır.",
    ]),
    "zk-9": ("Koyunun zekâtı", "Nisabı kırk koyundur.", [
        "Kırka ulaşır ve bir yıl geçerse farzdır.",
        "Kırktan yüz yirmiye kadar bir koyun; bir fazla olursa iki yüze kadar iki koyun.",
        "Bir fazla olursa üç yüz doksan dokuza kadar üç koyun.",
        "Dört yüze ulaşınca her yüz koyunda bir koyun.",
    ]),
    "zk-10": ("Ticaret malının zekâtı", "Ticaret malı değerinin kırkta biri.", [
        "Ticaret malının değeri altın veya gümüş nisabına ulaşır ve bir yıl geçerse zekât farzdır.",
        "Altın ve gümüş zekâtı gibi değerinin kırkta biri (%2,5) verilir.",
    ]),
    "zk-11": ("Fıtır sadakası ve vakti", "Bayram namazından önce kişi başı bir sâ‘ yiyecek.", [
        "Fıtır sadakası zengin Müslümana farzdır.",
        "Kişi başına bir sâ‘ buğday, darı, hurma veya kuru üzümdür.",
        "Kendisi, çocuğu ve nafakasını üstlendiği herkes için verir; eş hakkında iki görüş vardır.",
        "Vakti Ramazan bayramı günü fecirden namazgâha çıkışa kadardır; fakirlere ve yoksullara verilir.",
    ]),
    "zk-12": ("Sekiz sınıf", "Zekâta kimler hak sahibidir?", [
        "Fakirler: bir yıllık azığı olmayanlar; ve miskinler: durumu onlardan daha kötü olanlar.",
        "Zekât toplamakla görevliler ve kalpleri İslam’a ısındırılacaklar.",
        "Kölelikten kurtulmak isteyenler ve günah ya da israf olmayan bir sebeple borçlananlar.",
        "Allah yolunda olanlar ve ailesinden parasız kalmış yolcu.",
    ]),
    "hj-1": ("Hac ve farz oluşunun şartları", "Gücü yetene ömürde bir kez.", [
        "Hac, ergen muvahhide canı ve malıyla gereken bir ibadettir.",
        "Sağlıklı olur, gidiş dönüş azığı bulunur ve ailesine yetecek nafaka bırakırsa farzdır.",
        "Yol güvenli olur ve bineği bulunur ya da zorlanmadan yürüyebilirse.",
        "Ömürde bir kez farzdır; fazlası nafiledir.",
    ]),
    "hj-2": ("Hacca niyet edenin yapacakları", "Yolculuktan önce borçları öder, akrabayı ziyaret ederiz.", [
        "Borçlarını öde, yeminlerinin keffaretini ver ve adağını yerine getir.",
        "Akrabalarını ziyaret et ve sana gücenen komşunun gönlünü al.",
        "Azığını bol tut ki gönlün geniş olsun.",
        "Evinde iki rekât namaz kıl, niyetini halis kıl, sonra ailenle vedalaş.",
    ]),
    "hj-3": ("Hacca çıkış", "Bineğe binerken yolculuk duası.", [
        "Bineğine binince üç kez tekbir getir ve de ki: “Bunu bizim hizmetimize veren Allah’ı tenzih ederiz; yoksa biz buna güç yetiremezdik; şüphesiz biz Rabbimize döneceğiz.”",
        "“Allah’ım, yolculukta arkadaş sensin; aile ve malda vekil de sensin.”",
        "Yükseğe çıkınca tekbir getir, inince tesbih et.",
    ]),
    "hj-4": ("Mîkat ve haccın vakti", "Mîkatı ancak ihramlı geçeriz.", [
        "Hacı mîkata varınca onu ancak ihramlı olarak geçmelidir.",
        "Hac ayları: Şevval, Zilkade ve Zilhiccenin ilk on günüdür.",
        "Hac aylarından önce hac için ihrama giren kimseye bu hac yerine geçmez, umre olur.",
    ]),
    "hj-5": ("Umre", "İhram, sonra tavaf, sonra sa‘y.", [
        "Umre, hac için ihrama girer gibi ihrama girmek, sonra Beyt’e gelip tavaf ve sa‘y yapmaktır.",
        "Her ayda yapılabilir.",
        "İhrama girerken umre olduğuna niyet etmek gerekir.",
    ]),
    "hj-6": ("İhrama girişin şekli", "Gusül, sonra iki parça elbise, sonra iki rekât.", [
        "İhramın başında gusleder; abdestin yeterli olduğu da söylenmiştir.",
        "İki parça elbise giyer; yeni veya yıkanmış olması müstehaptır.",
        "İhram için iki rekât namaz kılar.",
    ]),
    "hj-7": ("Telbiye", "Lebbeyk Allahümme lebbeyk.", [
        "Niyet ettikten sonra der ki: “Buyur Allah’ım buyur; buyur, senin ortağın yoktur, buyur; hamd, nimet ve mülk senindir; senin ortağın yoktur, buyur.”",
        "Bineği yürüdükçe, yükseğe çıktıkça veya vadiye indikçe telbiye getirmesi müstehaptır.",
        "Sesini yükseltmesi müstehaptır; ne kadar çok olursa o kadar faziletlidir.",
    ]),
    "hj-8": ("İhramlıya caiz olmayanlar", "Koku yok, av yok, saç ve tırnak kesmek yok.", [
        "İhramlı dikişli elbise giyemez; zaruret dışında başını ve yüzünü örtemez.",
        "Kadın başını örter, yüzünü açar ve dikişli elbise giyebilir.",
        "İhramlı güzel koku kullanamaz ve avlanamaz.",
        "İhramlı olduğu sürece saçından ve tırnaklarından bir şey almaz.",
    ]),
    "hj-9": ("Mekke’ye giriş", "Telbiye getirerek gireriz.", [
        "Mekke’ye gelince telbiye getirerek girer ve mescidin kapısında durana kadar telbiyeyi kesmez.",
        "Kâbe’yi görünce der ki: “Allahu ekber (üç kez); Allah’ım sen Rabbimsin, ben kulunum; bu ev senin evindir; rızanı istemeye geldim.”",
        "Girince der ki: “Allah’ım, sen Selâm’sın, esenlik sendendir; Rabbimiz bizi esenlikle yaşat ve bizi esenlik yurduna koy.”",
    ]),
    "hj-10": ("Tavaf", "Kâbe’nin etrafında yedi şavt.", [
        "Hacerü’l-Esved’den başlar ve Beyt’i soluna alır.",
        "Tavafta çokça şöyle der: “Sübhânallah, velhamdülillah, ve lâ ilâhe illallah, vallahu ekber, ve lâ havle ve lâ kuvvete illâ billâhil aliyyil azîm.”",
        "Rükn-i Yemânî’de der ki: “Rabbimiz, bize dünyada da iyilik ver, ahirette de iyilik ver ve bizi ateş azabından koru”; kimseye eziyet etmez.",
        "Yedi şavtı tamamlar, sonra Makâm-ı İbrahim’in arkasında veya mümkün olan yerde iki rekât namaz kılar.",
    ]),
    "hj-11": ("Zemzem", "Zemzem suyundan içer ve dua ederiz.", [
        "Zemzem’e gelir, suyundan içer ve başına döker.",
        "Der ki: “Allah’ım, senden tam bir iman, sağlam bir yakîn, dosdoğru bir din, salih amel, ilim, helal, temiz ve geniş rızık ve her hastalıktan şifa isterim.”",
    ]),
    "hj-12": ("Safa ile Merve arasında sa‘y", "Safa’dan başlayıp Merve’de biten yedi şavt.", [
        "Beyt’e yöneleceği kadar Safa’ya çıkar, tekbir ve tehlil getirir ve dua eder.",
        "Merve’ye doğru iner; iki işaret arasında hızlı yürür ve der ki: “Rabbim, bağışla, merhamet et ve bildiklerini affet.”",
        "Merve’ye gelince Beyt’e yöneleceği kadar çıkar ve Safa’daki gibi dua eder.",
        "Yedi şavtı tamamlar: Safa’dan başlar, Merve’de bitirir.",
    ]),
    "hj-13": ("Umreden çıkış", "Sa‘yden sonra tıraş olmak.", [
        "Sa‘yi bitirince Merve’den iner ve başını tıraş eder; umreden çıkmış olur.",
        "Harem’de avlanmak dışında her şey ona helal olur; Harem’de av herkese haramdır.",
        "Bu temettu hacceden içindir; kıran hacceden, hac bitene kadar ihramdan çıkmaz.",
    ]),
    "hj-14": ("Hac için ihram ve Mina’ya çıkış", "Terviye günü: Zilhiccenin sekizi.", [
        "Terviye akşamı, yani Zilhiccenin sekizinde hac için ihrama girer.",
        "Telbiye getirir: “Hac için buyur; onu tamamlamak ve ulaştırmak sana aittir, ey Allah.”",
        "Sonra Mina’ya gider, orada beş vakit namaz kılar, geceyi insanlarla geçirir ve Allah’ı çokça anar.",
    ]),
    "hj-15": ("Arafat", "Arafat’ta vakfe haccın rüknüdür.", [
        "Güneş doğduktan sonra telbiye getirerek Arafat’a gider.",
        "Öğle namazını insanlarla kılar ve güneş batana kadar duada gayret eder.",
        "Çokça şöyle der: “Allah’tan başka ilah yoktur, O tektir, ortağı yoktur; mülk O’nundur, hamd O’nadır; diriltir ve öldürür; O ölmeyen diridir; hayır O’nun elindedir ve O her şeye kadirdir.”",
    ]),
    "hj-16": ("Arafat’tan ayrılış ve Meş‘ar-i Haram", "Müzdelife’de gece ve taş toplamak.", [
        "Sonra Arafat’tan Meş‘ar-i Haram’a (Cem‘) doğru ayrılır.",
        "Akşam ve yatsıyı birlikte kılar ve geceyi insanlarla geçirir.",
        "Oradan yetmiş küçük taş hazırlar ve yıkar.",
        "Fecir doğunca namaz kılar, Meş‘ar-i Haram’da durup dua eder, sonra güneş doğmadan ayrılır.",
    ]),
    "hj-17": ("Şeytan taşlama", "Her biriyle bir tekbir, yedi taş.", [
        "Akabe cemresine gelince telbiyeyi keser.",
        "Sonra ona yedi taş atar, her biriyle tekbir getirir ve her tekbirden sonra “Hamd Allah’a mahsustur” der.",
        "Teşrik günlerinde zevalden sonra üç cemreyi taşlar: ilki, sonra ortadaki, sonra Akabe cemresi.",
    ]),
    "hj-18": ("Kurban, tıraş ve haccın rükünleri", "Haccın rükünleri: ihram, Arafat vakfesi ve Beyt’i ziyaret.", [
        "Sonra kurban keser ve tıraş olur; der ki: “Allah’ım, saçımı kısaltmamı bereketli kıl ve günahımı bağışla.”",
        "Tıraştan sonra Beyt’i ziyaret edene kadar kadınlar ve av dışında her şey ona helal olur.",
        "Haccın üzerinde ittifak edilen rükünleri: ihram, Arafat vakfesi ve Beyt’i ziyarettir.",
    ]),
    "hj-19": ("Beyt’i ziyaret", "Umredeki gibi tavaf ve sa‘y.", [
        "Ziyaretinde umrede yaptığı her şeyi yapar: tavaf, sa‘y ve dua.",
        "Sonra Mina’ya döner, Mekke’de gecelemez ve teşrik günlerini orada geçirir.",
    ]),
    "hj-20": ("Veda tavafı", "Beyt ile son buluşma.", [
        "Mekke’den çıkmak isteyince Beyt’e gelir, yedi şavt tavaf eder, sonra iki rekât namaz kılar.",
        "Sonra Zemzem’e gelip ondan içer, sonra Allah’ın gönlüne açtığı dualarla dua eder.",
        "Dualarından: “Allah’ım, bunu Beyt-i Harâm’ınla son buluşmam kılma.”",
        "Sonra çıkar; vedadan sonra alışveriş yapmaz.",
    ]),
    "jh-1": ("Cihadın anlamı ve fazileti", "Allah yolunda can ve malı feda etmek.", [
        "Cihad, can ve malla meşru kılınmış bir ibadettir.",
        "Allah Teâlâ buyurdu: “Müminler ancak Allah’a ve Resulüne iman eden, sonra şüpheye düşmeyen ve Allah yolunda mallarıyla ve canlarıyla cihad edenlerdir; işte onlar sadıklardır.” [Hucurât: 15]",
        "Allah, önceki ümmetlerin salihlerini sebat, sabır ve cihadla övmüştür.",
    ]),
    "jh-2": ("Cihadın kısımları", "Nefis ve heva ile mücadele de buna dahildir.", [
        "Farz-ı ayn: yurda ve cemaate saldıran düşmanı püskürtmek gibi.",
        "Farz-ı kifaye: sınırları korumak ve İslam davetini himaye etmek gibi.",
        "Cihad, dini öğrenip onunla amel etmek ve ilmi yaymak için nefisle mücadeleye, şeytan ve hevaya karşı mücadeleye de denir. (Ebû İshak’ın açıklamasından)",
    ]),
    "jh-3": ("Cihadın hikmeti", "Zulmü defetmek ve hak davetini korumak.", [
        "Cihad, İslam’ı üstün kılmak ve korumak, saldırganlığı bastırmak ve batılı yok etmek için meşru kılındı.",
        "Yeryüzündeki zulmü ve fesadı defetmek ve hak davetini korumak için meşru kılındı; İslam’ın getirdiği rahmete ve Allah’ın emrettiği adalete aykırı değildir.",
        "Bâğîler, imama zulmen isyan eden tevhid ehlinden bir topluluktur; imam, hüccet ulaştıktan sonra onlar itaate dönene kadar onlarla savaşır ve malları ganimet alınmaz.",
    ]),
    "kh-1": ("Allah’ı inkâr (şirk)", "Terk edilmesi gereken en büyük şey.", [
        "Terk edilmesi gereken ilk şey Allah’ı inkâr etmektir; bu da Allah’a ortak koşmaktır.",
        "Allah’ın kitaplarından birini veya peygamberlerinden birini yalanlamak gibi.",
        "Ya da Allah’ın varlığından şüphe etmek, Allah’ı ve Resulü Muhammed ﷺ’i tanımamak.",
        "Ya da ölümü, dirilişi, hesabı, cenneti veya cehennemi inkâr etmek ya da Allah’ın açık hükümlerinden birini inkâr etmek.",
    ]),
    "kh-2": ("Nimete nankörlük (küfrân-ı nimet)", "Büyük günahlar işlemek.", [
        "Nimete nankörlük, açık veya gizli büyük günahlardan birini işlemektir.",
        "Gizli günahlar: ucub (kendini beğenmişlik), kibir, haset, riya ve bunlardan doğan kötü huylar.",
    ]),
    "kh-3": ("Ucub ve tedavisi", "Her nimet Allah’ın lütfundandır.", [
        "Ucub, insanın içinde bulunduğu nimeti büyük görüp onu verene bakmadan kendini ona layık görmesidir.",
        "Sebebi: güzellik, ilim, cesaret veya cömertlik gibi görünüşte, sıfatlarda veya malda bir üstünlüğe sahip olmak.",
        "Tedavisi: kendisine verileni yalnızca Allah’ın lütfettiğini ve nefsinin bunda hiçbir payı olmadığını bilmek.",
    ]),
    "kh-4": ("Kibir ve tedavisi", "Kimseyi küçük görmez, hakkı kabul ederiz.", [
        "Kibir, insanları küçük görmek ve hakkı reddetmektir.",
        "Sebebi: kendini büyük ve ayrıcalıklı görmesi.",
        "Tedavisi: yaratıldığı asla ve döneceği sona bakmak.",
    ]),
    "kh-5": ("Riya ve tedavisi", "Yalnızca Allah için amel ederiz.", [
        "Riya, insanlar için amel etmektir; amelinde Allah’tan başkasını gözeten riyakârdır.",
        "İnsanları bir kenara bırakıp yalnızca Rabbinin rızasını gözetmelidir.",
        "Tedavisi: insanların ona fayda veya zarar veremeyeceğini, bunların hepsini yapanın bir ve tek olan Allah olduğunu bilmek.",
    ]),
    "kh-6": ("Haset ve gıpta", "Aynı hayrı başkasından gitmesini istemeden kendimiz için dileriz.", [
        "Haset, Allah’ın başkasına verdiği nimetin yok olmasını istemektir; büyük bir günahtır.",
        "Onu terk etmeli ve bunun Allah’ın dilediğine verdiği lütfu olduğunu bilmelidir.",
        "Tedavisi: hasedinin başkasının nimetini yok etmediğini, aksine dünyada ve ahirette yalnızca kendisine zarar verdiğini bilmek.",
        "Başkasınınki gibi bir nimet dilemek caizdir; buna “gıpta” denir.",
    ]),
    "kh-7": ("Açık büyük günahlar", "Allah’ın haram kıldığı her şeyden uzak dururuz.", [
        "Açık büyük günahlardan: faiz, leş, kan ve domuz eti yemek ve öldürülmesi haram olan cana kıymak.",
        "Yol kesmek, kullara zulmetmek, hırsızlık, Müslümanlara eziyet edip onları korkutmak ve yeryüzünde fesat çıkarmak.",
        "Batılı desteklemek, hakka direnmek ve şarap ile bütün sarhoş edicileri içmek.",
        "Ve Kur’an, Sünnet ve ümmetin icmaıyla haram kılınan diğer fiiller.",
    ]),
}

QUIZ = {
    "intro": [
        ("Veli çocuğa namazı ne zaman öğretir?", ["Üç yaşında", "Yedi yaşında", "On beş yaşında"], "Veli, çocuğa yedi yaşında namazı öğretmekle emrolunmuştur."),
        ("Veli çocuğa başka ne öğretir?", ["Kur’an-ı Kerim ve edep", "Ergenlikten önce hiçbir şey", "Yalnızca oruç"], "Kur’an’ı, edebi ve çocuğun anlayacağı hikmetleri öğretir."),
    ],
    "aqeedah": [
        ("Kitaba göre resullerin sayısı kaçtır?", ["Yüz dört", "Üç yüz on üç", "Yirmi beş"], "Allah’ın gönderdiği resullerin sayısı üç yüz on üçtür."),
        ("İlk resul kimdir?", ["Nuh aleyhisselam", "İbrahim aleyhisselam", "Âdem aleyhisselam"], "İlki Âdem aleyhisselamdır; çocuklarına gönderilmiştir."),
        ("Zebur kime indirildi?", ["Davud aleyhisselam", "Musa aleyhisselam", "İsa aleyhisselam"], "Zebur Davud’a, Tevrat Musa’ya, İncil İsa’ya indirildi."),
        ("Allah’ın bize verdiği en büyük nimet nedir?", ["Sağlık", "İslam nimeti", "Mal"], "Allah’ın nimetlerinden: varlık, sağlık ve en büyüğü İslam nimeti."),
    ],
    "salah": [
        ("Akşam namazının farzı kaç rekâttır?", ["İki", "Üç", "Dört"], "Akşam namazının farzı üç rekâttır."),
        ("Rükûda ne deriz?", ["Sübhâne rabbiyel-a‘lâ", "Sübhâne rabbiyel-azîm", "Rabbenâ ve lekel-hamd"], "Rükûda üç kez “Sübhâne rabbiyel-azîm” denir."),
        ("Secde kaç uzuv üzerine yapılır?", ["Beş", "Yedi", "Üç"], "Secde yedi uzuv üzerine yapılır: alın, eller, dizler ve ayaklar."),
        ("Yolcu öğle namazını nasıl kılar?", ["Dört rekât", "İki rekât kısaltarak", "Kılmaz"], "Yolcu öğle, ikindi ve yatsıyı ikişer rekât kılar."),
        ("Bayram namazında namazın kendi tekbirleri dışında kaç tekbir vardır?", ["Yedi", "On üç", "Dört"], "Namazın tekbirleri dışında on üç tekbir vardır."),
    ],
    "taharah": [
        ("Abdestte yüz kaç kez yıkanır?", ["Bir kez", "Üç kez", "Beş kez"], "Yüz üç kez yıkanır."),
        ("Tuvalete hangi ayakla gireriz?", ["Sağ", "Sol", "Fark etmez"], "Sol ayakla girilir, sağ ayakla çıkılır."),
        ("Su bulamazsak ne yaparız?", ["Namazı bırakırız", "Temiz toprakla teyemmüm ederiz", "Namazı yarına bırakırız"], "Su yoksa temiz toprakla teyemmüm edilir."),
        ("Namazda yöneldiğimiz kıble nedir?", ["Mescid-i Aksâ", "Yüce Kâbe", "Herhangi bir yön"], "Kıble yüce Kâbe’dir; namaz ancak ona yönelmekle tamam olur."),
    ],
    "janaiz": [
        ("Cenaze namazında kaç tekbir vardır?", ["Üç", "Dört", "Beş"], "Cenaze namazı dört tekbirlidir."),
        ("Ölü kabre hangi yanı üzerine konur?", ["Sağ yanı, kıbleye dönük", "Sol yanı", "Sırtüstü"], "Sağ yanı üzerine, kıbleye dönük konur."),
    ],
    "sawm": [
        ("Ramazan orucunun niyeti ne zaman yapılır?", ["Geceden", "Öğleden sonra", "Niyet gerekmez"], "Geceden niyet edilir; etmeyenin orucu yoktur."),
        ("Bayram günü oruç tutmanın hükmü nedir?", ["Müstehap", "Haram", "Farz"], "İki bayram günü oruç tutmak haramdır."),
        ("Eyyâm-ı bîd hangi günlerdir?", ["1, 2 ve 3", "13, 14 ve 15", "Son üç gün"], "Eyyâm-ı bîd ayın 13, 14 ve 15. günleridir."),
    ],
    "huquq": [
        ("Babamıza nasıl sesleniriz?", ["Adıyla", "“Babacığım” deriz", "Seslenmeyiz"], "Babaya adıyla seslenmek saygısızlıktır; “babacığım” denir."),
        ("Misafirlik kaç gündür?", ["Bir gün", "Üç gün", "Bir hafta"], "Misafirlik üç gündür; ötesi sadakadır."),
        ("Akrabayı ziyaretin en güzeli nedir?", ["Hediye göndermek", "Selam göndermek", "Hiçbir şey"], "En güzeli hediye, en zayıfı selam göndermektir."),
    ],
    "zakah": [
        ("Gümüşün nisabı nedir?", ["Yüz dirhem", "İki yüz dirhem", "Kırk dirhem"], "Gümüş iki yüz dirheme ulaşınca zekât farz olur."),
        ("Fıtır sadakası ne zaman verilir?", ["Ramazan’dan önce", "Bayram günü namaza çıkmadan önce", "Bayramdan bir ay sonra"], "Vakti bayram günü fecirden namaza çıkışa kadardır."),
        ("Zekâta hak sahibi kaç sınıf vardır?", ["Dört", "Sekiz", "On"], "Zekâta hak sahibi sınıflar sekizdir."),
    ],
    "hajj": [
        ("Hac ömürde kaç kez farzdır?", ["Her yıl", "Bir kez", "İki kez"], "Hac ömürde bir kez farzdır; fazlası nafiledir."),
        ("Tavaf kaç şavttır?", ["Beş", "Yedi", "Üç"], "Tavaf yedi şavttır."),
        ("Sa‘y nereden başlar?", ["Merve’den", "Safa’dan", "Zemzem’den"], "Safa’dan başlar, Merve’de biter."),
    ],
    "jihad": [
        ("Cihad ne ile meşru kılınmıştır?", ["Can ve malla", "Yalnızca malla", "Yalnızca sözle"], "Cihad can ve malla meşru kılınmış bir ibadettir."),
    ],
    "khatimah": [
        ("Kibir nedir?", ["İnsanları küçük görmek ve hakkı reddetmek", "İnsanlar için iyilik istemek", "Allah için amel etmek"], "Kibir, insanları küçük görmek ve hakkı reddetmektir."),
        ("Haset ile gıpta arasındaki fark nedir?", ["Fark yoktur", "Gıpta, başkasındaki nimetin benzerini ondan gitmesini istemeden dilemektir", "Gıpta haram, haset caizdir"], "Başkasınınki gibi bir nimet dilemek caizdir ve buna gıpta denir."),
        ("Riyanın tedavisi nedir?", ["İnsanların fayda ve zarar veremeyeceğini bilmek", "İnsanların önünde daha çok amel etmek", "İyilikleri bırakmak"], "Tedavisi, insanların fayda veya zarar veremeyeceğini, bunun yalnızca Allah’tan olduğunu bilmektir."),
    ],
}
