"""UI strings for all languages -> Assets/Data/UIStrings.json  ({key: {lang: text}}).
Placeholders: {0}, {1} …  (replaced in Swift by L10n.t)."""
import json, os

LANGS = ["ar", "en", "fa", "tr", "hi", "bn"]

S = {
    "app.name": ["ثقافة إسلامية", "Islamic Culture", "فرهنگ اسلامی", "İslami Kültür", "इस्लामी संस्कृति", "ইসলামী সংস্কৃতি"],
    "home.greeting": ["السلام عليكم 👋", "Assalamu alaikum 👋", "السلام علیکم 👋", "Esselâmu aleyküm 👋", "अस्सलामु अलैकुम 👋", "আসসালামু আলাইকুম 👋"],
    "home.myProgress": ["تقدّمي", "My progress", "پیشرفت من", "İlerlemem", "मेरी प्रगति", "আমার অগ্রগতি"],
    "home.progressA11y": ["تقدّمك وعن الكتاب", "Your progress and about the book", "پیشرفت شما و درباره کتاب", "İlerlemen ve kitap hakkında", "आपकी प्रगति और किताब के बारे में", "তোমার অগ্রগতি ও বই সম্পর্কে"],
    "home.lessons.title": ["رحلات تفاعلية", "Interactive journeys", "سفرهای تعاملی", "Etkileşimli yolculuklar", "इंटरैक्टिव सफ़र", "ইন্টারঅ্যাকটিভ যাত্রা"],
    "home.lessons.subtitle": ["تعلّم خطوة بخطوة بالبطاقات", "Learn step by step with cards", "با کارت‌ها قدم‌به‌قدم بیاموز", "Kartlarla adım adım öğren", "कार्ड के साथ क़दम-ब-क़दम सीखें", "কার্ডে ধাপে ধাপে শেখো"],
    "home.chapters.title": ["أقسام الكتاب", "Book chapters", "بخش‌های کتاب", "Kitabın bölümleri", "किताब के अध्याय", "বইয়ের অধ্যায়সমূহ"],
    "home.chapters.subtitle": ["{0} مسألة في {1} قسمًا", "{0} topics in {1} chapters", "{0} مسئله در {1} بخش", "{1} bölümde {0} mesele", "{1} अध्यायों में {0} मसले", "{1}টি অধ্যায়ে {0}টি মাসআলা"],
    "search.placeholder": ["ابحث عن مسألة… (الوضوء، الزكاة، الجار)", "Search a topic… (wudu, zakat, neighbour)", "جستجوی مسئله… (وضو، زکات، همسایه)", "Mesele ara… (abdest, zekât, komşu)", "मसला खोजें… (वुज़ू, ज़कात, पड़ोसी)", "মাসআলা খোঁজো… (অজু, যাকাত, প্রতিবেশী)"],
    "search.clear": ["مسح البحث", "Clear search", "پاک کردن جستجو", "Aramayı temizle", "खोज साफ़ करें", "খোঁজ মুছে ফেলো"],
    "search.title": ["نتائج البحث", "Search results", "نتایج جستجو", "Arama sonuçları", "खोज परिणाम", "খোঁজের ফলাফল"],
    "search.count": ["{0} نتيجة", "{0} results", "{0} نتیجه", "{0} sonuç", "{0} परिणाम", "{0}টি ফলাফল"],
    "search.empty": ["لم نجد مسألة بهذا الاسم، جرّب كلمة أخرى 🌱", "No topic found — try another word 🌱", "مسئله‌ای با این نام پیدا نشد، کلمهٔ دیگری امتحان کن 🌱", "Bu adla mesele bulunamadı, başka bir kelime dene 🌱", "इस नाम का कोई मसला नहीं मिला, दूसरा शब्द आज़माएँ 🌱", "এই নামে কোনো মাসআলা পাওয়া যায়নি, অন্য শব্দ চেষ্টা করো 🌱"],
    "chapter.masailCount": ["{0} مسألة", "{0} topics", "{0} مسئله", "{0} mesele", "{0} मसले", "{0}টি মাসআলা"],
    "chapter.openHint": ["افتح القسم", "Open chapter", "باز کردن بخش", "Bölümü aç", "अध्याय खोलें", "অধ্যায় খোলো"],
    "chapter.learnInteractive": ["تعلّم بالتفاعل", "Learn by doing", "یادگیری تعاملی", "Yaparak öğren", "करके सीखें", "করে করে শেখো"],
    "chapter.masail": ["المسائل", "Topics", "مسائل", "Meseleler", "मसले", "মাসআলাসমূহ"],
    "chapter.masailSubtitle": ["اختر مسألة لتتعلّمها", "Choose a topic to learn", "یک مسئله برای یادگیری انتخاب کن", "Öğrenmek için bir mesele seç", "सीखने के लिए एक मसला चुनें", "শেখার জন্য একটি মাসআলা বেছে নাও"],
    "lesson.stepsCount": ["{0} خطوة", "{0} steps", "{0} مرحله", "{0} adım", "{0} क़दम", "{0}টি ধাপ"],
    "lesson.startHint": ["ابدأ الدرس التفاعلي", "Start the interactive lesson", "شروع درس تعاملی", "Etkileşimli dersi başlat", "इंटरैक्टिव पाठ शुरू करें", "ইন্টারঅ্যাকটিভ পাঠ শুরু করো"],
    "lesson.close": ["إغلاق الدرس", "Close lesson", "بستن درس", "Dersi kapat", "पाठ बंद करें", "পাঠ বন্ধ করো"],
    "lesson.swipeHintRTL": ["اسحب البطاقة إلى اليمين للخطوة التالية 👉", "Swipe the card right for the next step 👉", "کارت را به راست بکش تا مرحلهٔ بعد بیاید 👉", "Sonraki adım için kartı sağa kaydır 👉", "अगले क़दम के लिए कार्ड को दाईं ओर खींचें 👉", "পরের ধাপের জন্য কার্ডটি ডানে সরাও 👉"],
    "lesson.swipeHintLTR": ["اسحب البطاقة إلى اليسار للخطوة التالية 👈", "Swipe the card left for the next step 👈", "کارت را به چپ بکش تا مرحلهٔ بعد بیاید 👈", "Sonraki adım için kartı sola kaydır 👈", "अगले क़दम के लिए कार्ड को बाईं ओर खींचें 👈", "পরের ধাপের জন্য কার্ডটি বাঁয়ে সরাও 👈"],
    "lesson.previous": ["السابق", "Back", "قبلی", "Geri", "पिछला", "আগের"],
    "lesson.next": ["التالي", "Next", "بعدی", "İleri", "अगला", "পরের"],
    "lesson.finish": ["أتممتُ الدرس", "I finished!", "درس را تمام کردم", "Dersi bitirdim", "पाठ पूरा किया", "পাঠ শেষ করেছি"],
    "lesson.nextA11y": ["الخطوة التالية", "Next step", "مرحلهٔ بعد", "Sonraki adım", "अगला क़दम", "পরের ধাপ"],
    "lesson.previousA11y": ["الخطوة السابقة", "Previous step", "مرحلهٔ قبل", "Önceki adım", "पिछला क़दम", "আগের ধাপ"],
    "lesson.timeline": ["خطوات الدرس", "Lesson steps", "مراحل درس", "Dersin adımları", "पाठ के क़दम", "পাঠের ধাপসমূহ"],
    "step.of": ["الخطوة {0} من {1}", "Step {0} of {1}", "مرحلهٔ {0} از {1}", "Adım {0} / {1}", "क़दम {0} / {1}", "ধাপ {0} / {1}"],
    "step.wellDone": ["أحسنت", "Well done", "آفرین", "Aferin", "शाबाश", "সাবাশ"],
    "step.fromBook": ["من الكتاب", "From the book", "از کتاب", "Kitaptan", "किताब से", "বই থেকে"],
    "step.listen": ["استمع للخطوة", "Listen to this step", "به این مرحله گوش کن", "Bu adımı dinle", "यह क़दम सुनें", "এই ধাপটি শোনো"],
    "repeat.done": ["رائع! أكملت {0} مرات 🎉", "Great! You did it {0} times 🎉", "عالی! {0} بار انجام دادی 🎉", "Harika! {0} kez yaptın 🎉", "बहुत बढ़िया! {0} बार पूरा किया 🎉", "দারুণ! {0} বার সম্পন্ন করেছ 🎉"],
    "repeat.progress": ["المس القطرات: {0} من {1}", "Tap the drops: {0} of {1}", "قطره‌ها را لمس کن: {0} از {1}", "Damlalara dokun: {0} / {1}", "बूँदों को छुएँ: {0} / {1}", "ফোঁটাগুলো ছোঁও: {0} / {1}"],
    "repeat.time": ["المرة {0}", "Time {0}", "بار {0}", "{0}. kez", "{0}वीं बार", "{0} নম্বর বার"],
    "dua.say": ["قُل", "Say", "بگو", "Söyle", "कहें", "বলো"],
    "dua.meaning": ["المعنى", "Meaning", "معنا", "Anlamı", "अर्थ", "অর্থ"],
    "dua.listen": ["استمع للدعاء", "Listen to the supplication", "به دعا گوش کن", "Duayı dinle", "दुआ सुनें", "দোয়াটি শোনো"],
    "audio.stop": ["إيقاف القراءة", "Stop reading", "توقف خواندن", "Okumayı durdur", "पढ़ना रोकें", "পড়া থামাও"],
    "done.title": ["أحسنت! 🌟", "Well done! 🌟", "آفرین! 🌟", "Aferin! 🌟", "शाबाश! 🌟", "সাবাশ! 🌟"],
    "done.message": ["أتممت درس «{0}» خطوة بخطوة.\nبارك الله فيك!", "You completed “{0}” step by step.\nMay Allah bless you!", "درس «{0}» را قدم‌به‌قدم تمام کردی.\nخدا به تو برکت دهد!", "“{0}” dersini adım adım tamamladın.\nAllah seni mübarek kılsın!", "आपने “{0}” पाठ क़दम-ब-क़दम पूरा किया।\nअल्लाह आपको बरकत दे!", "তুমি “{0}” পাঠটি ধাপে ধাপে শেষ করেছ।\nআল্লাহ তোমাকে বরকত দিন!"],
    "done.restart": ["أعد الدرس", "Repeat lesson", "تکرار درس", "Dersi tekrarla", "पाठ दोहराएँ", "পাঠ আবার করো"],
    "done.back": ["العودة", "Home", "بازگشت", "Geri dön", "वापस", "ফিরে যাও"],
    "masala.startLesson": ["ابدأ درس «{0}» التفاعلي", "Start the “{0}” lesson", "شروع درس تعاملی «{0}»", "“{0}” dersini başlat", "“{0}” पाठ शुरू करें", "“{0}” পাঠ শুরু করো"],
    "masala.source": ["المصدر: {0} — ص {1}", "Source: {0} — p. {1}", "منبع: {0} — ص {1}", "Kaynak: {0} — s. {1}", "स्रोत: {0} — पृ. {1}", "সূত্র: {0} — পৃ. {1}"],
    "masala.listen": ["استمع للمسألة", "Listen to this topic", "به این مسئله گوش کن", "Bu meseleyi dinle", "यह मसला सुनें", "এই মাসআলাটি শোনো"],
    "masala.learned": ["تعلّمتُها ✓", "Learned ✓", "یاد گرفتم ✓", "Öğrendim ✓", "सीख लिया ✓", "শিখেছি ✓"],
    "masala.markLearned": ["تعلّمتُ هذه المسألة", "I learned this", "این مسئله را یاد گرفتم", "Bu meseleyi öğrendim", "मैंने यह मसला सीख लिया", "আমি এই মাসআলাটি শিখেছি"],
    "masala.hasLesson": ["فيها درس تفاعلي", "Has an interactive lesson", "درس تعاملی دارد", "Etkileşimli dersi var", "इसमें इंटरैक्टिव पाठ है", "এতে ইন্টারঅ্যাকটিভ পাঠ আছে"],
    "masala.learnedA11y": ["تم تعلّمها", "Learned", "یاد گرفته شد", "Öğrenildi", "सीखा गया", "শেখা হয়েছে"],
    "quiz.title": ["اختبر نفسك", "Test yourself", "خودت را بسنج", "Kendini dene", "ख़ुद को परखें", "নিজেকে যাচাই করো"],
    "quiz.best": ["أفضل نتيجة: {0} من {1}", "Best score: {0} of {1}", "بهترین نتیجه: {0} از {1}", "En iyi sonuç: {0} / {1}", "सबसे अच्छा स्कोर: {0} / {1}", "সেরা ফল: {0} / {1}"],
    "quiz.count": ["{0} أسئلة من القسم", "{0} questions from this chapter", "{0} پرسش از این بخش", "Bu bölümden {0} soru", "इस अध्याय से {0} सवाल", "এই অধ্যায় থেকে {0}টি প্রশ্ন"],
    "quiz.questionOf": ["سؤال {0} من {1}", "Question {0} of {1}", "پرسش {0} از {1}", "Soru {0} / {1}", "सवाल {0} / {1}", "প্রশ্ন {0} / {1}"],
    "quiz.correct": ["إجابة صحيحة! أحسنت 🌟", "Correct! Well done 🌟", "پاسخ درست! آفرین 🌟", "Doğru cevap! Aferin 🌟", "सही जवाब! शाबाश 🌟", "সঠিক উত্তর! সাবাশ 🌟"],
    "quiz.wrong": ["لا بأس، تعلّمنا شيئًا جديدًا", "No problem — we learned something new", "اشکالی ندارد، چیز تازه‌ای یاد گرفتیم", "Sorun değil, yeni bir şey öğrendik", "कोई बात नहीं, हमने कुछ नया सीखा", "সমস্যা নেই, আমরা নতুন কিছু শিখলাম"],
    "quiz.next": ["السؤال التالي", "Next question", "پرسش بعدی", "Sonraki soru", "अगला सवाल", "পরের প্রশ্ন"],
    "quiz.result": ["النتيجة", "See result", "نتیجه", "Sonuç", "परिणाम", "ফলাফল"],
    "quiz.perfect": ["ممتاز! علامة كاملة", "Excellent! Full marks", "عالی! نمرهٔ کامل", "Mükemmel! Tam puan", "बेहतरीन! पूरे अंक", "চমৎকার! পূর্ণ নম্বর"],
    "quiz.goodTry": ["أحسنت المحاولة!", "Good try!", "تلاش خوبی بود!", "Güzel deneme!", "अच्छी कोशिश!", "ভালো চেষ্টা!"],
    "quiz.score": ["نتيجتك: {0} من {1}", "Your score: {0} of {1}", "نتیجهٔ تو: {0} از {1}", "Puanın: {0} / {1}", "आपका स्कोर: {0} / {1}", "তোমার ফল: {0} / {1}"],
    "quiz.retry": ["أعد الاختبار", "Try again", "دوباره امتحان کن", "Tekrar dene", "फिर से करें", "আবার চেষ্টা করো"],
    "quiz.back": ["العودة للقسم", "Back to chapter", "بازگشت به بخش", "Bölüme dön", "अध्याय पर वापस", "অধ্যায়ে ফিরে যাও"],
    "about.title": ["عن التطبيق", "About", "دربارهٔ برنامه", "Hakkında", "ऐप के बारे में", "অ্যাপ সম্পর্কে"],
    "about.book": ["عن المحتوى", "About the content", "دربارهٔ محتوا", "İçerik hakkında", "सामग्री के बारे में", "বিষয়বস্তু সম্পর্কে"],
    "about.author": ["تأليف: {0}", "Author: {0}", "نویسنده: {0}", "Yazar: {0}", "लेखक: {0}", "লেখক: {0}"],
    "about.lessonsDone": ["الدروس المكتملة: {0} من {1}", "Lessons completed: {0} of {1}", "درس‌های کامل‌شده: {0} از {1}", "Tamamlanan dersler: {0} / {1}", "पूरे हुए पाठ: {0} / {1}", "সম্পন্ন পাঠ: {0} / {1}"],
    "about.reset": ["البدء من جديد", "Start over", "شروع دوباره", "Baştan başla", "फिर से शुरू करें", "নতুন করে শুরু করো"],
    "about.resetConfirm": ["هل تريد مسح كل التقدّم؟", "Erase all progress?", "همهٔ پیشرفت پاک شود؟", "Tüm ilerleme silinsin mi?", "क्या सारी प्रगति मिटा दें?", "সব অগ্রগতি মুছে ফেলবে?"],
    "about.resetAction": ["مسح التقدّم", "Erase progress", "پاک کردن پیشرفت", "İlerlemeyi sil", "प्रगति मिटाएँ", "অগ্রগতি মুছো"],
    "about.offline": ["يعمل التطبيق دون إنترنت بالكامل، وكل المحتوى مأخوذ من الكتاب مع تبسيط يسير للأطفال.", "The app works fully offline. All content comes from the book, lightly simplified for children.", "برنامه کاملاً بدون اینترنت کار می‌کند و همهٔ محتوا از کتاب گرفته شده و برای کودکان کمی ساده شده است.", "Uygulama tamamen internetsiz çalışır; tüm içerik kitaptan alınmış ve çocuklar için biraz sadeleştirilmiştir.", "ऐप पूरी तरह बिना इंटरनेट चलता है। सारी सामग्री किताब से ली गई है और बच्चों के लिए थोड़ी सरल की गई है।", "অ্যাপটি সম্পূর্ণ ইন্টারনেট ছাড়া চলে। সব বিষয়বস্তু বই থেকে নেওয়া, শিশুদের জন্য সামান্য সহজ করা।"],
    "about.translationNote": ["الترجمات لمعاني النصوص، والأدعية تبقى بالعربية كما وردت في الكتاب.", "Translations convey the meaning; supplications stay in Arabic as in the book.", "ترجمه‌ها معنای متن را می‌رسانند و دعاها همان‌طور که در کتاب آمده به عربی می‌مانند.", "Çeviriler anlamı aktarır; dualar kitaptaki gibi Arapça kalır.", "अनुवाद अर्थ बताते हैं; दुआएँ किताब की तरह अरबी में ही रहती हैं।", "অনুবাদে অর্থ তুলে ধরা হয়েছে; দোয়াগুলো বইয়ের মতো আরবিতেই রয়েছে।"],
    "common.cancel": ["إلغاء", "Cancel", "لغو", "İptal", "रद्द करें", "বাতিল"],
    "common.done": ["تم", "Done", "تمام", "Tamam", "हो गया", "সম্পন্ন"],
    "common.percent": ["{0}٪", "{0}%", "{0}٪", "%{0}", "{0}%", "{0}%"],
    "settings.title": ["الإعدادات", "Settings", "تنظیمات", "Ayarlar", "सेटिंग्स", "সেটিংস"],
    "settings.language": ["اللغة", "Language", "زبان", "Dil", "भाषा", "ভাষা"],
    "settings.audio": ["الصوت", "Audio", "صدا", "Ses", "आवाज़", "অডিও"],
    "settings.autoNarrate": ["قراءة كل خطوة تلقائيًا", "Read each step aloud automatically", "خواندن خودکار هر مرحله", "Her adımı otomatik oku", "हर क़दम अपने आप पढ़ें", "প্রতিটি ধাপ স্বয়ংক্রিয়ভাবে পড়ো"],
    "settings.autoNarrateFooter": ["أصوات طبيعية مسجّلة داخل التطبيق وتعمل دون إنترنت.", "Natural voices are bundled in the app and work offline.", "صداهای طبیعی درون برنامه‌اند و بدون اینترنت کار می‌کنند.", "Doğal sesler uygulamanın içindedir ve internetsiz çalışır.", "प्राकृतिक आवाज़ें ऐप में ही हैं और बिना इंटरनेट चलती हैं।", "স্বাভাবিক কণ্ঠগুলো অ্যাপের ভেতরেই আছে এবং ইন্টারনেট ছাড়া চলে।"],
    "settings.a11y": ["الإعدادات واللغة", "Settings and language", "تنظیمات و زبان", "Ayarlar ve dil", "सेटिंग्स और भाषा", "সেটিংস ও ভাষা"],
    "error.fileNotFound": ["لم يُعثر على الملف «{0}» داخل التطبيق.", "The file “{0}” was not found in the app.", "فایل «{0}» در برنامه پیدا نشد.", "“{0}” dosyası uygulamada bulunamadı.", "ऐप में “{0}” फ़ाइल नहीं मिली।", "অ্যাপে “{0}” ফাইলটি পাওয়া যায়নি।"],
    # --- v3: tab bar, question bank, settings, identity ---
    "tab.home": ["الرئيسية", "Home", "خانه", "Ana Sayfa", "होम", "হোম"],
    "tab.questions": ["الأسئلة", "Questions", "پرسش‌ها", "Sorular", "सवाल", "প্রশ্ন"],
    "tab.settings": ["الإعدادات", "Settings", "تنظیمات", "Ayarlar", "सेटिंग्स", "সেটিংস"],
    "settings.applyingLanguage": ["جارٍ تطبيق اللغة…", "Applying language…", "در حال اعمال زبان…", "Dil uygulanıyor…", "भाषा लागू हो रही है…", "ভাষা প্রয়োগ হচ্ছে…"],
    "quran.fontMissing": ["تعذّر تحميل خط هذه الصفحة", "This page's font could not be loaded", "بارگذاری قلم این صفحه ممکن نشد", "Bu sayfanın yazı tipi yüklenemedi", "इस पृष्ठ का फ़ॉन्ट लोड नहीं हो सका", "এই পৃষ্ঠার ফন্ট লোড করা যায়নি"],
    "prayer.title": ["مواقيت الصلاة", "Prayer times", "اوقات نماز", "Namaz vakitleri", "नमाज़ के समय", "নামাজের সময়"],
    "prayer.fajr": ["الفجر", "Fajr", "صبح", "İmsak / Sabah", "फ़ज्र", "ফজর"],
    "prayer.sunrise": ["الشروق", "Sunrise", "طلوع آفتاب", "Güneş", "सूर्योदय", "সূর্যোদয়"],
    "prayer.dhuhr": ["الظهر", "Dhuhr", "ظهر", "Öğle", "ज़ुहर", "যোহর"],
    "prayer.asr": ["العصر", "Asr", "عصر", "İkindi", "अस्र", "আসর"],
    "prayer.maghrib": ["المغرب", "Maghrib", "مغرب", "Akşam", "मग़रिब", "মাগরিব"],
    "prayer.isha": ["العشاء", "Isha", "عشا", "Yatsı", "इशा", "এশা"],
    "prayer.next": ["الصلاة القادمة", "Next prayer", "نماز بعدی", "Sıradaki vakit", "अगली नमाज़", "পরবর্তী নামাজ"],
    "prayer.remaining": ["بعد {0}", "in {0}", "{0} دیگر", "{0} sonra", "{0} में", "{0} পরে"],
    "prayer.inMinutes": ["بعد {0} دقيقة", "in {0} min", "{0} دقیقه دیگر", "{0} dk sonra", "{0} मिनट में", "{0} মিনিট পরে"],
    "prayer.inHoursMinutes": ["بعد {0} س و{1} د", "in {0} h {1} min", "{0} ساعت و {1} دقیقه دیگر", "{0} sa {1} dk sonra", "{0} घं {1} मि में", "{0} ঘ {1} মি পরে"],
    "prayer.locate": ["تحديد موقعي", "Use my location", "موقعیت من", "Konumumu kullan", "मेरी जगह इस्तेमाल करें", "আমার অবস্থান ব্যবহার করো"],
    "prayer.coordinates": ["{0}°، {1}°", "{0}°, {1}°", "{0}°، {1}°", "{0}°, {1}°", "{0}°, {1}°", "{0}°, {1}°"],
    "prayer.noLocationShort": ["حدّد موقعك", "Set your location", "موقعیت را تعیین کن", "Konumunu belirle", "अपनी जगह चुनें", "অবস্থান ঠিক করো"],
    "prayer.noLocation": ["نحتاج موقعك مرة واحدة لحساب مواقيت الصلاة بدقة. يُحفظ على جهازك فقط، وبعدها تعمل المواقيت دون إنترنت.", "We need your location once to calculate accurate prayer times. It stays on your device, and the times then work offline.", "برای محاسبهٔ دقیق اوقات نماز یک بار به موقعیت تو نیاز داریم. فقط روی دستگاه می‌ماند و پس از آن بدون اینترنت کار می‌کند.", "Doğru vakitler için konumuna bir kez ihtiyacımız var. Yalnızca cihazında kalır; sonra vakitler internetsiz çalışır.", "सही समय के लिए आपकी जगह एक बार चाहिए। यह सिर्फ़ आपके डिवाइस पर रहती है, फिर समय बिना इंटरनेट चलते हैं।", "সঠিক সময়ের জন্য একবার তোমার অবস্থান দরকার। এটি শুধু তোমার ডিভাইসে থাকে, তারপর ইন্টারনেট ছাড়াই চলে।"],
    "prayer.methodTitle": ["طريقة الحساب", "Calculation method", "روش محاسبه", "Hesaplama yöntemi", "गणना का तरीका", "হিসাবের পদ্ধতি"],
    "prayer.asrTitle": ["وقت العصر", "Asr time", "وقت عصر", "İkindi vakti", "अस्र का समय", "আসরের সময়"],
    "prayer.asr.standard": ["الجمهور", "Standard", "شافعی، مالکی، حنبلی", "Standart", "मानक", "মানক"],
    "prayer.asr.hanafi": ["الحنفي", "Hanafi", "حنفی", "Hanefi", "हनफ़ी", "হানাফি"],
    "prayer.soundTitle": ["صوت التنبيه", "Alert sound", "صدای اعلان", "Uyarı sesi", "अलर्ट की आवाज़", "সতর্কতার শব্দ"],
    "prayer.sound.adhan": ["الأذان", "Adhan", "اذان", "Ezan", "अज़ान", "আযান"],
    "prayer.sound.system": ["نغمة الجهاز", "Device tone", "صدای دستگاه", "Cihaz sesi", "डिवाइस की टोन", "ডিভাইসের টোন"],
    "prayer.playAdhan": ["استمع إلى الأذان", "Listen to the adhan", "شنیدن اذان", "Ezanı dinle", "अज़ान सुनें", "আযান শোনো"],
    "prayer.stopAdhan": ["إيقاف الأذان", "Stop the adhan", "توقف اذان", "Ezanı durdur", "अज़ान रोकें", "আযান থামাও"],
    "prayer.adhanAlert": ["تنبيه الأذان", "Adhan alert", "اعلان اذان", "Ezan uyarısı", "अज़ान अलर्ट", "আযানের সতর্কতা"],
    "prayer.notificationsDenied": ["الإشعارات متوقفة لهذا التطبيق، فلن يصلك الأذان. فعّلها من الإعدادات.", "Notifications are off for this app, so the adhan will not reach you. Turn them on in Settings.", "اعلان‌ها برای این برنامه خاموش است و اذان به تو نمی‌رسد. از تنظیمات روشنش کن.", "Bu uygulamanın bildirimleri kapalı, ezan sana ulaşmayacak. Ayarlar'dan aç.", "इस ऐप की सूचनाएँ बंद हैं, अज़ान आप तक नहीं पहुँचेगी। सेटिंग्स में चालू करें।", "এই অ্যাপের নোটিফিকেশন বন্ধ, তাই আযান পৌঁছাবে না। সেটিংসে চালু করো।"],
    "prayer.footer": ["تُحسب المواقيت على جهازك دون إنترنت من موقعك بالضبط. يُضبط تنبيه الأذان لاثني عشر يومًا قادمة، ويتجدد كلما فتحت التطبيق. إن كان التطبيق مفتوحًا وقت الأذان يُرفع الأذان كاملًا.", "Times are calculated on your device, offline. Adhan alerts are set for the next twelve days and renew whenever you open the app. If the app is open at prayer time, the full adhan plays.", "اوقات روی دستگاه و بدون اینترنت محاسبه می‌شود. اعلان اذان برای دوازده روز آینده تنظیم و با هر بار باز کردن برنامه تمدید می‌شود. اگر برنامه باز باشد، اذان کامل پخش می‌شود.", "Vakitler cihazında internetsiz hesaplanır. Ezan uyarıları önümüzdeki on iki gün için kurulur ve uygulamayı her açtığında yenilenir. Uygulama açıksa ezanın tamamı okunur.", "समय आपके डिवाइस पर बिना इंटरनेट निकाले जाते हैं। अज़ान अलर्ट अगले बारह दिनों के लिए लगते हैं और ऐप खोलने पर नए हो जाते हैं। ऐप खुला हो तो पूरी अज़ान चलती है।", "সময় তোমার ডিভাইসে ইন্টারনেট ছাড়াই হিসাব হয়। আযানের সতর্কতা আগামী বারো দিনের জন্য সেট হয় এবং অ্যাপ খুললেই নবায়ন হয়। অ্যাপ খোলা থাকলে পুরো আযান বাজে।"],
    "prayer.notification.title": ["حان الآن موعد أذان {0}", "It is time for {0}", "وقت اذان {0} است", "{0} vakti girdi", "{0} का समय हो गया", "{0}-এর সময় হয়েছে"],
    "prayer.notification.body": ["حيّ على الصلاة، حيّ على الفلاح", "Come to prayer, come to success", "حی علی الصلاة، حی علی الفلاح", "Haydi namaza, haydi kurtuluşa", "नमाज़ की ओर आओ, कामयाबी की ओर आओ", "নামাজের দিকে এসো, সাফল্যের দিকে এসো"],
    "prayer.notification.bodyPlace": ["حيّ على الصلاة — حسب توقيت {0}", "Come to prayer — times for {0}", "حی علی الصلاة — به وقت {0}", "Haydi namaza — {0} vakitleri", "नमाज़ की ओर आओ — {0} का समय", "নামাজের দিকে এসো — {0}-এর সময়"],
    "prayer.method.ummAlQura": ["أم القرى (مكة المكرمة)", "Umm al-Qura (Makkah)", "ام القری (مکه)", "Ümmü'l-Kura (Mekke)", "उम्म अल-क़ुरा (मक्का)", "উম্মুল কুরা (মক্কা)"],
    "prayer.method.muslimWorldLeague": ["رابطة العالم الإسلامي", "Muslim World League", "رابطهٔ جهان اسلام", "Dünya İslam Birliği", "मुस्लिम वर्ल्ड लीग", "মুসলিম ওয়ার্ল্ড লীগ"],
    "prayer.method.egypt": ["الهيئة المصرية العامة للمساحة", "Egyptian General Authority", "سازمان مساحی مصر", "Mısır Genel Otoritesi", "मिस्री जनरल अथॉरिटी", "মিশরীয় জেনারেল অথরিটি"],
    "prayer.method.karachi": ["جامعة العلوم الإسلامية بكراتشي", "University of Islamic Sciences, Karachi", "دانشگاه علوم اسلامی کراچی", "Karaçi İslami İlimler Üniversitesi", "इस्लामी विज्ञान विश्वविद्यालय, कराची", "ইসলামিক সায়েন্সেস বিশ্ববিদ্যালয়, করাচি"],
    "prayer.method.northAmerica": ["الجمعية الإسلامية لأمريكا الشمالية", "Islamic Society of North America", "انجمن اسلامی آمریکای شمالی", "Kuzey Amerika İslam Birliği", "इस्लामिक सोसाइटी ऑफ़ नॉर्थ अमेरिका", "ইসলামিক সোসাইটি অব নর্থ আমেরিকা"],
    "prayer.method.kuwait": ["الكويت", "Kuwait", "کویت", "Kuveyt", "कुवैत", "কুয়েত"],
    "prayer.method.qatar": ["قطر", "Qatar", "قطر", "Katar", "क़तर", "কাতার"],
    "prayer.method.dubai": ["دبي (الإمارات)", "Dubai (UAE)", "دبی (امارات)", "Dubai (BAE)", "दुबई (यूएई)", "দুবাই (সংযুক্ত আরব আমিরাত)"],
    "prayer.method.gulf": ["منطقة الخليج", "Gulf region", "منطقهٔ خلیج", "Körfez bölgesi", "खाड़ी क्षेत्र", "উপসাগরীয় অঞ্চল"],
    "prayer.method.turkey": ["تركيا", "Turkey", "ترکیه", "Türkiye", "तुर्की", "তুরস্ক"],
    "prayer.method.tehran": ["معهد الجيوفيزياء بطهران", "Institute of Geophysics, Tehran", "مؤسسهٔ ژئوفیزیک تهران", "Tahran Jeofizik Enstitüsü", "भूभौतिकी संस्थान, तेहरान", "ভূপদার্থবিদ্যা ইনস্টিটিউট, তেহরান"],
    "prayer.method.auto": ["تُختار تلقائيًا حسب البلد الذي أنت فيه", "Chosen automatically for the country you are in", "خودکار بر اساس کشوری که در آن هستی", "Bulunduğun ülkeye göre otomatik seçilir", "आप जिस देश में हैं उसके हिसाब से अपने-आप", "তুমি যে দেশে আছ সে অনুযায়ী স্বয়ংক্রিয়"],
    "prayer.method.manual": ["اخترتها بنفسك", "Chosen by you", "انتخاب خودت", "Senin seçimin", "आपकी पसंद", "তোমার পছন্দ"],
    "prayer.method.useAuto": ["تلقائي", "Automatic", "خودکار", "Otomatik", "अपने-आप", "স্বয়ংক্রিয়"],
    "prayer.placesCredit": ["أسماء الأماكن: GeoNames (CC BY 4.0)", "Place names: GeoNames (CC BY 4.0)", "نام مکان‌ها: GeoNames (CC BY 4.0)", "Yer adları: GeoNames (CC BY 4.0)", "जगहों के नाम: GeoNames (CC BY 4.0)", "স্থানের নাম: GeoNames (CC BY 4.0)"],
    "prayer.method.oman": ["سلطنة عُمان (وزارة الأوقاف)", "Oman (Ministry of Awqaf)", "عمان (وزارت اوقاف)", "Umman (Vakıflar Bakanlığı)", "ओमान (औक़ाफ़ मंत्रालय)", "ওমান (আওকাফ মন্ত্রণালয়)"],
    "common.close": ["إغلاق", "Close", "بستن", "Kapat", "बंद करें", "বন্ধ করো"],
    "bank.title": ["بنك الأسئلة", "Question bank", "بانک پرسش‌ها", "Soru bankası", "सवालों का बैंक", "প্রশ্ন ভান্ডার"],
    "bank.subtitle": ["{0} سؤالًا من الكتاب تظهر عشوائيًا", "{0} questions from the book, in random order", "{0} پرسش از کتاب، به‌صورت تصادفی", "Kitaptan rastgele {0} soru", "किताब से {0} सवाल, बेतरतीब क्रम में", "বই থেকে {0}টি প্রশ্ন, এলোমেলো ক্রমে"],
    "bank.loading": ["جارٍ تجهيز الأسئلة…", "Preparing questions…", "در حال آماده‌سازی پرسش‌ها…", "Sorular hazırlanıyor…", "सवाल तैयार हो रहे हैं…", "প্রশ্ন প্রস্তুত হচ্ছে…"],
    "bank.daily": ["سؤال اليوم", "Question of the day", "پرسش امروز", "Günün sorusu", "आज का सवाल", "আজকের প্রশ্ন"],
    "bank.newRound": ["جولة جديدة", "New round", "دور جدید", "Yeni tur", "नया दौर", "নতুন রাউন্ড"],
    "bank.newRoundSubtitle": ["اختر النوع والقسم وعدد الأسئلة", "Pick the type, chapter and number of questions", "نوع، بخش و تعداد پرسش‌ها را انتخاب کن", "Türü, bölümü ve soru sayısını seç", "प्रकार, अध्याय और सवालों की संख्या चुनें", "ধরন, অধ্যায় ও প্রশ্নের সংখ্যা বেছে নাও"],
    "bank.filter.all": ["الكل", "All", "همه", "Tümü", "सभी", "সব"],
    "bank.filter.choice": ["اختيار من متعدد", "Multiple choice", "چندگزینه‌ای", "Çoktan seçmeli", "बहुविकल्पी", "বহুনির্বাচনী"],
    "bank.filter.written": ["كتابة", "Written", "نوشتاری", "Yazılı", "लिखित", "লিখিত"],
    "bank.kind.choice": ["اختيار من متعدد", "Multiple choice", "چندگزینه‌ای", "Çoktan seçmeli", "बहुविकल्पी", "বহুনির্বাচনী"],
    "bank.kind.written": ["اكتب الإجابة", "Write the answer", "پاسخ را بنویس", "Cevabı yaz", "जवाब लिखें", "উত্তর লেখো"],
    "bank.chapter": ["القسم", "Chapter", "بخش", "Bölüm", "अध्याय", "অধ্যায়"],
    "bank.allChapters": ["كل الأقسام", "All chapters", "همهٔ بخش‌ها", "Tüm bölümler", "सभी अध्याय", "সব অধ্যায়"],
    "bank.roundLength": ["عدد الأسئلة", "Questions", "تعداد پرسش", "Soru sayısı", "सवालों की संख्या", "প্রশ্নের সংখ্যা"],
    "bank.start": ["ابدأ ({0} سؤالًا متاحًا)", "Start ({0} available)", "شروع ({0} پرسش)", "Başla ({0} soru)", "शुरू करें ({0} उपलब्ध)", "শুরু করো ({0}টি আছে)"],
    "bank.typeAnswer": ["اكتب الكلمة هنا…", "Type the word here…", "کلمه را اینجا بنویس…", "Kelimeyi buraya yaz…", "शब्द यहाँ लिखें…", "শব্দটি এখানে লেখো…"],
    "bank.hint": ["تلميح", "Hint", "راهنما", "İpucu", "संकेत", "ইঙ্গিত"],
    "bank.check": ["تحقّق", "Check", "بررسی", "Kontrol et", "जाँचें", "যাচাই করো"],
    "bank.dontKnow": ["لا أعرف", "I don’t know", "نمی‌دانم", "Bilmiyorum", "मुझे नहीं पता", "জানি না"],
    "bank.correctAnswer": ["الإجابة الصحيحة: {0}", "Correct answer: {0}", "پاسخ درست: {0}", "Doğru cevap: {0}", "सही जवाब: {0}", "সঠিক উত্তর: {0}"],
    "bank.anotherRound": ["جولة أخرى", "Another round", "دور دیگر", "Bir tur daha", "एक और दौर", "আরেক রাউন্ড"],
    "stats.answered": ["إجابة", "Answered", "پاسخ", "Cevaplanan", "जवाब दिए", "উত্তর দেওয়া"],
    "stats.accuracy": ["الدقّة", "Accuracy", "دقت", "Doğruluk", "सटीकता", "নির্ভুলতা"],
    "stats.bestStreak": ["أفضل سلسلة", "Best streak", "بهترین زنجیره", "En iyi seri", "सबसे लंबी लड़ी", "সেরা ধারাবাহিকতা"],
    "stats.days": ["أيام متتالية", "Day streak", "روزهای پیاپی", "Gün serisi", "लगातार दिन", "টানা দিন"],
    "stats.roundStreak": ["أطول سلسلة", "Longest streak", "بلندترین زنجیره", "En uzun seri", "सबसे लंबी लड़ी", "দীর্ঘতম ধারাবাহিকতা"],
    "settings.appearance": ["المظهر", "Appearance", "ظاهر", "Görünüm", "रूप", "চেহারা"],
    "appearance.system": ["تلقائي", "Automatic", "خودکار", "Otomatik", "अपने आप", "স্বয়ংক্রিয়"],
    "appearance.light": ["نهاري", "Light", "روشن", "Açık", "हल्का", "হালকা"],
    "appearance.dark": ["ليلي", "Dark", "تیره", "Koyu", "गहरा", "গাঢ়"],
    "settings.background": ["خلفية التطبيق", "App background", "پس‌زمینهٔ برنامه", "Uygulama arka planı", "ऐप का बैकग्राउंड", "অ্যাপের পটভূমি"],
    "theme.classic": ["كلاسيكي", "Classic", "کلاسیک", "Klasik", "क्लासिक", "ক্লাসিক"],
    "theme.ocean": ["محيط", "Ocean", "اقیانوس", "Okyanus", "सागर", "সমুদ্র"],
    "theme.sunset": ["غروب", "Sunset", "غروب", "Gün batımı", "सूर्यास्त", "সূর্যাস্ত"],
    "theme.emerald": ["زمرّد", "Emerald", "زمرد", "Zümrüt", "पन्ना", "পান্না"],
    "theme.royal": ["ملكي", "Royal", "سلطنتی", "Kraliyet", "शाही", "রাজকীয়"],
    "settings.appIcon": ["أيقونة التطبيق", "App icon", "آیکون برنامه", "Uygulama simgesi", "ऐप आइकन", "অ্যাপ আইকন"],
    "icon.classic": ["الأساسية", "Classic", "کلاسیک", "Klasik", "क्लासिक", "ক্লাসিক"],
    "icon.night": ["ليل", "Night", "شب", "Gece", "रात", "রাত"],
    "icon.desert": ["صحراء", "Desert", "صحرا", "Çöl", "रेगिस्तान", "মরুভূমি"],
    "icon.emerald": ["زمرّد", "Emerald", "زمرد", "Zümrüt", "पन्ना", "পান্না"],
    "icon.rose": ["ورد", "Rose", "گل سرخ", "Gül", "गुलाब", "গোলাপ"],
    "settings.tashkeel": ["إظهار التشكيل", "Show diacritics", "نمایش اعراب", "Harekeleri göster", "हरकात दिखाएँ", "হরকত দেখাও"],
    "settings.tashkeelFooter": ["تشكيل كامل لنصوص المسائل والخطوات يساعد على القراءة الصحيحة.", "Full vowel marks on topics and steps for correct reading.", "اعراب کامل متن‌ها برای خواندن درست.", "Doğru okuma için tam hareke.", "सही पढ़ने के लिए पूरी हरकात।", "সঠিক পড়ার জন্য পূর্ণ হরকত।"],
    "settings.speed": ["سرعة القراءة", "Reading speed", "سرعت خواندن", "Okuma hızı", "पढ़ने की रफ़्तार", "পড়ার গতি"],
    "settings.speedReset": ["٠٪", "0%", "۰٪", "%0", "0%", "০%"],
    "settings.general": ["عام", "General", "عمومی", "Genel", "सामान्य", "সাধারণ"],
    "settings.haptics": ["الاهتزاز عند اللمس", "Haptic feedback", "لرزش هنگام لمس", "Dokunsal geri bildirim", "छूने पर कंपन", "স্পর্শে কম্পন"],
    "settings.reminder": ["تذكير يومي بالتعلّم", "Daily learning reminder", "یادآور روزانهٔ یادگیری", "Günlük öğrenme hatırlatıcısı", "रोज़ाना सीखने की याद", "প্রতিদিন শেখার রিমাইন্ডার"],
    "settings.reminderFooter": ["إشعار لطيف كل يوم في الوقت الذي تختاره.", "A gentle notification every day at your chosen time.", "هر روز در زمان دلخواه یک اعلان ملایم.", "Seçtiğin saatte her gün nazik bir bildirim.", "आपके चुने समय पर रोज़ एक हल्की सूचना।", "তোমার বেছে নেওয়া সময়ে প্রতিদিন একটি নোটিফিকেশন।"],
    "settings.reminderDenied": ["فعّل الإشعارات للتطبيق من إعدادات الجهاز أولًا.", "Allow notifications for the app in the device Settings first.", "ابتدا اعلان‌ها را در تنظیمات دستگاه فعال کن.", "Önce cihaz ayarlarından bildirimlere izin ver.", "पहले डिवाइस सेटिंग्स में सूचनाएँ चालू करें।", "আগে ডিভাইসের সেটিংসে নোটিফিকেশন চালু করো।"],
    "settings.reminderTime": ["وقت التذكير", "Reminder time", "زمان یادآوری", "Hatırlatma saati", "याद दिलाने का समय", "রিমাইন্ডারের সময়"],
    "settings.progress": ["التقدّم", "Progress", "پیشرفت", "İlerleme", "प्रगति", "অগ্রগতি"],
    "settings.progressDetails": ["تفاصيل تقدّمي", "My progress details", "جزئیات پیشرفت من", "İlerleme ayrıntıları", "मेरी प्रगति का विवरण", "আমার অগ্রগতির বিবরণ"],
    "settings.support": ["الدعم والمشاركة", "Support & sharing", "پشتیبانی و اشتراک‌گذاری", "Destek ve paylaşım", "सहायता और साझा करें", "সহায়তা ও শেয়ার"],
    "settings.contactSupport": ["راسل الدعم الفني", "Contact support", "تماس با پشتیبانی", "Destekle iletişim", "सहायता से संपर्क करें", "সহায়তায় যোগাযোগ করো"],
    "settings.supportSubject": ["دعم تطبيق ثقافة إسلامية", "Islamic Culture app support", "پشتیبانی برنامهٔ فرهنگ اسلامی", "İslami Kültür uygulama desteği", "इस्लामी संस्कृति ऐप सहायता", "ইসলামী সংস্কৃতি অ্যাপ সহায়তা"],
    "settings.copyEmail": ["نسخ البريد الإلكتروني", "Copy email address", "کپی نشانی ایمیل", "E-posta adresini kopyala", "ईमेल पता कॉपी करें", "ইমেইল ঠিকানা কপি করো"],
    "settings.copied": ["تم النسخ ✓", "Copied ✓", "کپی شد ✓", "Kopyalandı ✓", "कॉपी हो गया ✓", "কপি হয়েছে ✓"],
    "settings.share": ["شارك التطبيق", "Share the app", "اشتراک‌گذاری برنامه", "Uygulamayı paylaş", "ऐप साझा करें", "অ্যাপটি শেয়ার করো"],
    "settings.shareText": ["تطبيق «{0}» — القرآن الكريم مع التفسير والتلاوة، وتعلّم الوضوء والصلاة خطوة بخطوة، دون إنترنت. من تطوير {1}.", "“{0}” — the Holy Quran with tafsir and recitation, plus wudu and prayer step by step, fully offline. Developed by Saqer.", "«{0}» — قرآن کریم با تفسیر و تلاوت، و آموزش وضو و نماز قدم‌به‌قدم، بدون اینترنت. ساختهٔ صقر.", "“{0}” — tefsir ve tilavetle Kur’an-ı Kerim, adım adım abdest ve namaz, internetsiz. Geliştiren: Saqer.", "“{0}” — तफ़सीर और तिलावत के साथ क़ुरआन मजीद, और क़दम-ब-क़दम वुज़ू व नमाज़, बिना इंटरनेट। विकसित: Saqer.", "“{0}” — তাফসীর ও তিলাওয়াতসহ কুরআন মাজীদ, ধাপে ধাপে অজু ও নামাজ, ইন্টারনেট ছাড়াই। নির্মাতা: Saqer।"],
    "settings.version": ["الإصدار {0}", "Version {0}", "نسخهٔ {0}", "Sürüm {0}", "संस्करण {0}", "সংস্করণ {0}"],
    "brand.developedBy": ["تم تطويره بواسطة {0} © {1}", "Developed by Saqer © {1}", "توسعه‌یافته توسط صقر (Saqer) © {1}", "Saqer tarafından geliştirildi © {1}", "Saqer द्वारा विकसित © {1}", "Saqer দ্বারা নির্মিত © {1}"],
    "brand.tagline": ["تعلّم دينك خطوة بخطوة", "Learn your faith step by step", "دینت را قدم‌به‌قدم بیاموز", "Dinini adım adım öğren", "अपना दीन क़दम-ब-क़दम सीखें", "তোমার দ্বীন ধাপে ধাপে শেখো"],
    "reminder.title": ["ثقافة إسلامية 🌙", "Islamic Culture 🌙", "فرهنگ اسلامی 🌙", "İslami Kültür 🌙", "इस्लामी संस्कृति 🌙", "ইসলামী সংস্কৃতি 🌙"],
    "reminder.body": ["حان وقت درسك اليومي — سؤال واحد يكفي لتبدأ ✨", "Time for today’s lesson — one question is enough to start ✨", "وقت درس امروز است — یک پرسش برای شروع کافی است ✨", "Günlük ders zamanı — başlamak için bir soru yeter ✨", "आज के पाठ का समय — शुरू करने के लिए एक सवाल काफ़ी है ✨", "আজকের পাঠের সময় — শুরু করতে একটি প্রশ্নই যথেষ্ট ✨"],
    # --- v4: Quran ---
    "tab.quran": ["القرآن", "Quran", "قرآن", "Kur’an", "क़ुरआन", "কুরআন"],
    "masala.page": ["الصفحة {0}", "Page {0}", "صفحهٔ {0}", "Sayfa {0}", "पृष्ठ {0}", "পৃষ্ঠা {0}"],
    "quran.title": ["القرآن الكريم", "The Holy Quran", "قرآن کریم", "Kur’an-ı Kerim", "क़ुरआन मजीद", "কুরআন মাজীদ"],
    "quran.loading": ["جارٍ تجهيز المصحف…", "Preparing the mushaf…", "در حال آماده‌سازی مصحف…", "Mushaf hazırlanıyor…", "मुसहफ़ तैयार हो रहा है…", "মুসহাফ প্রস্তুত হচ্ছে…"],
    "quran.start": ["ابدأ القراءة", "Start reading", "شروع قرائت", "Okumaya başla", "पढ़ना शुरू करें", "পড়া শুরু করো"],
    "quran.continue": ["تابع القراءة", "Continue reading", "ادامهٔ قرائت", "Okumaya devam et", "पढ़ना जारी रखें", "পড়া চালিয়ে যাও"],
    "quran.khatma": ["الختمة", "Khatmah", "ختم", "Hatim", "ख़त्म", "খতম"],
    "quran.pageJuz": ["الصفحة {0} · الجزء {1}", "Page {0} · Juz {1}", "صفحهٔ {0} · جزء {1}", "Sayfa {0} · Cüz {1}", "पृष्ठ {0} · पारा {1}", "পৃষ্ঠা {0} · পারা {1}"],
    "quran.surahName": ["سورة {0}", "Surah {0}", "سورهٔ {0}", "{0} Suresi", "सूरह {0}", "সূরা {0}"],
    "quran.friday.title": ["جمعة مباركة — سورة الكهف", "Blessed Friday — Surat Al-Kahf", "جمعهٔ مبارک — سورهٔ کهف", "Hayırlı Cumalar — Kehf Suresi", "जुमा मुबारक — सूरह अल-कहफ़", "জুমা মোবারক — সূরা আল-কাহফ"],
    "quran.friday.body": ["من السنّة قراءة سورة الكهف يوم الجمعة. اضغط لتبدأ.", "It is Sunnah to read Al-Kahf on Friday. Tap to begin.", "خواندن سورهٔ کهف در روز جمعه سنت است. برای شروع لمس کن.", "Cuma günü Kehf suresini okumak sünnettir. Başlamak için dokun.", "जुमा के दिन सूरह अल-कहफ़ पढ़ना सुन्नत है। शुरू करने के लिए छुएँ।", "জুমার দিনে সূরা কাহফ পড়া সুন্নত। শুরু করতে ছোঁও।"],
    "quran.special": ["سور مختارة", "Selected surahs", "سوره‌های منتخب", "Seçilmiş sureler", "चुनी हुई सूरतें", "নির্বাচিত সূরা"],
    "quran.special.18": ["تُقرأ كل جمعة", "Read every Friday", "هر جمعه خوانده می‌شود", "Her cuma okunur", "हर जुमा को पढ़ी जाती है", "প্রতি জুমায় পড়া হয়"],
    "quran.special.67": ["المانعة من عذاب القبر، تُقرأ كل ليلة", "The protector — read every night", "بازدارنده از عذاب قبر، هر شب", "Kabir azabına kalkan, her gece okunur", "क़ब्र के अज़ाब से बचाने वाली, हर रात", "কবরের আজাব থেকে রক্ষাকারী, প্রতি রাতে"],
    "quran.special.2": ["أخذها بركة وتركها حسرة", "Taking it is a blessing, leaving it a regret", "فراگرفتنش برکت و رها کردنش حسرت است", "Onu almak bereket, bırakmak hasrettir", "इसे अपनाना बरकत, छोड़ना पछतावा", "এটি গ্রহণ বরকত, বর্জন অনুশোচনা"],
    "quran.special.36": ["قلب القرآن", "The heart of the Quran", "قلب قرآن", "Kur’an’ın kalbi", "क़ुरआन का दिल", "কুরআনের হৃদয়"],
    "quran.listen": ["استمع", "Listen", "گوش کن", "Dinle", "सुनें", "শোনো"],
    "quran.listenPage": ["استمع للصفحة", "Listen to this page", "به این صفحه گوش کن", "Bu sayfayı dinle", "यह पृष्ठ सुनें", "এই পৃষ্ঠাটি শোনো"],
    "quran.listenFromHere": ["استمع من هذه الآية", "Listen from this ayah", "از این آیه گوش کن", "Bu ayetten dinle", "इस आयत से सुनें", "এই আয়াত থেকে শোনো"],
    "quran.nowPlaying": ["سورة {0} · الآية {1}", "Surah {0} · Ayah {1}", "سورهٔ {0} · آیهٔ {1}", "{0} Suresi · Ayet {1}", "सूरह {0} · आयत {1}", "সূরা {0} · আয়াত {1}"],
    "quran.reciter": ["القارئ", "Reciter", "قاری", "Kâri", "क़ारी", "ক্বারী"],
    "quran.reciters": ["القرّاء", "Reciters", "قاریان", "Kâriler", "क़ारी", "ক্বারীগণ"],
    "quran.offlineCount": ["{0} من {1} سورة دون إنترنت", "{0} of {1} surahs offline", "{0} از {1} سوره بدون اینترنت", "{1} sureden {0} tanesi çevrimdışı", "{1} में से {0} सूरतें ऑफ़लाइन", "{1}টির মধ্যে {0}টি সূরা অফলাইন"],
    "quran.partial": ["سجّل {0} سورة", "Recorded {0} surahs", "{0} سوره ضبط شده", "{0} sure kaydetti", "{0} सूरतें रिकॉर्ड कीं", "{0}টি সূরা রেকর্ড"],
    "quran.downloadAll": ["حمّل المصحف كاملًا بهذا الصوت", "Download the whole Quran in this voice", "دانلود کامل قرآن با این صدا", "Tüm Kur’an’ı bu sesle indir", "पूरा क़ुरआन इस आवाज़ में डाउनलोड करें", "পুরো কুরআন এই কণ্ঠে ডাউনলোড করো"],
    "quran.delete": ["حذف التحميلات", "Delete downloads", "حذف دانلودها", "İndirilenleri sil", "डाउनलोड हटाएँ", "ডাউনলোড মুছো"],
    "quran.deleteConfirm": ["حذف السور المحمّلة لهذا القارئ؟ (المدمجة في التطبيق تبقى)", "Delete this reciter’s downloaded surahs? (Built-in ones stay)", "سوره‌های دانلودشدهٔ این قاری حذف شود؟ (سوره‌های داخلی می‌مانند)", "Bu kârinin indirilen sureleri silinsin mi? (Dahili olanlar kalır)", "इस क़ारी की डाउनलोड सूरतें हटाएँ? (अंदर की सूरतें रहेंगी)", "এই ক্বারীর ডাউনলোড করা সূরাগুলো মুছবে? (অ্যাপের ভেতরেরগুলো থাকবে)"],
    "quran.offlineFooter": ["الكهف والملك والفاتحة ويس والرحمن والواقعة وجزء عمّ بصوت هزاع البلوشي، والبقرة والكهف والملك بصوت مشاري العفاسي — مدمجة وتعمل دون إنترنت. أي سورة أخرى تُحفظ على جهازك تلقائيًا بعد أول استماع، أو حمّل المصحف كاملًا مرة واحدة ليعمل دون إنترنت دائمًا.", "Al-Kahf, Al-Mulk, Al-Fatiha, Ya-Sin, Ar-Rahman, Al-Waqi’ah and Juz ’Amma (Hazza Al-Balushi), plus Al-Baqarah, Al-Kahf and Al-Mulk (Mishary Alafasy), are built in and work offline. Any other surah is saved on your device after the first listen — or download a whole recitation once to keep it offline forever.", "کهف، ملک، فاتحه، یس، الرحمن، واقعه و جزء عمّ با صدای هزاع البلوشی، و بقره، کهف و ملک با صدای مشاری العفاسی داخل برنامه‌اند و بدون اینترنت کار می‌کنند. هر سورهٔ دیگر پس از اولین شنیدن روی دستگاه ذخیره می‌شود، یا یک‌بار کل قرآن را دانلود کن.", "Kehf, Mülk, Fatiha, Yasin, Rahman, Vâkıa ve Amme cüzü (Hazza el-Beluşi) ile Bakara, Kehf ve Mülk (Mişari Afasi) uygulamanın içindedir ve internetsiz çalışır. Diğer sureler ilk dinlemeden sonra cihazına kaydedilir; ya da tüm tilaveti bir kez indir.", "अल-कहफ़, अल-मुल्क, अल-फ़ातिहा, या-सीन, अर-रहमान, अल-वाक़िआ और पारा अम्म (हज़्ज़ा अल-बलूशी), और अल-बक़रह, अल-कहफ़ व अल-मुल्क (मिशारी अल-अफ़ासी) ऐप में ही हैं और बिना इंटरनेट चलती हैं। बाक़ी सूरतें पहली बार सुनने के बाद डिवाइस में सेव हो जाती हैं, या पूरा क़ुरआन एक बार डाउनलोड करें।", "আল-কাহফ, আল-মুলক, আল-ফাতিহা, ইয়াসীন, আর-রহমান, আল-ওয়াকিআ ও আমপারা (হাজ্জা আল-বালুশি), এবং আল-বাকারা, আল-কাহফ ও আল-মুলক (মিশারি আলাফাসি) অ্যাপের ভেতরেই আছে এবং ইন্টারনেট ছাড়া চলে। অন্য সূরাগুলো প্রথমবার শোনার পর ডিভাইসে সংরক্ষিত হয়, অথবা পুরো কুরআন একবার ডাউনলোড করো।"],
    "quran.offlineMissing": ["هذه السورة غير محمّلة على جهازك ولا يوجد اتصال. حمّلها مرة واحدة لتعمل دون إنترنت.", "This surah isn’t on your device and there’s no connection. Download it once to use it offline.", "این سوره روی دستگاه نیست و اتصال ندارید. یک‌بار دانلودش کن تا بدون اینترنت کار کند.", "Bu sure cihazında yok ve bağlantı yok. Çevrimdışı kullanmak için bir kez indir.", "यह सूरह आपके डिवाइस पर नहीं है और इंटरनेट भी नहीं है। ऑफ़लाइन के लिए एक बार डाउनलोड करें।", "এই সূরাটি তোমার ডিভাইসে নেই এবং সংযোগও নেই। অফলাইনের জন্য একবার ডাউনলোড করো।"],
    "quran.notRecorded": ["لم يسجّل {0} هذه السورة، تُتلى بصوت {1}.", "{0} hasn’t recorded this surah; playing {1}.", "{0} این سوره را ضبط نکرده؛ با صدای {1} پخش می‌شود.", "{0} bu sureyi kaydetmedi; {1} sesiyle çalınıyor.", "{0} ने यह सूरह रिकॉर्ड नहीं की; {1} की आवाज़ में।", "{0} এই সূরাটি রেকর্ড করেননি; {1}-এর কণ্ঠে বাজছে।"],
    "quran.index.surahs": ["السور", "Surahs", "سوره‌ها", "Sureler", "सूरतें", "সূরা"],
    "quran.index.juz": ["الأجزاء", "Juz", "جزءها", "Cüzler", "पारे", "পারা"],
    "quran.index.bookmarks": ["العلامات", "Bookmarks", "نشانه‌ها", "Yer imleri", "बुकमार्क", "বুকমার্ক"],
    "quran.search": ["ابحث عن سورة (الاسم أو الرقم)", "Search a surah (name or number)", "جستجوی سوره (نام یا شماره)", "Sure ara (ad veya numara)", "सूरह खोजें (नाम या संख्या)", "সূরা খোঁজো (নাম বা নম্বর)"],
    "quran.juz": ["الجزء", "Juz", "جزء", "Cüz", "पारा", "পারা"],
    "quran.meccan": ["مكية", "Meccan", "مکی", "Mekki", "मक्की", "মাক্কী"],
    "quran.medinan": ["مدنية", "Medinan", "مدنی", "Medeni", "मदनी", "মাদানী"],
    "quran.ayahCount": ["{0} آية", "{0} ayahs", "{0} آیه", "{0} ayet", "{0} आयतें", "{0} আয়াত"],
    "quran.noBookmarks": ["لا توجد علامات بعد — اضغط زر العلامة داخل المصحف لحفظ صفحة.", "No bookmarks yet — use the bookmark button in the mushaf to save a page.", "هنوز نشانه‌ای نیست — در مصحف دکمهٔ نشانه را بزن.", "Henüz yer imi yok — mushafta yer imi düğmesine dokun.", "अभी कोई बुकमार्क नहीं — मुसहफ़ में बुकमार्क बटन दबाएँ।", "এখনো কোনো বুকমার্ক নেই — মুসহাফে বুকমার্ক বোতাম চাপো।"],
    "quran.addBookmark": ["ضع علامة على هذه الصفحة", "Bookmark this page", "نشانه‌گذاری این صفحه", "Bu sayfayı işaretle", "यह पृष्ठ बुकमार्क करें", "এই পৃষ্ঠা বুকমার্ক করো"],
    "quran.removeBookmark": ["أزل العلامة", "Remove bookmark", "حذف نشانه", "Yer imini kaldır", "बुकमार्क हटाएँ", "বুকমার্ক সরাও"],
    "quran.nightPages": ["صفحات ليلية", "Night pages", "صفحه‌های شبانه", "Gece sayfaları", "रात के पृष्ठ", "রাতের পৃষ্ঠা"],
    "quran.follow": ["تابع التلاوة صفحة بصفحة", "Follow the recitation page by page", "همراهی با تلاوت صفحه‌به‌صفحه", "Tilaveti sayfa sayfa izle", "तिलावत के साथ पृष्ठ बदलें", "তিলাওয়াতের সঙ্গে পৃষ্ঠা বদলাও"],
    "quran.tafsir": ["التفسير", "Tafsir", "تفسیر", "Tefsir", "तफ़सीर", "তাফসীর"],
    "quran.tafsirTitle": ["تفسير الصفحة {0}", "Tafsir of page {0}", "تفسیر صفحهٔ {0}", "Sayfa {0} tefsiri", "पृष्ठ {0} की तफ़सीर", "পৃষ্ঠা {0}-এর তাফসীর"],
    "quran.tafsirName": ["التفسير الميسّر", "Al-Tafsir Al-Muyassar (Arabic)", "التفسیر المیسر (عربی)", "Et-Tefsîrü’l-Müyesser (Arapça)", "अत-तफ़सीर अल-मुयस्सर (अरबी)", "আত-তাফসীর আল-মুয়াস্সার (আরবি)"],
    "quran.showTafsir": ["التفسير الميسّر", "Arabic tafsir", "تفسیر عربی", "Arapça tefsir", "अरबी तफ़सीर", "আরবি তাফসীর"],
    "quran.ayahNumber": ["الآية {0}", "Ayah {0}", "آیهٔ {0}", "Ayet {0}", "आयत {0}", "আয়াত {0}"],
    "quran.sajda": ["سجدة", "Prostration", "سجده", "Secde", "सज्दा", "সিজদা"],
    "quran.pageLabel": ["صفحة المصحف {0}", "Mushaf page {0}", "صفحهٔ مصحف {0}", "Mushaf sayfası {0}", "मुसहफ़ पृष्ठ {0}", "মুসহাফ পৃষ্ঠা {0}"],
    "quran.confined": ["قراءة {0} حتى تمامها", "Reading {0} to the end", "خواندن {0} تا پایان", "{0} sonuna kadar okunuyor", "{0} पूरी पढ़ें", "{0} শেষ পর্যন্ত পড়া"],
    "quran.confined.done": ["أتممت قراءة {0} — تقبّل الله منك", "You completed {0} — may Allah accept it", "{0} را به پایان رساندی — خدا بپذیرد", "{0} tamamlandı — Allah kabul etsin", "आपने {0} पूरी की — अल्लाह क़बूल करे", "তুমি {0} শেষ করেছ — আল্লাহ কবুল করুন"],
    "quran.confined.restart": ["من البداية", "From the start", "از ابتدا", "Baştan", "शुरू से", "শুরু থেকে"],
    "quran.pressHint": ["اضغط مطوّلًا على آية لتفسيرها", "Long-press an ayah for its tafsir", "برای تفسیر، روی آیه نگه دار", "Tefsiri için ayete basılı tut", "तफ़सीर के लिए आयत को दबाकर रखें", "তাফসীরের জন্য আয়াতে চেপে ধরো"],
    "qibla.title": ["اتجاه القبلة", "Qibla direction", "جهت قبله", "Kıble yönü", "क़िबला की दिशा", "কিবলার দিক"],
    "qibla.subtitle": ["بوصلة تعمل دون إنترنت", "A compass that works offline", "قطب‌نمایی که بدون اینترنت کار می‌کند", "İnternetsiz çalışan pusula", "बिना इंटरनेट चलने वाला कम्पास", "ইন্টারনেট ছাড়াই চলা কম্পাস"],
    "qibla.aligned": ["أنت تتجه إلى القبلة", "You are facing the Qibla", "رو به قبله هستی", "Kıbleye dönüksün", "आप क़िबला की ओर हैं", "তুমি কিবলার দিকে মুখ করে আছ"],
    "qibla.turn": ["أدِر الجهاز حتى يتطابق السهم مع الكعبة", "Turn until the arrow meets the Kaaba", "بچرخ تا پیکان با کعبه یکی شود", "Ok Kâbe ile buluşana kadar dön", "तब तक घुमाएँ जब तक तीर काबा से न मिले", "তীর কাবার সঙ্গে না মেলা পর্যন্ত ঘোরাও"],
    "qibla.bearing": ["القبلة {0}° من الشمال", "Qibla {0}° from north", "قبله {0}° از شمال", "Kıble kuzeyden {0}°", "क़िबला उत्तर से {0}°", "কিবলা উত্তর থেকে {0}°"],
    "qibla.distance": ["المسافة إلى مكة {0} كم", "{0} km to Makkah", "{0} کیلومتر تا مکه", "Mekke'ye {0} km", "मक्का तक {0} किमी", "মক্কা পর্যন্ত {0} কিমি"],
    "qibla.locating": ["جارٍ تحديد موقعك…", "Finding your location…", "در حال یافتن موقعیت…", "Konum bulunuyor…", "आपकी जगह खोजी जा रही है…", "তোমার অবস্থান খোঁজা হচ্ছে…"],
    "qibla.denied": ["اسمح للتطبيق بالوصول إلى موقعك من الإعدادات لتحديد القبلة. لا يُرسل موقعك إلى أي مكان.", "Allow location access in Settings to find the Qibla. Your location never leaves the device.", "برای یافتن قبله، دسترسی به موقعیت را در تنظیمات مجاز کن. موقعیتت جایی فرستاده نمی‌شود.", "Kıbleyi bulmak için Ayarlar'dan konum izni ver. Konumun cihazdan çıkmaz.", "क़िबला के लिए सेटिंग्स में लोकेशन की अनुमति दें। आपकी लोकेशन कहीं नहीं भेजी जाती।", "কিবলা খুঁজতে সেটিংসে লোকেশনের অনুমতি দাও। তোমার অবস্থান কোথাও পাঠানো হয় না।"],
    "qibla.openSettings": ["فتح الإعدادات", "Open Settings", "باز کردن تنظیمات", "Ayarları aç", "सेटिंग्स खोलें", "সেটিংস খোলো"],
    "qibla.calibrate": ["حرّك الجهاز على شكل ٨ لمعايرة البوصلة", "Move your device in a figure 8 to calibrate", "برای تنظیم قطب‌نما، دستگاه را به شکل ۸ حرکت بده", "Pusulayı ayarlamak için cihazı 8 çizerek hareket ettir", "कम्पास ठीक करने के लिए फ़ोन को 8 के आकार में घुमाएँ", "কম্পাস ঠিক করতে ফোনটি ৮-এর মতো ঘোরাও"],
    "qibla.noCompass": ["هذا الجهاز لا يحتوي على بوصلة — استخدم الزاوية من الشمال.", "This device has no compass — use the angle from north.", "این دستگاه قطب‌نما ندارد — از زاویه نسبت به شمال استفاده کن.", "Bu cihazda pusula yok — kuzeyden açıyı kullan.", "इस डिवाइस में कम्पास नहीं है — उत्तर से कोण का उपयोग करें।", "এই ডিভাইসে কম্পাস নেই — উত্তর থেকে কোণ ব্যবহার করো।"],
    "qibla.north": ["ش", "N", "ش", "K", "उ", "উ"],
    "qibla.east": ["ق", "E", "خ", "D", "पू", "পূ"],
    "qibla.south": ["ج", "S", "ج", "G", "द", "দ"],
    "qibla.west": ["غ", "W", "غ", "B", "प", "প"],
    "qibla.turnRight": ["أدِر يمينًا", "Turn right", "به راست بچرخ", "Sağa dön", "दाएँ घुमाएँ", "ডানে ঘোরাও"],
    "qibla.turnLeft": ["أدِر يسارًا", "Turn left", "به چپ بچرخ", "Sola dön", "बाएँ घुमाएँ", "বাঁয়ে ঘোরাও"],
}

out = {}
for key, values in S.items():
    assert len(values) == len(LANGS), key
    out[key] = dict(zip(LANGS, values))

path = os.path.join(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "ThaqafaIslamiya", "Assets", "Data"), "UIStrings.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=1, sort_keys=True)
print(len(out), "keys")
