"""UI strings for all languages -> Assets/Data/UIStrings.json  ({key: {lang: text}}).
Placeholders: {0}, {1} …  (replaced in Swift by L10n.t)."""
import json, os

LANGS = ["ar", "en", "fa", "tr", "hi", "bn"]

S = {
    "app.name": ["ثقافة إسلامية", "Islamic Culture", "فرهنگ اسلامی", "İslami Kültür", "इस्लामी संस्कृति", "ইসলামী সংস্কৃতি"],
    "home.greeting": ["السلام عليكم 👋", "Assalamu alaikum 👋", "السلام علیکم 👋", "Esselâmu aleyküm 👋", "अस्सलामु अलैकुम 👋", "আসসালামু আলাইকুম 👋"],
    "home.myProgress": ["تقدّمي", "My progress", "پیشرفت من", "İlerlemem", "मेरी प्रगति", "আমার অগ্রগতি"],
    "home.progressA11y": ["تقدّمك وعن الكتاب", "Your progress and about the book", "پیشرفت شما و درباره کتاب", "İlerlemen ve kitap hakkında", "आपकी प्रगति और किताब के बारे में", "তোমার অগ্রগতি ও বই সম্পর্কে"],
    "home.lessons.title": ["رحلات تفاعلية", "Interactive journeys", "سفرهای تعاملی", "Etkileşimli yolculuklar", "इंटरैक्टिव सफ़र", "ইন্টারঅ্যাকটিভ যাত্রা"],
    "home.lessons.subtitle": ["تعلّم خطوة بخطوة بالبطاقات", "Learn step by step with cards", "با کارت‌ها قدم‌به‌قدم بیاموز", "Kartlarla adım adım öğren", "कार्ड के साथ क़दम-ब-क़दम सीखें", "কার্ডে ধাপে ধাপে শেখো"],
    "home.chapters.title": ["أقسام الكتاب", "Book chapters", "بخش‌های کتاب", "Kitabın bölümleri", "किताब के अध्याय", "বইয়ের অধ্যায়সমূহ"],
    "home.chapters.subtitle": ["{0} مسألة في {1} قسمًا", "{0} topics in {1} chapters", "{0} مسئله در {1} بخش", "{1} bölümde {0} mesele", "{1} अध्यायों में {0} मसले", "{1}টি অধ্যায়ে {0}টি মাসআলা"],
    "search.placeholder": ["ابحث عن مسألة… (الوضوء، الزكاة، الجار)", "Search a topic… (wudu, zakat, neighbour)", "جستجوی مسئله… (وضو، زکات، همسایه)", "Mesele ara… (abdest, zekât, komşu)", "मसला खोजें… (वुज़ू, ज़कात, पड़ोसी)", "মাসআলা খোঁজো… (অজু, যাকাত, প্রতিবেশী)"],
    "search.clear": ["مسح البحث", "Clear search", "پاک کردن جستجو", "Aramayı temizle", "खोज साफ़ करें", "খোঁজ মুছে ফেলো"],
    "search.title": ["نتائج البحث", "Search results", "نتایج جستجو", "Arama sonuçları", "खोज परिणाम", "খোঁজের ফলাফল"],
    "search.count": ["{0} نتيجة", "{0} results", "{0} نتیجه", "{0} sonuç", "{0} परिणाम", "{0}টি ফলাফল"],
    "search.empty": ["لم نجد مسألة بهذا الاسم، جرّب كلمة أخرى 🌱", "No topic found — try another word 🌱", "مسئله‌ای با این نام پیدا نشد، کلمهٔ دیگری امتحان کن 🌱", "Bu adla mesele bulunamadı, başka bir kelime dene 🌱", "इस नाम का कोई मसला नहीं मिला, दूसरा शब्द आज़माएँ 🌱", "এই নামে কোনো মাসআলা পাওয়া যায়নি, অন্য শব্দ চেষ্টা করো 🌱"],
    "chapter.masailCount": ["{0} مسألة", "{0} topics", "{0} مسئله", "{0} mesele", "{0} मसले", "{0}টি মাসআলা"],
    "chapter.openHint": ["افتح القسم", "Open chapter", "باز کردن بخش", "Bölümü aç", "अध्याय खोलें", "অধ্যায় খোলো"],
    "chapter.learnInteractive": ["تعلّم بالتفاعل", "Learn by doing", "یادگیری تعاملی", "Yaparak öğren", "करके सीखें", "করে করে শেখো"],
    "chapter.masail": ["المسائل", "Topics", "مسائل", "Meseleler", "मसले", "মাসআলাসমূহ"],
    "chapter.masailSubtitle": ["اختر مسألة لتتعلّمها", "Choose a topic to learn", "یک مسئله برای یادگیری انتخاب کن", "Öğrenmek için bir mesele seç", "सीखने के लिए एक मसला चुनें", "শেখার জন্য একটি মাসআলা বেছে নাও"],
    "lesson.stepsCount": ["{0} خطوة", "{0} steps", "{0} مرحله", "{0} adım", "{0} क़दम", "{0}টি ধাপ"],
    "lesson.startHint": ["ابدأ الدرس التفاعلي", "Start the interactive lesson", "شروع درس تعاملی", "Etkileşimli dersi başlat", "इंटरैक्टिव पाठ शुरू करें", "ইন্টারঅ্যাকটিভ পাঠ শুরু করো"],
    "lesson.close": ["إغلاق الدرس", "Close lesson", "بستن درس", "Dersi kapat", "पाठ बंद करें", "পাঠ বন্ধ করো"],
    "lesson.swipeHintRTL": ["اسحب البطاقة إلى اليمين للخطوة التالية 👉", "Swipe the card right for the next step 👉", "کارت را به راست بکش تا مرحلهٔ بعد بیاید 👉", "Sonraki adım için kartı sağa kaydır 👉", "अगले क़दम के लिए कार्ड को दाईं ओर खींचें 👉", "পরের ধাপের জন্য কার্ডটি ডানে সরাও 👉"],
    "lesson.swipeHintLTR": ["اسحب البطاقة إلى اليسار للخطوة التالية 👈", "Swipe the card left for the next step 👈", "کارت را به چپ بکش تا مرحلهٔ بعد بیاید 👈", "Sonraki adım için kartı sola kaydır 👈", "अगले क़दम के लिए कार्ड को बाईं ओर खींचें 👈", "পরের ধাপের জন্য কার্ডটি বাঁয়ে সরাও 👈"],
    "lesson.previous": ["السابق", "Back", "قبلی", "Geri", "पिछला", "আগের"],
    "lesson.next": ["التالي", "Next", "بعدی", "İleri", "अगला", "পরের"],
    "lesson.finish": ["أتممتُ الدرس", "I finished!", "درس را تمام کردم", "Dersi bitirdim", "पाठ पूरा किया", "পাঠ শেষ করেছি"],
    "lesson.nextA11y": ["الخطوة التالية", "Next step", "مرحلهٔ بعد", "Sonraki adım", "अगला क़दम", "পরের ধাপ"],
    "lesson.previousA11y": ["الخطوة السابقة", "Previous step", "مرحلهٔ قبل", "Önceki adım", "पिछला क़दम", "আগের ধাপ"],
    "lesson.timeline": ["خطوات الدرس", "Lesson steps", "مراحل درس", "Dersin adımları", "पाठ के क़दम", "পাঠের ধাপসমূহ"],
    "step.of": ["الخطوة {0} من {1}", "Step {0} of {1}", "مرحلهٔ {0} از {1}", "Adım {0} / {1}", "क़दम {0} / {1}", "ধাপ {0} / {1}"],
    "step.wellDone": ["أحسنت", "Well done", "آفرین", "Aferin", "शाबाश", "সাবাশ"],
    "step.fromBook": ["من الكتاب", "From the book", "از کتاب", "Kitaptan", "किताब से", "বই থেকে"],
    "step.listen": ["استمع للخطوة", "Listen to this step", "به این مرحله گوش کن", "Bu adımı dinle", "यह क़दम सुनें", "এই ধাপটি শোনো"],
    "repeat.done": ["رائع! أكملت {0} مرات 🎉", "Great! You did it {0} times 🎉", "عالی! {0} بار انجام دادی 🎉", "Harika! {0} kez yaptın 🎉", "बहुत बढ़िया! {0} बार पूरा किया 🎉", "দারুণ! {0} বার সম্পন্ন করেছ 🎉"],
    "repeat.progress": ["المس القطرات: {0} من {1}", "Tap the drops: {0} of {1}", "قطره‌ها را لمس کن: {0} از {1}", "Damlalara dokun: {0} / {1}", "बूँदों को छुएँ: {0} / {1}", "ফোঁটাগুলো ছোঁও: {0} / {1}"],
    "repeat.time": ["المرة {0}", "Time {0}", "بار {0}", "{0}. kez", "{0}वीं बार", "{0} নম্বর বার"],
    "dua.say": ["قُل", "Say", "بگو", "Söyle", "कहें", "বলো"],
    "dua.meaning": ["المعنى", "Meaning", "معنا", "Anlamı", "अर्थ", "অর্থ"],
    "dua.listen": ["استمع للدعاء", "Listen to the supplication", "به دعا گوش کن", "Duayı dinle", "दुआ सुनें", "দোয়াটি শোনো"],
    "audio.stop": ["إيقاف القراءة", "Stop reading", "توقف خواندن", "Okumayı durdur", "पढ़ना रोकें", "পড়া থামাও"],
    "done.title": ["أحسنت! 🌟", "Well done! 🌟", "آفرین! 🌟", "Aferin! 🌟", "शाबाश! 🌟", "সাবাশ! 🌟"],
    "done.message": ["أتممت درس «{0}» خطوة بخطوة.\nبارك الله فيك!", "You completed “{0}” step by step.\nMay Allah bless you!", "درس «{0}» را قدم‌به‌قدم تمام کردی.\nخدا به تو برکت دهد!", "“{0}” dersini adım adım tamamladın.\nAllah seni mübarek kılsın!", "आपने “{0}” पाठ क़दम-ब-क़दम पूरा किया।\nअल्लाह आपको बरकत दे!", "তুমি “{0}” পাঠটি ধাপে ধাপে শেষ করেছ।\nআল্লাহ তোমাকে বরকত দিন!"],
    "done.restart": ["أعد الدرس", "Repeat lesson", "تکرار درس", "Dersi tekrarla", "पाठ दोहराएँ", "পাঠ আবার করো"],
    "done.back": ["العودة", "Home", "بازگشت", "Geri dön", "वापस", "ফিরে যাও"],
    "masala.startLesson": ["ابدأ درس «{0}» التفاعلي", "Start the “{0}” lesson", "شروع درس تعاملی «{0}»", "“{0}” dersini başlat", "“{0}” पाठ शुरू करें", "“{0}” পাঠ শুরু করো"],
    "masala.source": ["المصدر: {0} — ص {1}", "Source: {0} — p. {1}", "منبع: {0} — ص {1}", "Kaynak: {0} — s. {1}", "स्रोत: {0} — पृ. {1}", "সূত্র: {0} — পৃ. {1}"],
    "masala.listen": ["استمع للمسألة", "Listen to this topic", "به این مسئله گوش کن", "Bu meseleyi dinle", "यह मसला सुनें", "এই মাসআলাটি শোনো"],
    "masala.learned": ["تعلّمتُها ✓", "Learned ✓", "یاد گرفتم ✓", "Öğrendim ✓", "सीख लिया ✓", "শিখেছি ✓"],
    "masala.markLearned": ["تعلّمتُ هذه المسألة", "I learned this", "این مسئله را یاد گرفتم", "Bu meseleyi öğrendim", "मैंने यह मसला सीख लिया", "আমি এই মাসআলাটি শিখেছি"],
    "masala.hasLesson": ["فيها درس تفاعلي", "Has an interactive lesson", "درس تعاملی دارد", "Etkileşimli dersi var", "इसमें इंटरैक्टिव पाठ है", "এতে ইন্টারঅ্যাকটিভ পাঠ আছে"],
    "masala.learnedA11y": ["تم تعلّمها", "Learned", "یاد گرفته شد", "Öğrenildi", "सीखा गया", "শেখা হয়েছে"],
    "quiz.title": ["اختبر نفسك", "Test yourself", "خودت را بسنج", "Kendini dene", "ख़ुद को परखें", "নিজেকে যাচাই করো"],
    "quiz.best": ["أفضل نتيجة: {0} من {1}", "Best score: {0} of {1}", "بهترین نتیجه: {0} از {1}", "En iyi sonuç: {0} / {1}", "सबसे अच्छा स्कोर: {0} / {1}", "সেরা ফল: {0} / {1}"],
    "quiz.count": ["{0} أسئلة من القسم", "{0} questions from this chapter", "{0} پرسش از این بخش", "Bu bölümden {0} soru", "इस अध्याय से {0} सवाल", "এই অধ্যায় থেকে {0}টি প্রশ্ন"],
    "quiz.questionOf": ["سؤال {0} من {1}", "Question {0} of {1}", "پرسش {0} از {1}", "Soru {0} / {1}", "सवाल {0} / {1}", "প্রশ্ন {0} / {1}"],
    "quiz.correct": ["إجابة صحيحة! أحسنت 🌟", "Correct! Well done 🌟", "پاسخ درست! آفرین 🌟", "Doğru cevap! Aferin 🌟", "सही जवाब! शाबाश 🌟", "সঠিক উত্তর! সাবাশ 🌟"],
    "quiz.wrong": ["لا بأس، تعلّمنا شيئًا جديدًا", "No problem — we learned something new", "اشکالی ندارد، چیز تازه‌ای یاد گرفتیم", "Sorun değil, yeni bir şey öğrendik", "कोई बात नहीं, हमने कुछ नया सीखा", "সমস্যা নেই, আমরা নতুন কিছু শিখলাম"],
    "quiz.next": ["السؤال التالي", "Next question", "پرسش بعدی", "Sonraki soru", "अगला सवाल", "পরের প্রশ্ন"],
    "quiz.result": ["النتيجة", "See result", "نتیجه", "Sonuç", "परिणाम", "ফলাফল"],
    "quiz.perfect": ["ممتاز! علامة كاملة", "Excellent! Full marks", "عالی! نمرهٔ کامل", "Mükemmel! Tam puan", "बेहतरीन! पूरे अंक", "চমৎকার! পূর্ণ নম্বর"],
    "quiz.goodTry": ["أحسنت المحاولة!", "Good try!", "تلاش خوبی بود!", "Güzel deneme!", "अच्छी कोशिश!", "ভালো চেষ্টা!"],
    "quiz.score": ["نتيجتك: {0} من {1}", "Your score: {0} of {1}", "نتیجهٔ تو: {0} از {1}", "Puanın: {0} / {1}", "आपका स्कोर: {0} / {1}", "তোমার ফল: {0} / {1}"],
    "quiz.retry": ["أعد الاختبار", "Try again", "دوباره امتحان کن", "Tekrar dene", "फिर से करें", "আবার চেষ্টা করো"],
    "quiz.back": ["العودة للقسم", "Back to chapter", "بازگشت به بخش", "Bölüme dön", "अध्याय पर वापस", "অধ্যায়ে ফিরে যাও"],
    "about.title": ["عن التطبيق", "About", "دربارهٔ برنامه", "Hakkında", "ऐप के बारे में", "অ্যাপ সম্পর্কে"],
    "about.book": ["عن الكتاب", "About the book", "دربارهٔ کتاب", "Kitap hakkında", "किताब के बारे में", "বই সম্পর্কে"],
    "about.author": ["تأليف: {0}", "Author: {0}", "نویسنده: {0}", "Yazar: {0}", "लेखक: {0}", "লেখক: {0}"],
    "about.lessonsDone": ["الدروس المكتملة: {0} من {1}", "Lessons completed: {0} of {1}", "درس‌های کامل‌شده: {0} از {1}", "Tamamlanan dersler: {0} / {1}", "पूरे हुए पाठ: {0} / {1}", "সম্পন্ন পাঠ: {0} / {1}"],
    "about.reset": ["البدء من جديد", "Start over", "شروع دوباره", "Baştan başla", "फिर से शुरू करें", "নতুন করে শুরু করো"],
    "about.resetConfirm": ["هل تريد مسح كل التقدّم؟", "Erase all progress?", "همهٔ پیشرفت پاک شود؟", "Tüm ilerleme silinsin mi?", "क्या सारी प्रगति मिटा दें?", "সব অগ্রগতি মুছে ফেলবে?"],
    "about.resetAction": ["مسح التقدّم", "Erase progress", "پاک کردن پیشرفت", "İlerlemeyi sil", "प्रगति मिटाएँ", "অগ্রগতি মুছো"],
    "about.offline": ["يعمل التطبيق دون إنترنت بالكامل، وكل المحتوى مأخوذ من الكتاب مع تبسيط يسير للأطفال.", "The app works fully offline. All content comes from the book, lightly simplified for children.", "برنامه کاملاً بدون اینترنت کار می‌کند و همهٔ محتوا از کتاب گرفته شده و برای کودکان کمی ساده شده است.", "Uygulama tamamen internetsiz çalışır; tüm içerik kitaptan alınmış ve çocuklar için biraz sadeleştirilmiştir.", "ऐप पूरी तरह बिना इंटरनेट चलता है। सारी सामग्री किताब से ली गई है और बच्चों के लिए थोड़ी सरल की गई है।", "অ্যাপটি সম্পূর্ণ ইন্টারনেট ছাড়া চলে। সব বিষয়বস্তু বই থেকে নেওয়া, শিশুদের জন্য সামান্য সহজ করা।"],
    "about.translationNote": ["الترجمات لمعاني النصوص، والأدعية تبقى بالعربية كما وردت في الكتاب.", "Translations convey the meaning; supplications stay in Arabic as in the book.", "ترجمه‌ها معنای متن را می‌رسانند و دعاها همان‌طور که در کتاب آمده به عربی می‌مانند.", "Çeviriler anlamı aktarır; dualar kitaptaki gibi Arapça kalır.", "अनुवाद अर्थ बताते हैं; दुआएँ किताब की तरह अरबी में ही रहती हैं।", "অনুবাদে অর্থ তুলে ধরা হয়েছে; দোয়াগুলো বইয়ের মতো আরবিতেই রয়েছে।"],
    "common.cancel": ["إلغاء", "Cancel", "لغو", "İptal", "रद्द करें", "বাতিল"],
    "common.done": ["تم", "Done", "تمام", "Tamam", "हो गया", "সম্পন্ন"],
    "common.percent": ["{0}٪", "{0}%", "{0}٪", "%{0}", "{0}%", "{0}%"],
    "settings.title": ["الإعدادات", "Settings", "تنظیمات", "Ayarlar", "सेटिंग्स", "সেটিংস"],
    "settings.language": ["اللغة", "Language", "زبان", "Dil", "भाषा", "ভাষা"],
    "settings.audio": ["الصوت", "Audio", "صدا", "Ses", "आवाज़", "অডিও"],
    "settings.autoNarrate": ["قراءة كل خطوة تلقائيًا", "Read each step aloud automatically", "خواندن خودکار هر مرحله", "Her adımı otomatik oku", "हर क़दम अपने आप पढ़ें", "প্রতিটি ধাপ স্বয়ংক্রিয়ভাবে পড়ো"],
    "settings.autoNarrateFooter": ["أصوات طبيعية مسجّلة داخل التطبيق وتعمل دون إنترنت.", "Natural voices are bundled in the app and work offline.", "صداهای طبیعی درون برنامه‌اند و بدون اینترنت کار می‌کنند.", "Doğal sesler uygulamanın içindedir ve internetsiz çalışır.", "प्राकृतिक आवाज़ें ऐप में ही हैं और बिना इंटरनेट चलती हैं।", "স্বাভাবিক কণ্ঠগুলো অ্যাপের ভেতরেই আছে এবং ইন্টারনেট ছাড়া চলে।"],
    "settings.a11y": ["الإعدادات واللغة", "Settings and language", "تنظیمات و زبان", "Ayarlar ve dil", "सेटिंग्स और भाषा", "সেটিংস ও ভাষা"],
    "error.fileNotFound": ["لم يُعثر على الملف «{0}» داخل التطبيق.", "The file “{0}” was not found in the app.", "فایل «{0}» در برنامه پیدا نشد.", "“{0}” dosyası uygulamada bulunamadı.", "ऐप में “{0}” फ़ाइल नहीं मिली।", "অ্যাপে “{0}” ফাইলটি পাওয়া যায়নি।"],
    # --- v3: tab bar, question bank, settings, identity ---
    "tab.home": ["الرئيسية", "Home", "خانه", "Ana Sayfa", "होम", "হোম"],
    "tab.questions": ["الأسئلة", "Questions", "پرسش‌ها", "Sorular", "सवाल", "প্রশ্ন"],
    "tab.settings": ["الإعدادات", "Settings", "تنظیمات", "Ayarlar", "सेटिंग्स", "সেটিংস"],
    "common.close": ["إغلاق", "Close", "بستن", "Kapat", "बंद करें", "বন্ধ করো"],
    "bank.title": ["بنك الأسئلة", "Question bank", "بانک پرسش‌ها", "Soru bankası", "सवालों का बैंक", "প্রশ্ন ভান্ডার"],
    "bank.subtitle": ["{0} سؤالًا من الكتاب تظهر عشوائيًا", "{0} questions from the book, in random order", "{0} پرسش از کتاب، به‌صورت تصادفی", "Kitaptan rastgele {0} soru", "किताब से {0} सवाल, बेतरतीब क्रम में", "বই থেকে {0}টি প্রশ্ন, এলোমেলো ক্রমে"],
    "bank.loading": ["جارٍ تجهيز الأسئلة…", "Preparing questions…", "در حال آماده‌سازی پرسش‌ها…", "Sorular hazırlanıyor…", "सवाल तैयार हो रहे हैं…", "প্রশ্ন প্রস্তুত হচ্ছে…"],
    "bank.daily": ["سؤال اليوم", "Question of the day", "پرسش امروز", "Günün sorusu", "आज का सवाल", "আজকের প্রশ্ন"],
    "bank.newRound": ["جولة جديدة", "New round", "دور جدید", "Yeni tur", "नया दौर", "নতুন রাউন্ড"],
    "bank.newRoundSubtitle": ["اختر النوع والقسم وعدد الأسئلة", "Pick the type, chapter and number of questions", "نوع، بخش و تعداد پرسش‌ها را انتخاب کن", "Türü, bölümü ve soru sayısını seç", "प्रकार, अध्याय और सवालों की संख्या चुनें", "ধরন, অধ্যায় ও প্রশ্নের সংখ্যা বেছে নাও"],
    "bank.filter.all": ["الكل", "All", "همه", "Tümü", "सभी", "সব"],
    "bank.filter.choice": ["اختيار من متعدد", "Multiple choice", "چندگزینه‌ای", "Çoktan seçmeli", "बहुविकल्पी", "বহুনির্বাচনী"],
    "bank.filter.written": ["كتابة", "Written", "نوشتاری", "Yazılı", "लिखित", "লিখিত"],
    "bank.kind.choice": ["اختيار من متعدد", "Multiple choice", "چندگزینه‌ای", "Çoktan seçmeli", "बहुविकल्पी", "বহুনির্বাচনী"],
    "bank.kind.written": ["اكتب الإجابة", "Write the answer", "پاسخ را بنویس", "Cevabı yaz", "जवाब लिखें", "উত্তর লেখো"],
    "bank.chapter": ["القسم", "Chapter", "بخش", "Bölüm", "अध्याय", "অধ্যায়"],
    "bank.allChapters": ["كل الأقسام", "All chapters", "همهٔ بخش‌ها", "Tüm bölümler", "सभी अध्याय", "সব অধ্যায়"],
    "bank.roundLength": ["عدد الأسئلة", "Questions", "تعداد پرسش", "Soru sayısı", "सवालों की संख्या", "প্রশ্নের সংখ্যা"],
    "bank.start": ["ابدأ ({0} سؤالًا متاحًا)", "Start ({0} available)", "شروع ({0} پرسش)", "Başla ({0} soru)", "शुरू करें ({0} उपलब्ध)", "শুরু করো ({0}টি আছে)"],
    "bank.typeAnswer": ["اكتب الكلمة هنا…", "Type the word here…", "کلمه را اینجا بنویس…", "Kelimeyi buraya yaz…", "शब्द यहाँ लिखें…", "শব্দটি এখানে লেখো…"],
    "bank.hint": ["تلميح", "Hint", "راهنما", "İpucu", "संकेत", "ইঙ্গিত"],
    "bank.check": ["تحقّق", "Check", "بررسی", "Kontrol et", "जाँचें", "যাচাই করো"],
    "bank.dontKnow": ["لا أعرف", "I don’t know", "نمی‌دانم", "Bilmiyorum", "मुझे नहीं पता", "জানি না"],
    "bank.correctAnswer": ["الإجابة الصحيحة: {0}", "Correct answer: {0}", "پاسخ درست: {0}", "Doğru cevap: {0}", "सही जवाब: {0}", "সঠিক উত্তর: {0}"],
    "bank.anotherRound": ["جولة أخرى", "Another round", "دور دیگر", "Bir tur daha", "एक और दौर", "আরেক রাউন্ড"],
    "stats.answered": ["إجابة", "Answered", "پاسخ", "Cevaplanan", "जवाब दिए", "উত্তর দেওয়া"],
    "stats.accuracy": ["الدقّة", "Accuracy", "دقت", "Doğruluk", "सटीकता", "নির্ভুলতা"],
    "stats.bestStreak": ["أفضل سلسلة", "Best streak", "بهترین زنجیره", "En iyi seri", "सबसे लंबी लड़ी", "সেরা ধারাবাহিকতা"],
    "stats.days": ["أيام متتالية", "Day streak", "روزهای پیاپی", "Gün serisi", "लगातार दिन", "টানা দিন"],
    "stats.roundStreak": ["أطول سلسلة", "Longest streak", "بلندترین زنجیره", "En uzun seri", "सबसे लंबी लड़ी", "দীর্ঘতম ধারাবাহিকতা"],
    "settings.appearance": ["المظهر", "Appearance", "ظاهر", "Görünüm", "रूप", "চেহারা"],
    "appearance.system": ["تلقائي", "Automatic", "خودکار", "Otomatik", "अपने आप", "স্বয়ংক্রিয়"],
    "appearance.light": ["نهاري", "Light", "روشن", "Açık", "हल्का", "হালকা"],
    "appearance.dark": ["ليلي", "Dark", "تیره", "Koyu", "गहरा", "গাঢ়"],
    "settings.background": ["خلفية التطبيق", "App background", "پس‌زمینهٔ برنامه", "Uygulama arka planı", "ऐप का बैकग्राउंड", "অ্যাপের পটভূমি"],
    "theme.classic": ["كلاسيكي", "Classic", "کلاسیک", "Klasik", "क्लासिक", "ক্লাসিক"],
    "theme.ocean": ["محيط", "Ocean", "اقیانوس", "Okyanus", "सागर", "সমুদ্র"],
    "theme.sunset": ["غروب", "Sunset", "غروب", "Gün batımı", "सूर्यास्त", "সূর্যাস্ত"],
    "theme.emerald": ["زمرّد", "Emerald", "زمرد", "Zümrüt", "पन्ना", "পান্না"],
    "theme.royal": ["ملكي", "Royal", "سلطنتی", "Kraliyet", "शाही", "রাজকীয়"],
    "settings.appIcon": ["أيقونة التطبيق", "App icon", "آیکون برنامه", "Uygulama simgesi", "ऐप आइकन", "অ্যাপ আইকন"],
    "icon.classic": ["الأساسية", "Classic", "کلاسیک", "Klasik", "क्लासिक", "ক্লাসিক"],
    "icon.night": ["ليل", "Night", "شب", "Gece", "रात", "রাত"],
    "icon.desert": ["صحراء", "Desert", "صحرا", "Çöl", "रेगिस्तान", "মরুভূমি"],
    "icon.emerald": ["زمرّد", "Emerald", "زمرد", "Zümrüt", "पन्ना", "পান্না"],
    "icon.rose": ["ورد", "Rose", "گل سرخ", "Gül", "गुलाब", "গোলাপ"],
    "settings.tashkeel": ["إظهار التشكيل", "Show diacritics", "نمایش اعراب", "Harekeleri göster", "हरकात दिखाएँ", "হরকত দেখাও"],
    "settings.tashkeelFooter": ["تشكيل كامل لنصوص المسائل والخطوات يساعد على القراءة الصحيحة.", "Full vowel marks on topics and steps for correct reading.", "اعراب کامل متن‌ها برای خواندن درست.", "Doğru okuma için tam hareke.", "सही पढ़ने के लिए पूरी हरकात।", "সঠিক পড়ার জন্য পূর্ণ হরকত।"],
    "settings.speed": ["سرعة القراءة", "Reading speed", "سرعت خواندن", "Okuma hızı", "पढ़ने की रफ़्तार", "পড়ার গতি"],
    "settings.speedReset": ["٠٪", "0%", "۰٪", "%0", "0%", "০%"],
    "settings.general": ["عام", "General", "عمومی", "Genel", "सामान्य", "সাধারণ"],
    "settings.haptics": ["الاهتزاز عند اللمس", "Haptic feedback", "لرزش هنگام لمس", "Dokunsal geri bildirim", "छूने पर कंपन", "স্পর্শে কম্পন"],
    "settings.reminder": ["تذكير يومي بالتعلّم", "Daily learning reminder", "یادآور روزانهٔ یادگیری", "Günlük öğrenme hatırlatıcısı", "रोज़ाना सीखने की याद", "প্রতিদিন শেখার রিমাইন্ডার"],
    "settings.reminderFooter": ["إشعار لطيف كل يوم في الوقت الذي تختاره.", "A gentle notification every day at your chosen time.", "هر روز در زمان دلخواه یک اعلان ملایم.", "Seçtiğin saatte her gün nazik bir bildirim.", "आपके चुने समय पर रोज़ एक हल्की सूचना।", "তোমার বেছে নেওয়া সময়ে প্রতিদিন একটি নোটিফিকেশন।"],
    "settings.reminderDenied": ["فعّل الإشعارات للتطبيق من إعدادات الجهاز أولًا.", "Allow notifications for the app in the device Settings first.", "ابتدا اعلان‌ها را در تنظیمات دستگاه فعال کن.", "Önce cihaz ayarlarından bildirimlere izin ver.", "पहले डिवाइस सेटिंग्स में सूचनाएँ चालू करें।", "আগে ডিভাইসের সেটিংসে নোটিফিকেশন চালু করো।"],
    "settings.reminderTime": ["وقت التذكير", "Reminder time", "زمان یادآوری", "Hatırlatma saati", "याद दिलाने का समय", "রিমাইন্ডারের সময়"],
    "settings.progress": ["التقدّم", "Progress", "پیشرفت", "İlerleme", "प्रगति", "অগ্রগতি"],
    "settings.progressDetails": ["تفاصيل تقدّمي", "My progress details", "جزئیات پیشرفت من", "İlerleme ayrıntıları", "मेरी प्रगति का विवरण", "আমার অগ্রগতির বিবরণ"],
    "settings.support": ["الدعم والمشاركة", "Support & sharing", "پشتیبانی و اشتراک‌گذاری", "Destek ve paylaşım", "सहायता और साझा करें", "সহায়তা ও শেয়ার"],
    "settings.contactSupport": ["راسل الدعم الفني", "Contact support", "تماس با پشتیبانی", "Destekle iletişim", "सहायता से संपर्क करें", "সহায়তায় যোগাযোগ করো"],
    "settings.supportSubject": ["دعم تطبيق ثقافة إسلامية", "Islamic Culture app support", "پشتیبانی برنامهٔ فرهنگ اسلامی", "İslami Kültür uygulama desteği", "इस्लामी संस्कृति ऐप सहायता", "ইসলামী সংস্কৃতি অ্যাপ সহায়তা"],
    "settings.copyEmail": ["نسخ البريد الإلكتروني", "Copy email address", "کپی نشانی ایمیل", "E-posta adresini kopyala", "ईमेल पता कॉपी करें", "ইমেইল ঠিকানা কপি করো"],
    "settings.copied": ["تم النسخ ✓", "Copied ✓", "کپی شد ✓", "Kopyalandı ✓", "कॉपी हो गया ✓", "কপি হয়েছে ✓"],
    "settings.share": ["شارك التطبيق", "Share the app", "اشتراک‌گذاری برنامه", "Uygulamayı paylaş", "ऐप साझा करें", "অ্যাপটি শেয়ার করো"],
    "settings.shareText": ["تطبيق «{0}» — تعلّم الوضوء والصلاة وأحكام الدين خطوة بخطوة من كتاب «تلقين الصبيان»، دون إنترنت. من تطوير {1}.", "“{0}” — learn wudu, prayer and the basics of the faith step by step from the book “Talqeen al-Sibyan”, fully offline. Developed by {1}.", "«{0}» — وضو، نماز و احکام دین را قدم‌به‌قدم از کتاب «تلقین الصبیان» بدون اینترنت بیاموز. ساختهٔ {1}.", "“{0}” — abdest, namaz ve dinin temellerini “Talkinü’s-Sıbyan” kitabından adım adım, internetsiz öğren. Geliştiren: {1}.", "“{0}” — “तल्क़ीनुस-सिब्यान” किताब से वुज़ू, नमाज़ और दीन की बुनियादी बातें क़दम-ब-क़दम, बिना इंटरनेट सीखें। विकसित: {1}.", "“{0}” — “তালকীনুস সিবইয়ান” বই থেকে অজু, নামাজ ও দ্বীনের মৌলিক বিষয় ধাপে ধাপে, ইন্টারনেট ছাড়াই শেখো। নির্মাতা: {1}।"],
    "settings.version": ["الإصدار {0}", "Version {0}", "نسخهٔ {0}", "Sürüm {0}", "संस्करण {0}", "সংস্করণ {0}"],
    "brand.developedBy": ["تم تطويره بواسطة {0} © {1}", "Developed by Saqer Store © {1}", "توسعه‌یافته توسط Saqer Store © {1}", "Saqer Store tarafından geliştirildi © {1}", "Saqer Store द्वारा विकसित © {1}", "Saqer Store দ্বারা নির্মিত © {1}"],
    "brand.tagline": ["تعلّم دينك خطوة بخطوة", "Learn your faith step by step", "دینت را قدم‌به‌قدم بیاموز", "Dinini adım adım öğren", "अपना दीन क़दम-ब-क़दम सीखें", "তোমার দ্বীন ধাপে ধাপে শেখো"],
    "reminder.title": ["ثقافة إسلامية 🌙", "Islamic Culture 🌙", "فرهنگ اسلامی 🌙", "İslami Kültür 🌙", "इस्लामी संस्कृति 🌙", "ইসলামী সংস্কৃতি 🌙"],
    "reminder.body": ["حان وقت درسك اليومي — سؤال واحد يكفي لتبدأ ✨", "Time for today’s lesson — one question is enough to start ✨", "وقت درس امروز است — یک پرسش برای شروع کافی است ✨", "Günlük ders zamanı — başlamak için bir soru yeter ✨", "आज के पाठ का समय — शुरू करने के लिए एक सवाल काफ़ी है ✨", "আজকের পাঠের সময় — শুরু করতে একটি প্রশ্নই যথেষ্ট ✨"],
}

out = {}
for key, values in S.items():
    assert len(values) == len(LANGS), key
    out[key] = dict(zip(LANGS, values))

path = os.path.join(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "ThaqafaIslamiya", "Assets", "Data"), "UIStrings.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=1, sort_keys=True)
print(len(out), "keys")
