"""UI strings for all languages -> Assets/Data/UIStrings.json  ({key: {lang: text}}).
Placeholders: {0}, {1} …  (replaced in Swift by L10n.t)."""
import json, os

LANGS = ["ar", "en", "fa", "tr", "hi", "bn"]

S = {
    "app.name": ["ثقافة إسلامية", "Islamic Culture", "فرهنگ اسلامی", "İslami Kültür", "इस्लामी संस्कृति", "ইসলামী সংস্কৃতি"],
    "home.greeting": ["السلام عليكم 👋", "Assalamu alaikum 👋", "السلام علیکم 👋", "Esselâmu aleyküm 👋", "अस्सलामु अलैकुम 👋", "আসসালামু আলাইকুম 👋"],
    "home.myProgress": ["تقدّمي", "My progress", "پیشرفت من", "İlerlemem", "मेरी प्रगति", "আমার অগ্রগতি"],
    "home.progressA11y": ["تقدّمك وعن الكتاب", "Your progress and about the book", "پیشرفت شما و درباره کتاب", "İlerlemen ve kitap hakkında", "आपकी प्रगति और किताब के बारे में", "তোমার অগ্রগতি ও বই সম্পর্কে"],
    "home.lessons.title": ["رحلات تفاعلية", "Interactive journeys", "سفرهای تعاملی", "Etkileşimli yolculuklar", "इंटरैक्टिव सफ़र", "ইন্টারঅ্যাকটিভ যাত্রা"],
    "home.lessons.subtitle": ["تعلّم خطوة بخطوة بالبطاقات", "Learn step by step with cards", "با کارت‌ها قدم‌به‌قدم بیاموز", "Kartlarla adım adım öğren", "कार्ड के साथ क़दम-ब-क़दम सीखें", "কার্ডে ধাপে ধাপে শেখো"],
    "home.chapters.title": ["أقسام الكتاب", "Book chapters", "بخش‌های کتاب", "Kitabın bölümleri", "किताब के अध्याय", "বইয়ের অধ্যায়সমূহ"],
    "home.chapters.subtitle": ["{0} مسألة في {1} قسمًا", "{0} topics in {1} chapters", "{0} مسئله در {1} بخش", "{1} bölümde {0} mesele", "{1} अध्यायों में {0} मसले", "{1}টি অধ্যায়ে {0}টি মাসআলা"],
    "search.placeholder": ["ابحث عن مسألة… (الوضوء، الزكاة، الجار)", "Search a topic… (wudu, zakat, neighbour)", "جستجوی مسئله… (وضو، زکات، همسایه)", "Mesele ara… (abdest, zekât, komşu)", "मसला खोजें… (वुज़ू, ज़कात, पड़ोसी)", "মাসআলা খোঁজো… (অজু, যাকাত, প্রতিবেশী)"],
    "search.clear": ["مسح البحث", "Clear search", "پاک کردن جستجو", "Aramayı temizle", "खोज साफ़ करें", "খোঁজ মুছে ফেলো"],
    "search.title": ["نتائج البحث", "Search results", "نتایج جستجو", "Arama sonuçları", "खोज परिणाम", "খোঁজের ফলাফল"],
    "search.count": ["{0} نتيجة", "{0} results", "{0} نتیجه", "{0} sonuç", "{0} परिणाम", "{0}টি ফলাফল"],
    "search.empty": ["لم نجد مسألة بهذا الاسم، جرّب كلمة أخرى 🌱", "No topic found — try another word 🌱", "مسئله‌ای با این نام پیدا نشد، کلمهٔ دیگری امتحان کن 🌱", "Bu adla mesele bulunamadı, başka bir kelime dene 🌱", "इस नाम का कोई मसला नहीं मिला, दूसरा शब्द आज़माएँ 🌱", "এই নামে কোনো মাসআলা পাওয়া যায়নি, অন্য শব্দ চেষ্টা করো 🌱"],
    "chapter.masailCount": ["{0} مسألة", "{0} topics", "{0} مسئله", "{0} mesele", "{0} मसले", "{0}টি মাসআলা"],
    "chapter.openHint": ["افتح القسم", "Open chapter", "باز کردن بخش", "Bölümü aç", "अध्याय खोलें", "অধ্যায় খোলো"],
    "chapter.learnInteractive": ["تعلّم بالتفاعل", "Learn by doing", "یادگیری تعاملی", "Yaparak öğren", "करके सीखें", "করে করে শেখো"],
    "chapter.masail": ["المسائل", "Topics", "مسائل", "Meseleler", "मसले", "মাসআলাসমূহ"],
    "chapter.masailSubtitle": ["اختر مسألة لتتعلّمها", "Choose a topic to learn", "یک مسئله برای یادگیری انتخاب کن", "Öğrenmek için bir mesele seç", "सीखने के लिए एक मसला चुनें", "শেখার জন্য একটি মাসআলা বেছে নাও"],
    "lesson.stepsCount": ["{0} خطوة", "{0} steps", "{0} مرحله", "{0} adım", "{0} क़दम", "{0}টি ধাপ"],
    "lesson.startHint": ["ابدأ الدرس التفاعلي", "Start the interactive lesson", "شروع درس تعاملی", "Etkileşimli dersi başlat", "इंटरैक्टिव पाठ शुरू करें", "ইন্টারঅ্যাকটিভ পাঠ শুরু করো"],
    "lesson.close": ["إغلاق الدرس", "Close lesson", "بستن درس", "Dersi kapat", "पाठ बंद करें", "পাঠ বন্ধ করো"],
    "lesson.swipeHintRTL": ["اسحب البطاقة إلى اليمين للخطوة التالية 👉", "Swipe the card right for the next step 👉", "کارت را به راست بکش تا مرحلهٔ بعد بیاید 👉", "Sonraki adım için kartı sağa kaydır 👉", "अगले क़दम के लिए कार्ड को दाईं ओर खींचें 👉", "পরের ধাপের জন্য কার্ডটি ডানে সরাও 👉"],
    "lesson.swipeHintLTR": ["اسحب البطاقة إلى اليسار للخطوة التالية 👈", "Swipe the card left for the next step 👈", "کارت را به چپ بکش تا مرحلهٔ بعد بیاید 👈", "Sonraki adım için kartı sola kaydır 👈", "अगले क़दम के लिए कार्ड को बाईं ओर खींचें 👈", "পরের ধাপের জন্য কার্ডটি বাঁয়ে সরাও 👈"],
    "lesson.previous": ["السابق", "Back", "قبلی", "Geri", "पिछला", "আগের"],
    "lesson.next": ["التالي", "Next", "بعدی", "İleri", "अगला", "পরের"],
    "lesson.finish": ["أتممتُ الدرس", "I finished!", "درس را تمام کردم", "Dersi bitirdim", "पाठ पूरा किया", "পাঠ শেষ করেছি"],
    "lesson.nextA11y": ["الخطوة التالية", "Next step", "مرحلهٔ بعد", "Sonraki adım", "अगला क़दम", "পরের ধাপ"],
    "lesson.previousA11y": ["الخطوة السابقة", "Previous step", "مرحلهٔ قبل", "Önceki adım", "पिछला क़दम", "আগের ধাপ"],
    "lesson.timeline": ["خطوات الدرس", "Lesson steps", "مراحل درس", "Dersin adımları", "पाठ के क़दम", "পাঠের ধাপসমূহ"],
    "step.of": ["الخطوة {0} من {1}", "Step {0} of {1}", "مرحلهٔ {0} از {1}", "Adım {0} / {1}", "क़दम {0} / {1}", "ধাপ {0} / {1}"],
    "step.wellDone": ["أحسنت", "Well done", "آفرین", "Aferin", "शाबाश", "সাবাশ"],
    "step.fromBook": ["من الكتاب", "From the book", "از کتاب", "Kitaptan", "किताब से", "বই থেকে"],
    "step.listen": ["استمع للخطوة", "Listen to this step", "به این مرحله گوش کن", "Bu adımı dinle", "यह क़दम सुनें", "এই ধাপটি শোনো"],
    "repeat.done": ["رائع! أكملت {0} مرات 🎉", "Great! You did it {0} times 🎉", "عالی! {0} بار انجام دادی 🎉", "Harika! {0} kez yaptın 🎉", "बहुत बढ़िया! {0} बार पूरा किया 🎉", "দারুণ! {0} বার সম্পন্ন করেছ 🎉"],
    "repeat.progress": ["المس القطرات: {0} من {1}", "Tap the drops: {0} of {1}", "قطره‌ها را لمس کن: {0} از {1}", "Damlalara dokun: {0} / {1}", "बूँदों को छुएँ: {0} / {1}", "ফোঁটাগুলো ছোঁও: {0} / {1}"],
    "repeat.time": ["المرة {0}", "Time {0}", "بار {0}", "{0}. kez", "{0}वीं बार", "{0} নম্বর বার"],
    "dua.say": ["قُل", "Say", "بگو", "Söyle", "कहें", "বলো"],
    "dua.meaning": ["المعنى", "Meaning", "معنا", "Anlamı", "अर्थ", "অর্থ"],
    "dua.listen": ["استمع للدعاء", "Listen to the supplication", "به دعا گوش کن", "Duayı dinle", "दुआ सुनें", "দোয়াটি শোনো"],
    "audio.stop": ["إيقاف القراءة", "Stop reading", "توقف خواندن", "Okumayı durdur", "पढ़ना रोकें", "পড়া থামাও"],
    "done.title": ["أحسنت! 🌟", "Well done! 🌟", "آفرین! 🌟", "Aferin! 🌟", "शाबाश! 🌟", "সাবাশ! 🌟"],
    "done.message": ["أتممت درس «{0}» خطوة بخطوة.\nبارك الله فيك!", "You completed “{0}” step by step.\nMay Allah bless you!", "درس «{0}» را قدم‌به‌قدم تمام کردی.\nخدا به تو برکت دهد!", "“{0}” dersini adım adım tamamladın.\nAllah seni mübarek kılsın!", "आपने “{0}” पाठ क़दम-ब-क़दम पूरा किया।\nअल्लाह आपको बरकत दे!", "তুমি “{0}” পাঠটি ধাপে ধাপে শেষ করেছ।\nআল্লাহ তোমাকে বরকত দিন!"],
    "done.restart": ["أعد الدرس", "Repeat lesson", "تکرار درس", "Dersi tekrarla", "पाठ दोहराएँ", "পাঠ আবার করো"],
    "done.back": ["العودة", "Home", "بازگشت", "Geri dön", "वापस", "ফিরে যাও"],
    "masala.startLesson": ["ابدأ درس «{0}» التفاعلي", "Start the “{0}” lesson", "شروع درس تعاملی «{0}»", "“{0}” dersini başlat", "“{0}” पाठ शुरू करें", "“{0}” পাঠ শুরু করো"],
    "masala.source": ["المصدر: {0} — ص {1}", "Source: {0} — p. {1}", "منبع: {0} — ص {1}", "Kaynak: {0} — s. {1}", "स्रोत: {0} — पृ. {1}", "সূত্র: {0} — পৃ. {1}"],
    "masala.listen": ["استمع للمسألة", "Listen to this topic", "به این مسئله گوش کن", "Bu meseleyi dinle", "यह मसला सुनें", "এই মাসআলাটি শোনো"],
    "masala.learned": ["تعلّمتُها ✓", "Learned ✓", "یاد گرفتم ✓", "Öğrendim ✓", "सीख लिया ✓", "শিখেছি ✓"],
    "masala.markLearned": ["تعلّمتُ هذه المسألة", "I learned this", "این مسئله را یاد گرفتم", "Bu meseleyi öğrendim", "मैंने यह मसला सीख लिया", "আমি এই মাসআলাটি শিখেছি"],
    "masala.hasLesson": ["فيها درس تفاعلي", "Has an interactive lesson", "درس تعاملی دارد", "Etkileşimli dersi var", "इसमें इंटरैक्टिव पाठ है", "এতে ইন্টারঅ্যাকটিভ পাঠ আছে"],
    "masala.learnedA11y": ["تم تعلّمها", "Learned", "یاد گرفته شد", "Öğrenildi", "सीखा गया", "শেখা হয়েছে"],
    "quiz.title": ["اختبر نفسك", "Test yourself", "خودت را بسنج", "Kendini dene", "ख़ुद को परखें", "নিজেকে যাচাই করো"],
    "quiz.best": ["أفضل نتيجة: {0} من {1}", "Best score: {0} of {1}", "بهترین نتیجه: {0} از {1}", "En iyi sonuç: {0} / {1}", "सबसे अच्छा स्कोर: {0} / {1}", "সেরা ফল: {0} / {1}"],
    "quiz.count": ["{0} أسئلة من القسم", "{0} questions from this chapter", "{0} پرسش از این بخش", "Bu bölümden {0} soru", "इस अध्याय से {0} सवाल", "এই অধ্যায় থেকে {0}টি প্রশ্ন"],
    "quiz.questionOf": ["سؤال {0} من {1}", "Question {0} of {1}", "پرسش {0} از {1}", "Soru {0} / {1}", "सवाल {0} / {1}", "প্রশ্ন {0} / {1}"],
    "quiz.correct": ["إجابة صحيحة! أحسنت 🌟", "Correct! Well done 🌟", "پاسخ درست! آفرین 🌟", "Doğru cevap! Aferin 🌟", "सही जवाब! शाबाश 🌟", "সঠিক উত্তর! সাবাশ 🌟"],
    "quiz.wrong": ["لا بأس، تعلّمنا شيئًا جديدًا", "No problem — we learned something new", "اشکالی ندارد، چیز تازه‌ای یاد گرفتیم", "Sorun değil, yeni bir şey öğrendik", "कोई बात नहीं, हमने कुछ नया सीखा", "সমস্যা নেই, আমরা নতুন কিছু শিখলাম"],
    "quiz.next": ["السؤال التالي", "Next question", "پرسش بعدی", "Sonraki soru", "अगला सवाल", "পরের প্রশ্ন"],
    "quiz.result": ["النتيجة", "See result", "نتیجه", "Sonuç", "परिणाम", "ফলাফল"],
    "quiz.perfect": ["ممتاز! علامة كاملة", "Excellent! Full marks", "عالی! نمرهٔ کامل", "Mükemmel! Tam puan", "बेहतरीन! पूरे अंक", "চমৎকার! পূর্ণ নম্বর"],
    "quiz.goodTry": ["أحسنت المحاولة!", "Good try!", "تلاش خوبی بود!", "Güzel deneme!", "अच्छी कोशिश!", "ভালো চেষ্টা!"],
    "quiz.score": ["نتيجتك: {0} من {1}", "Your score: {0} of {1}", "نتیجهٔ تو: {0} از {1}", "Puanın: {0} / {1}", "आपका स्कोर: {0} / {1}", "তোমার ফল: {0} / {1}"],
    "quiz.retry": ["أعد الاختبار", "Try again", "دوباره امتحان کن", "Tekrar dene", "फिर से करें", "আবার চেষ্টা করো"],
    "quiz.back": ["العودة للقسم", "Back to chapter", "بازگشت به بخش", "Bölüme dön", "अध्याय पर वापस", "অধ্যায়ে ফিরে যাও"],
    "about.title": ["عن التطبيق", "About", "دربارهٔ برنامه", "Hakkında", "ऐप के बारे में", "অ্যাপ সম্পর্কে"],
    "about.book": ["عن الكتاب", "About the book", "دربارهٔ کتاب", "Kitap hakkında", "किताब के बारे में", "বই সম্পর্কে"],
    "about.author": ["تأليف: {0}", "Author: {0}", "نویسنده: {0}", "Yazar: {0}", "लेखक: {0}", "লেখক: {0}"],
    "about.lessonsDone": ["الدروس المكتملة: {0} من {1}", "Lessons completed: {0} of {1}", "درس‌های کامل‌شده: {0} از {1}", "Tamamlanan dersler: {0} / {1}", "पूरे हुए पाठ: {0} / {1}", "সম্পন্ন পাঠ: {0} / {1}"],
    "about.reset": ["البدء من جديد", "Start over", "شروع دوباره", "Baştan başla", "फिर से शुरू करें", "নতুন করে শুরু করো"],
    "about.resetConfirm": ["هل تريد مسح كل التقدّم؟", "Erase all progress?", "همهٔ پیشرفت پاک شود؟", "Tüm ilerleme silinsin mi?", "क्या सारी प्रगति मिटा दें?", "সব অগ্রগতি মুছে ফেলবে?"],
    "about.resetAction": ["مسح التقدّم", "Erase progress", "پاک کردن پیشرفت", "İlerlemeyi sil", "प्रगति मिटाएँ", "অগ্রগতি মুছো"],
    "about.offline": ["يعمل التطبيق دون إنترنت بالكامل، وكل المحتوى مأخوذ من الكتاب مع تبسيط يسير للأطفال.", "The app works fully offline. All content comes from the book, lightly simplified for children.", "برنامه کاملاً بدون اینترنت کار می‌کند و همهٔ محتوا از کتاب گرفته شده و برای کودکان کمی ساده شده است.", "Uygulama tamamen internetsiz çalışır; tüm içerik kitaptan alınmış ve çocuklar için biraz sadeleştirilmiştir.", "ऐप पूरी तरह बिना इंटरनेट चलता है। सारी सामग्री किताब से ली गई है और बच्चों के लिए थोड़ी सरल की गई है।", "অ্যাপটি সম্পূর্ণ ইন্টারনেট ছাড়া চলে। সব বিষয়বস্তু বই থেকে নেওয়া, শিশুদের জন্য সামান্য সহজ করা।"],
    "about.translationNote": ["الترجمات لمعاني النصوص، والأدعية تبقى بالعربية كما وردت في الكتاب.", "Translations convey the meaning; supplications stay in Arabic as in the book.", "ترجمه‌ها معنای متن را می‌رسانند و دعاها همان‌طور که در کتاب آمده به عربی می‌مانند.", "Çeviriler anlamı aktarır; dualar kitaptaki gibi Arapça kalır.", "अनुवाद अर्थ बताते हैं; दुआएँ किताब की तरह अरबी में ही रहती हैं।", "অনুবাদে অর্থ তুলে ধরা হয়েছে; দোয়াগুলো বইয়ের মতো আরবিতেই রয়েছে।"],
    "common.cancel": ["إلغاء", "Cancel", "لغو", "İptal", "रद्द करें", "বাতিল"],
    "common.done": ["تم", "Done", "تمام", "Tamam", "हो गया", "সম্পন্ন"],
    "common.percent": ["{0}٪", "{0}%", "{0}٪", "%{0}", "{0}%", "{0}%"],
    "settings.title": ["الإعدادات", "Settings", "تنظیمات", "Ayarlar", "सेटिंग्स", "সেটিংস"],
    "settings.language": ["اللغة", "Language", "زبان", "Dil", "भाषा", "ভাষা"],
    "settings.audio": ["الصوت", "Audio", "صدا", "Ses", "आवाज़", "অডিও"],
    "settings.autoNarrate": ["قراءة كل خطوة تلقائيًا", "Read each step aloud automatically", "خواندن خودکار هر مرحله", "Her adımı otomatik oku", "हर क़दम अपने आप पढ़ें", "প্রতিটি ধাপ স্বয়ংক্রিয়ভাবে পড়ো"],
    "settings.autoNarrateFooter": ["أصوات طبيعية مسجّلة داخل التطبيق وتعمل دون إنترنت.", "Natural voices are bundled in the app and work offline.", "صداهای طبیعی درون برنامه‌اند و بدون اینترنت کار می‌کنند.", "Doğal sesler uygulamanın içindedir ve internetsiz çalışır.", "प्राकृतिक आवाज़ें ऐप में ही हैं और बिना इंटरनेट चलती हैं।", "স্বাভাবিক কণ্ঠগুলো অ্যাপের ভেতরেই আছে এবং ইন্টারনেট ছাড়া চলে।"],
    "settings.a11y": ["الإعدادات واللغة", "Settings and language", "تنظیمات و زبان", "Ayarlar ve dil", "सेटिंग्स और भाषा", "সেটিংস ও ভাষা"],
    "error.fileNotFound": ["لم يُعثر على الملف «{0}» داخل التطبيق.", "The file “{0}” was not found in the app.", "فایل «{0}» در برنامه پیدا نشد.", "“{0}” dosyası uygulamada bulunamadı.", "ऐप में “{0}” फ़ाइल नहीं मिली।", "অ্যাপে “{0}” ফাইলটি পাওয়া যায়নি।"],
}

out = {}
for key, values in S.items():
    assert len(values) == len(LANGS), key
    out[key] = dict(zip(LANGS, values))

path = os.path.join(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "ThaqafaIslamiya", "Assets", "Data"), "UIStrings.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=1, sort_keys=True)
print(len(out), "keys")
